var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(q,u,t){q instanceof String&&(q=String(q));for(var B=q.length,y=0;y<B;y++){var P=q[y];if(u.call(t,P,y,q))return{i:y,v:P}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(q,u,t){if(q==Array.prototype||q==Object.prototype)return q;q[u]=t.value;return q};$jscomp.getGlobal=function(q){q=["object"==typeof globalThis&&globalThis,q,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var u=0;u<q.length;++u){var t=q[u];if(t&&t.Math==Math)return t}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(q,u){var t=$jscomp.propertyToPolyfillSymbol[u];if(null==t)return q[u];t=q[t];return void 0!==t?t:q[u]};
$jscomp.polyfill=function(q,u,t,B){u&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(q,u,t,B):$jscomp.polyfillUnisolated(q,u,t,B))};$jscomp.polyfillUnisolated=function(q,u,t,B){t=$jscomp.global;q=q.split(".");for(B=0;B<q.length-1;B++){var y=q[B];if(!(y in t))return;t=t[y]}q=q[q.length-1];B=t[q];u=u(B);u!=B&&null!=u&&$jscomp.defineProperty(t,q,{configurable:!0,writable:!0,value:u})};
$jscomp.polyfillIsolated=function(q,u,t,B){var y=q.split(".");q=1===y.length;B=y[0];B=!q&&B in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var P=0;P<y.length-1;P++){var v=y[P];if(!(v in B))return;B=B[v]}y=y[y.length-1];t=$jscomp.IS_SYMBOL_NATIVE&&"es6"===t?B[y]:null;u=u(t);null!=u&&(q?$jscomp.defineProperty($jscomp.polyfills,y,{configurable:!0,writable:!0,value:u}):u!==t&&(void 0===$jscomp.propertyToPolyfillSymbol[y]&&(t=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[y]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(y):$jscomp.POLYFILL_PREFIX+t+"$"+y),$jscomp.defineProperty(B,$jscomp.propertyToPolyfillSymbol[y],{configurable:!0,writable:!0,value:u})))};$jscomp.polyfill("Array.prototype.find",function(q){return q?q:function(u,t){return $jscomp.findInternal(this,u,t).v}},"es6","es3");
(function(){function q(m,G,p,H){ea.call(this,m,G,p,H);var E=this.protectedMethod;this.loadAnalysisCenterGroupPubished=function(){E.remote("loadAnalysisCenterGroupPubished",{})};this.saveAnalysisCenterGroupPubishedOrder=function(g){g={arrCenterGroupId:JSON.stringify(g)};E.remote("saveAnalysisCenterGroupPubishedOrder",g)}}function u(){fa.call(this);var m,G;this.getRemoteUrl=function(p){p.tag=G;return m};this.setRemoteUrl=function(p){m=p};this.setTag=function(p){G=p}}function t(){var m,G=[],p,H=new ha,
E,g,F;this.getList=function(){return p};this.getCurrentSelectedNode=function(){return F};this.getJqUi=function(){if(!m){m=$("<div>");m.addClass("analysiscenter-menu-lists");p||(p=new ia,p.scrollSelectedToVisible(),p.setCustomItemPainter(K),p.addSelectedChangedListener(z),p.setUserObject(G),p.setItemModels(G));var d=p.getJqUi(),e=d.find(".sa-ctrl-common-border");e&&e.css("border","0px solid #dbdbdb");m.append(d)}return m};var z=function(d,e,k){if((F=k=k&&0<k.length?k[0]:e[0]?e[0]:g)&&k instanceof Q)E&&
E(k);else{var l=k.getIsOpenDir();k.setIsOpenDir(!l);C(k,!1);l=d.getUserObject();var r=m.find(".sa-ctrl-list-owner");r.empty();for(var w=$(document.createDocumentFragment()),M=K,L=0;L<l.length;L++){var J=$("<div>");J.addClass("sa-ctrl-list-item");J.addClass("sa-ctrl-list-item_enabled");J.addClass("sa-ctrl-list-item-defaultlayout");J.css("height","33px");J.css("line-height","33px");var D=l[L];J.data("model",D);M(J,D);w.append(J)}r.append(w)}l=(l=e[0])?l:g;(e=d.getJqUi().find(".analysiscenter-menu-lists-item-selected"))&&
e.removeClass("analysiscenter-menu-lists-item-selected");e=d.getItemUiByModel(k);e.addClass("sa-ctrl-list-item_selected_enabled");(r=e.find(".sa-ctrl-label-text"))&&r.addClass("analysiscenter-menu-lists-item-selected");l&&l instanceof Q&&(r=d.getItemUiByModel(l).find(".analysiscenter-menu-lists-item-icon"),l&&l.getSource()==S.DASHBOARD?v.background(r,"dashboard"):l.getSource()==S.EXTREPORT?v.background(r,"extreport"):v.background(r,"analysis"),l.getIsPreset()&&(r=d.getJqUi().find(".analysiscenter-menu-lists-item-preset-selected"))&&
r.removeClass("analysiscenter-menu-lists-item-preset-selected"));l&&l instanceof I&&(r=d.getItemUiByModel(l).find(".analysiscenter-menu-lists-dir-icon"),(d=l.getIsOpenDir())?v.background(r,"icon_dir_open"):v.background(r,"icon_dir_close"));k&&k instanceof I?(l=e.find(".analysiscenter-menu-lists-dir-icon"),(d=k.getIsOpenDir())?v.background(l,"icon_dir_open_on"):v.background(l,"icon_dir_close_on")):((l=e.find(".analysiscenter-menu-lists-item-icon"))&&(k.getSource()==S.DASHBOARD?v.background(l,"dashboard-on"):
k.getSource()==S.EXTREPORT?v.background(l,"extreport-on"):v.background(l,"analysis-on")),k.getIsPreset()&&(d=e.find(".analysiscenter-menu-lists-item-preset-tag"))&&d.addClass("analysiscenter-menu-lists-item-preset-selected"));e=m.find(".sa-ctrl-list-item");for(l=0;l<e.length;l++)if(d=e.eq(l),r=d.data("model"),w=k,r==w||r&&w&&r instanceof I&&w instanceof I&&r.getCenterId1()==w.getCenterId1()&&r.getCenterId2()==w.getCenterId2()&&r.getCenterId3()==w.getCenterId3()&&r.getCenterId4()==w.getCenterId4()){k=
m.find(".sa-ctrl-list-owner");e=k.prop("clientHeight");l=k.prop("scrollTop");r=l+e;w=d.prop("offsetTop");d=w+d.prop("offsetHeight");w<l?k.prop("scrollTop",w-10):d>r&&k.prop("scrollTop",d-e+10);break}},C=function(d,e){d.setIsHidden(e);e=d.getChildren();if(d.getChildren())for(d=0;d<e.length;d++)e[d]instanceof I?e[d].getParentNode().getIsOpenDir()&&!e[d].getParentNode().getIsHidden()?C(e[d],!e[d].getIsHidden()):C(e[d],!0):e[d]&&e[d]instanceof Q&&(e[d].getParentNode().getIsHidden()||!e[d].getParentNode().getIsOpenDir()?
e[d].setIsHidden(!0):e[d].setIsHidden(!e[d].getIsHidden()))},K=function(d,e){if(e&&e instanceof I){d.addClass("analysiscenter-menu-lists-dir");var k=$("<div>");k.text(e.getName());k.addClass("analysiscenter-menu-lists-dir-text");k.css("margin-left",30*(e.getSubNodeLevel()+1)+"px");d.attr("title",e.getName());var l=$("<div>");l.addClass("analysiscenter-menu-lists-dir-icon");l.css("margin-left",30*e.getSubNodeLevel()+"px");e.getIsOpenDir()?v.background(l,"icon_dir_open"):v.background(l,"icon_dir_close");
d.append(k);d.append(l)}else if(d.addClass("analysiscenter-menu-lists-dir"),k=$("<div>"),k.text(e.getName()),k.addClass("analysiscenter-menu-lists-dir-text"),k.css("margin-left",30*e.getSubNodeLevel()+25+"px"),d.attr("title",e.getName()),l=$("<span>"),l.addClass("analysiscenter-menu-lists-item-icon"),l.css("margin-left",30*e.getSubNodeLevel()+"px"),e.getSource()==S.DASHBOARD?v.background(l,"dashboard"):e.getSource()==S.EXTREPORT?v.background(l,"extreport"):v.background(l,"analysis"),d.append(k),d.append(l),
e.getIsPreset()){var r=$("<div>"),w=x.get("preset","\u9884\u7f6e"),M=H.measureWidth(w)+14;r.text(w);r.addClass("analysiscenter-menu-lists-item-preset-tag");r.css("margin-left",30*e.getSubNodeLevel()+"px");l.css("margin-left",30*e.getSubNodeLevel()+M+"px");k.css("margin-left",30*e.getSubNodeLevel()+M+24+"px");d.append(r)}e.getIsHidden()?d.hide():(d.show(),d.on("click",function(L){g=p.getSelecteds()[0];p.setSelecteds([])}))};this.setItemModels=function(d){G=d};this.setIsOpenFirstItem=function(d){};
this.setSubItemSelectedListener=function(d){E=d};this.setOuterMessageCurtain=function(d){}}function B(m){ja.call(this);var G=this,p=this.protectedMethod,H,E,g,F;(function(){p.setTitle(x.get("manualSort","\u624b\u52a8\u6392\u5e8f"));G.setSize(810,570);p.setSelectable(!0);m.setOuterMessageCurtain(p.getMessageCurtain());p.setContentPaneCreator(function(){g=m.getJqUi();F||(F=new Z,F.getJqUi().appendTo(g));var z=g.find(".sa-ctrl-common-border");z&&z.css("border","1px solid #dbdbdb");return g});p.setClosingChecker2(function(z){E&&
E(m);p.destroy();return!0},function(z){H&&H(m);p.destroy();return!0});p.setClosingAction(function(z){})})();this.getJqUi=function(){g||(g=m.getJqUi(),F||(F=new Z,F.getJqUi().appendTo(g)));return g};this.setConfirmCallBack=function(z){E=z};this.getOuterMessageCurtain=function(){return F};this.setClosedCallback=function(z){H=z}}function y(m,G){aa.AbstractTabPane.call(this);var p=this,H,E,g,F,z;this.setFunOpenNewTab=function(d){z=d};this.setFunCloseTabCallBack=function(d){F=d};this.getJqUi=function(){E||
(g=$("<iframe>"),g.on("load",function(){var d=g[0].contentWindow.com.kingdee.bos.qing.AnalysisSceneOuterApi;d&&(d.setClosingRequestListener(p.onClose),d.setFunOpenNewTab&&d.setFunOpenNewTab(z))}),g.attr("src",G),g.attr("name","QING_CONTEXT_TAB"),g.attr("allowFullscreen",!0),g.attr("allowtransparency",!0),g.addClass("analysiscenter-rightpane-iframe ."+m),E=g);return E};this.protectedAskCloseable=function(d){var e=g[0].contentWindow;if(e.com&&e.com.kingdee&&e.com.kingdee.bos&&e.com.kingdee.bos.qing)var k=
e.com.kingdee.bos.qing.AnalysisSceneOuterApi;k&&k.isDirtyToForbidClosing()?K(d):(d(!0),F&&F())};var C=!0,K=function(d){if(C){var e=com.kingdee.bos.qing.ui.component.MessageDialog,k=e.createFeedbackDialog();k.setMsgImageType(e.MSG_CONFIRM);k.setButtonText(e.RETURN_OK,x.get("sureExit","\u76f4\u63a5\u9000\u51fa"));k.setButtonText(e.RETURN_CANCEL,x.get("sureReturn","\u8fd4\u56de\u7f16\u8f91"));var l=H;l&&25<l.length&&(l=l.substring(0,25)+"...");k.setMessage(x.get("confirmExit","\u201c#1\u201d \u68c0\u6d4b\u5230\u60a8\u6709\u66f4\u6539\u5185\u5bb9\uff0c\u662f\u5426\u4e0d\u4fdd\u5b58\u76f4\u63a5\u9000\u51fa\uff1f\u82e5\u4e0d\u4fdd\u5b58\uff0c\u5c06\u4e22\u5931\u8fd9\u4e9b\u66f4\u6539\u3002").replace("#1",
l));k.showDialog();k.setClosingChecker(function(r){r==e.RETURN_OK?((r=g[0].contentWindow.com.kingdee.bos.qing.AnalysisSceneOuterApi)&&r.doBeforeClosing(),d(!0),F&&F()):d(!1);return!0});k.setClosedAction(function(r){C=!0});C=!1}};this.getId=function(){return m};this.setTitle=function(d){H=d};this.getTitle=function(){return H}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&
(com.kingdee.bos.qing={});"undefined"==typeof com.kingdee.bos.qing.analysiscenter&&(com.kingdee.bos.qing.analysiscenter={});var P=com.kingdee.bos.qing.analysiscenter;P.Facade=q;P.RemoteImpl=u;P.AnalysisCenter=function(){var m=this,G,p,H,E,g,F=!1,z,C,K,d,e,k,l,r,w,M,L,J,D,ka,N,O=[],U=[];this.getJqUi=function(a){H=a;ya();a.append(p);return p};var ya=function(){if(!p){p=$("<div>");p.addClass("analysiscenter-body");za();la();var a=new ma;a.setCallbackImmediately(function(){la();g&&g.resize()});a.setDelay(250);
a.observe();m.loadAnalysisCenterGroupPubished(V);a=com.kingdee.bos.qing.behavior.BehaviorManager;a.interestInBehaviorEntrance(a.ENTRANCE_ANALYSIS_CENTER)}},la=function(){document.body.style.height=document.documentElement.clientHeight+"px"};this.loadAnalysisCenterGroupPubished=function(a,b){var c=new q(m.getRemoteImpl(),function(f){g||na();O=Aa(f);a(O);K||(K=$("<div>"),K.addClass("analysiscenter-leftpane-tool-label"),g.getJqUi().append(K));d||(d=$("<div>"),d.addClass("analysiscenter-search-icon"),
d.attr("title",x.get("search","\u641c\u7d22")),v.background(d,"icon_search"),d.on("mouseover",function(n){v.background(d,"icon_search_on")}),d.on("mouseout",function(n){v.background(d,"icon_search")}),d.on("click",Ba),K.append(d));k||(k=$("<div>"),k.addClass("analysiscenter-refresh-icon"),v.background(k,"icon_refresh"),k.on("mouseover",function(n){v.background(k,"icon_refresh_on")}),k.on("mouseout",function(n){v.background(k,"icon_refresh")}),k.attr("title",x.get("refresh","\u5237\u65b0")),k.on("click",
Ca),K.append(k));L||(L=$("<div>"),L.addClass("analysiscenter-order-icon"),v.background(L,"icon_order"),L.on("mouseover",function(n){v.background(L,"icon_order_on")}),L.on("mouseout",function(n){v.background(L,"icon_order")}),L.on("click",Da),L.attr("title",x.get("manualSort","\u624b\u5de5\u6392\u5e8f")),K.append(L));if(!e){e=$("<div>");e.addClass("analysiscenter-collapse");var h=$("<div>");h.addClass("analysiscenter-collapse-icon");v.background(h,"icon_left");h.on("mouseover",function(n){v.background(h,
"icon_left_on")});h.on("mouseout",function(n){v.background(h,"icon_left")});h.attr("title",x.get("retract","\u6536\u8d77"));e.append(h);e.on("click",Ea);K.append(e)}(b&&U&&0<U.length||p.find(".analysiscenter-leftpane-search-nothing"))&&oa()},function(f,h){return!1});c.setShowBlocking(!1);c.loadAnalysisCenterGroupPubished()};var Ca=function(){m.loadAnalysisCenterGroupPubished(V,!0)},Da=function(){var a={width:"40px",position:"absolute","margin-top":"12px","text-align":"center"},b=$("<div>");b.text(x.get("moveUp",
"\u4e0a\u79fb"));b.css(a);b.addClass("analysiscenter-order-moveup");b.on("click",Fa);var c=$("<div>");c.text(x.get("moveDown","\u4e0b\u79fb"));c.on("click",Ga);c.css(a);c.addClass("analysiscenter-order-movedown");J=new t;J.setItemModels(O);J.setSubItemSelectedListener(null);N=new B(J);N.setClosedCallback(function(f){f.setSubItemSelectedListener(ba);m.loadAnalysisCenterGroupPubished(V,!0)});N.setConfirmCallBack(function(f){f.setSubItemSelectedListener(ba);Ha();V(O,!0)});N.showDialog();a=J.getJqUi();
a.css("height","430px");a.css("left","20px");a.css("right","20px");a.css("top","40px");a.css("position","absolute");a.before(b);a.before(c);(D=J.getList())&&D.getUserObject()&&D.setSelecteds([D.getUserObject()[0]])},Fa=function(a){var b=J.getCurrentSelectedNode();a=D.getUserObject();if(b){var c=R(b,a);if(0==c)N.getOuterMessageCurtain().showPrompt(x.get("currentFirstDirectoryCannotMoveUp","\u540c\u5c42\u7ea7\u7b2c\u4e00\u4e2a\u76ee\u5f55\u6216\u53d1\u5e03\u8bb0\u5f55\u4e0d\u652f\u6301\u4e0a\u79fb\u3002"),
2E3);else if(b.getSubNodeLevel()==a[c-1].getSubNodeLevel()&&b instanceof Q&&a[c-1]instanceof Q){var f=b.getParentNode().getChildren(),h=R(b,f);f.splice(h-1,2,b,f[h-1]);Y(b.getParentNode());D.getItemUiByModel(b).insertBefore(D.getItemUiByModel(b).prev());a.splice(c-1,2,b,a[c-1]);D.setUserObject(a)}else{f=[];if(b.getParentNode())f=b.getParentNode().getChildren();else for(var n in a)0==a[n].getSubNodeLevel()&&f.push(a[n]);h=R(b,f);if(0==h)N.getOuterMessageCurtain().showPrompt(x.get("currentFirstDirectoryCannotMoveUp",
"\u540c\u5c42\u7ea7\u7b2c\u4e00\u4e2a\u76ee\u5f55\u6216\u53d1\u5e03\u8bb0\u5f55\u4e0d\u652f\u6301\u4e0a\u79fb\u3002"),2E3);else if(b instanceof Q&&f[h-1]instanceof I)N.getOuterMessageCurtain().showPrompt(x.get("menuCannotMoveUpToDirectory","\u540c\u5c42\u7ea7\u76ee\u5f55\u53d1\u5e03\u8bb0\u5f55\u4e0d\u652f\u6301\u79fb\u52a8\u5230\u76ee\u5f55\u4e0a\u65b9\u3002"),2E3);else if(b.getSubNodeLevel()==f[h-1].getSubNodeLevel()){c=[];c=X(c,b);b=[];b=X(b,f[h-1]);for(n in c){0==n&&c[0]instanceof I&&c[0].getParentNode()&&
(f=c[n].getParentNode().getChildren(),h=R(c[n],f),f.splice(h-1,2,c[n],f[h-1]),Y(c[n].getParentNode()));h=R(c[n],a);for(var A in b)D.getItemUiByModel(c[n]).insertBefore(D.getItemUiByModel(c[n]).prev()),a.splice(h-1-A,2,c[n],a[h-1-A])}D.setUserObject(a)}else N.getOuterMessageCurtain().showPrompt(x.get("cannotBeMovedToAnnotherLevel","\u975e\u540c\u5c42\u7ea7\u76ee\u5f55\u6216\u53d1\u5e03\u8bb0\u5f55\u4e0d\u652f\u6301\u79fb\u52a8\u3002"),2E3)}}else N.getOuterMessageCurtain().showPrompt(x.get("pleaseSelectedDirectory",
"\u8bf7\u5148\u9009\u4e2d\u5177\u4f53\u7684\u76ee\u5f55\u3002"),2E3)},Ga=function(a){var b=J.getCurrentSelectedNode();a=D.getUserObject();if(b){var c=R(b,a);if(c==a.length-1)N.getOuterMessageCurtain().showPrompt(x.get("currentLastDirectoryCannotMoveDown","\u540c\u5c42\u7ea7\u6700\u540e\u4e00\u4e2a\u76ee\u5f55\u6216\u53d1\u5e03\u8bb0\u5f55\u4e0d\u652f\u6301\u4e0b\u79fb\u3002"),2E3);else if(b.getSubNodeLevel()==a[c+1].getSubNodeLevel()&&b instanceof Q&&a[c+1]instanceof Q){var f=b.getParentNode().getChildren(),
h=R(b,f);f.splice(h,2,f[h+1],b);Y(b.getParentNode());D.getItemUiByModel(b).insertAfter(D.getItemUiByModel(b).next());a.splice(c,2,a[c+1],b);D.setUserObject(a)}else{c=[];if(b.getParentNode())c=b.getParentNode().getChildren();else for(var n in a)0==a[n].getSubNodeLevel()&&c.push(a[n]);h=R(b,c);if(h==c.length-1)N.getOuterMessageCurtain().showPrompt(x.get("currentLastDirectoryCannotMoveDown","\u540c\u5c42\u7ea7\u6700\u540e\u4e00\u4e2a\u76ee\u5f55\u6216\u53d1\u5e03\u8bb0\u5f55\u4e0d\u652f\u6301\u4e0b\u79fb\u3002"),
2E3);else if(b instanceof I&&c[h+1]instanceof Q)N.getOuterMessageCurtain().showPrompt(x.get("directoryCannotMoveDownToMenu","\u540c\u5c42\u7ea7\u76ee\u5f55\u4e0d\u652f\u6301\u79fb\u52a8\u5230\u53d1\u5e03\u8bb0\u5f55\u4e0b\u65b9\u3002"),2E3);else if(b.getSubNodeLevel()==c[h+1].getSubNodeLevel()){var A=[];A=X(A,b);b=[];b=X(b,c[h+1]);b=b.length+A.length-1;for(n in A)for(0==n&&A[0]instanceof I&&A[0].getParentNode()&&(f=A[n].getParentNode().getChildren(),h=R(A[n],f),c.splice(h,2,c[h+1],A[n]),Y(A[n].getParentNode())),
h=R(A[n],a),f=0;f<b;f++)D.getItemUiByModel(A[n]).insertAfter(D.getItemUiByModel(A[n]).next()),a.splice(h+f,2,a[h+1+f],A[n]);D.setUserObject(a)}else N.getOuterMessageCurtain().showPrompt(x.get("cannotBeMovedToAnnotherLevel","\u975e\u540c\u5c42\u7ea7\u76ee\u5f55\u6216\u53d1\u5e03\u8bb0\u5f55\u4e0d\u652f\u6301\u79fb\u52a8\u3002"),2E3)}}else N.getOuterMessageCurtain().showPrompt(x.get("pleaseSelectedDirectory","\u8bf7\u5148\u9009\u4e2d\u5177\u4f53\u7684\u76ee\u5f55\u3002"),2E3)},X=function(a,b){a.push(b);
if((b=b.getChildren())&&0<b.length)for(var c=0;c<b.length;c++)b[c]instanceof I&&b[c].getChildren()&&0<b[c].getChildren().length?X(a,b[c]):a.push(b[c]);return a},Y=function(a){var b=[];pa(b,a);for(a=1;a<b.length;a++){var c=b[a].getChildren();if(c&&0<c.length){var f=R(b[a-1],c);-1<f&&c.splice(f,1,b[a-1])}}},pa=function(a,b){-1==a.indexOf(b)&&a.push(b);b.getParentNode()&&pa(a,b.getParentNode());return a},R=function(a,b){if(a){var c=b.indexOf(a);if(0>c)for(var f in b)if(b[f]instanceof I){if(b[f].getRelationId()==
a.getRelationId()&&b[f].getId()==a.getId()){c=f;break}}else if(b[f].getId()==a.getId()&&b[f].getParentId()==a.getParentId()){c=f;break}return c}ka.showPrompt(x.get("selectedOneDirectory","\u8bf7\u5148\u9009\u4e2d\u5177\u4f53\u76ee\u5f55\u3002"),2E3)},Ha=function(){var a=[];for(c in O){var b=O[c].getId();O[c]instanceof I&&(b=Ia(O[c]));a.push(b)}var c=new q(m.getRemoteImpl(),function(f){},function(f,h){return!1});c.setShowBlocking(!1);c.saveAnalysisCenterGroupPubishedOrder(a)},Ia=function(a){var b=
[];qa(b,a);a="";for(var c=b.length-1;0<=c;c--)c<b.length-1&&(a+="/"),a+=b[c].getId();return a},V=function(a,b){0==a.length?(g.getJqUi().remove(),na(),ra(!0),g.setSecondChild(T.createChildWrapper(w))):(a=Ja(a),z&&z.getText()&&b&&p.find(".analysiscenter-leftpane-search-nothing")&&(z.clear(),p.find(".analysiscenter-leftpane-search-nothing").remove()),w||(ra(!1),g.setSecondChild(T.createChildWrapper(w,function(){var c=-185,f=g.getJqUi().height(),h=w.children(".analysiscenter-message");0<h.length&&f<=
h.height()&&(c=-115);h.css("margin-top",c+"px")}))),g.setFirstChild(T.createChildWrapper(a,function(){if(e)if(e.css({left:g.getNonemptyFirstWide()+"px"}),g.getNonemptyFirstWide()){var c=e.find(".analysiscenter-collapse-icon");c&&c.removeClass("analysiscenter-collapse-icon-right")}else(c=e.find(".analysiscenter-collapse-icon"))&&c.addClass("analysiscenter-collapse-icon-right");C&&C.css({width:g.getNonemptyFirstWide()+"px"});K&&K.css({width:g.getNonemptyFirstWide()+"px"});p&&g&&(c=p.find(".analysiscenter-leftpane-search-nothing"))&&
c.css({width:g.getNonemptyFirstWide()+"px"});r&&r.resize()})))},na=function(){g=new T;g.setHorizontalSplit(!0);g.setEnabled(!0);g.setSplitLineWide(8);g.setResizeMode(T.RESIZE_MODE_FIRST_FIXED);g.setFirstSize(200,200,640);g.setSecondSize(H.width()-200-13,0,-1);g.getJqUi().addClass("analysiscenter-pane");p.append(g.getJqUi())},za=function(){$(window).resize(function(){g.getNonemptyFirstWide()?(g.setFirstSize(200,200,640),g.setSecondSize(H.width()-200-13,0,-1)):(g.setFirstSize(0,200,640),g.setSecondSize(H.width()-
13,0,-1))})},Ea=function(a){var b=$(a.currentTarget);a&&a.stopPropagation();a=b.find(".analysiscenter-collapse-icon");g.getNonemptyFirstWide()?(l=g.getNonemptyFirstWide(),g.setFirstSize(0,200,640),g.setSecondSize(H.width()-13,0,-1),a.addClass("analysiscenter-collapse-icon-right"),a.attr("title",x.get("spread","\u5c55\u5f00"))):(b=13<l?l:200,g.setFirstSize(b,200,640),g.setSecondSize(H.width()-b-13,0,-1),a.removeClass("analysiscenter-collapse-icon-right"),a.attr("title",x.get("retract","\u6536\u8d77")))},
Ja=function(a){var b=$("<div>");E=new t;E.setItemModels(a);E.setIsOpenFirstItem(!0);E.setSubItemSelectedListener(ba);a=E.getJqUi();b.append(a);b.addClass("analysiscenter-leftpane");C&&"block"==C.css("display")&&b.css("margin-top","60px");return b},sa=function(a,b,c){b=new y(c,b);b.setFunOpenNewTab(sa);b.setTitle(a);b.setFunCloseTabCallBack(ta);r.addTab(b,!0);F=!0},ba=function(a){var b=a.getId();w?M&&M.hide():(w=$("<div>"),w.addClass("analysiscenter-rightpane"),g.setSecondChild(T.createChildWrapper(w)));
r||(r=new aa,w.append(r.getJqUi()));var c=com.kingdee.bos.qing.SkinUtil.getUrlParamValue(),f=m.protectedGetPublishEntranceUrl(b);f=W.appendParamToUrl(f,"publishTargetType",ua.CENTER);f=W.appendParamToUrl(f,"skin",c);(c=a.getSource())&&"extreport"==c&&(f=W.appendParamToUrl(f,"appID","qing_rpt"),f=W.appendParamToUrl(f,"isPreset",a.getIsPreset()));c=r.getDynamicTabPanes();var h=c.length;if(10<=h){for(var n=!1,A=0;A<h;A++)if(b==c[A].getId()){n=!0;break}if(!n){a=x.get("maxTabCountError","\u9875\u7b7e\u6700\u591a\u53ef\u540c\u65f6\u6253\u5f0010\u4e2a\uff0c\u8bf7\u5173\u95ed\u90e8\u5206\u9875\u7b7e\u540e\u518d\u8bd5");
b=new ca;b.setBounds(760,200,320,200);b.setOptionType(ca.OPTION_OK);b.setMessage(a);b.showDialog();return}}b=new y(b,f);b.setTitle(a.getName());b.setFunCloseTabCallBack(ta);b.setFunOpenNewTab(sa);r.addTab(b,!0);F=!0},ta=function(){var a=r.getDynamicTabPanes();a&&0!=a.length||M&&M.show()},Aa=function(a){for(var b=[],c=0;c<a.length;c++){var f=new I;f.fromJsonObject(a[c]);b.push(f)}a=[];for(c=0;c<b.length;c++)va(a,b[c]);return a},va=function(a,b){-1==a.indexOf(b)&&a.push(b);if(b=b.getChildren())for(var c=
0;c<b.length;c++)1<b[c].getSubNodeLevel()&&b[c].setIsHidden(!0),b[c]instanceof I?(0<b[c].getSubNodeLevel()&&b[c].setIsOpenDir(!1),va(a,b[c])):-1==a.indexOf(b[c])&&a.push(b[c])},ra=function(a){if(!w){w=$("<div>");w.addClass("analysiscenter-rightpane");if(!M){M=$("<div>");M.addClass("analysiscenter-message");var b=$("<div>");if(a){var c="icon_empty_background";var f="analysiscenter-empty-background";var h=x.get("emptyTips","\u6682\u65e0\u53d1\u5e03\u8bb0\u5f55")}else F||(c="icon_open_tips_background",
f="analysiscenter-message-background",h=x.get("openTips","\u8bf7\u70b9\u51fb\u5de6\u4fa7\u83dc\u5355\u8fdb\u884c\u67e5\u770b"));b.addClass(f);v.background(b,c);a=$("<div>");a.addClass("analysiscenter-message-text");a.text(h);a.css("top","225px");M.append(b);M.append(a)}w.append(M)}},Ba=function(){if(C)"none"==C.css("display")?(C.css("display","block"),a=p.find(".analysiscenter-leftpane"),a.css("margin-top","60px")):(C.css("display","none"),a=p.find(".analysiscenter-leftpane"),a.css("margin-top","35px"));
else{z=new wa;z.addSearchListener(oa);z.setPlaceholder(x.get("enterSearchPublishName","\u641c\u7d22\u53d1\u5e03\u540d\u79f0"));C=z.getJqUi();C.addClass("analysiscenter-leftpane-searchbox");g&&C.css({width:g.getNonemptyFirstWide()+"px"});C.insertAfter(K);var a=p.find(".analysiscenter-leftpane");a.css("margin-top","60px")}},oa=function(){p.find(".analysiscenter-leftpane-search-nothing").remove();U=[];var a;z&&(a=z.getText());if(a){var b=O,c=new I,f=[],h;for(h in b)b[h].getParentId()||b[h].getParentNode()||
f.push(b[h]);c.setChildren(f);a=xa([],c,a.toUpperCase());if(0==a.length){p.find(".analysiscenter-menu-lists").remove();var n=new da(x.get("nothingSearched","\u6ca1\u6709\u7b26\u5408\u641c\u7d22\u6761\u4ef6\u7684\u7ed3\u679c"));n.setAlign(da.ALIGN_CENTER);n=n.getJqUi();n.addClass("analysiscenter-leftpane-search-nothing");n.insertAfter(C)}else{b=[];for(c=a.length-1;0<=c;c--)-1==b.indexOf(a[c])&&b.push(a[c]);for(n in O)O[n].setIsHidden(!1),O[n]instanceof I&&O[n].setIsOpenDir(!0);U=b;V(b)}}else U=O,V(U)},
xa=function(a,b,c){if(b=b.getChildren())for(var f=0;f<b.length;f++){var h=b[f];if(h instanceof Q)-1<h.getName().toUpperCase().indexOf(c)?(h.setIsSearch(!0),a.push(h)):h.setIsSearch(!1);else{xa(a,h,c);a:{var n=void 0;var A=h.getChildren();for(n in A)if(A[n].getIsSearch()){n=!0;break a}n=!1}n&&-1==a.indexOf(h)?(h.setIsSearch(!0),a.push(h)):h.setIsSearch(!1)}}return a},qa=function(a,b){-1==a.indexOf(b)&&a.push(b);b.getParentNode()&&qa(a,b.getParentNode());return a};this.setOuterMessageCurtain=function(a){ka=
a};this.getRemoteImpl=function(){if(null==G){G=new u;G.setRemoteUrl(m.protectedGetRemoleUrl());var a=m.getUrlParam("tag");G.setTag(a)}return G};this.getUrlParam=function(a){return W.decodeParamFromUrl(window.location.search,a)};this.protectedGetRemoleUrl=function(){throw Error("overwrite me.");};this.protectedGetPublishEntranceUrl=function(){throw Error("overwrite me.");}};var v,x,fa,ea,ma,W,ha,ia,T,ca,wa,da,ja,Z,I,Q,aa,S,ua;(function(){var m=com.kingdee.bos.qing.framework.common;fa=m.AbstractRemoteCall;
ea=m.AbstractFacade;ma=m.WindowResizeObserver;x=m.MultilanguageManager.createPackageAccessor(P);m=com.kingdee.bos.qing.ui.component;ia=m.List;T=m.SplitPane;ca=m.MessageDialog;wa=m.SearchBox;da=m.Label;ja=m.AbstractModalDialog;Z=m.MessageCurtain;aa=m.DynamicTabContainer;m=com.kingdee.bos.qing.common;W=m.Util;ha=m.TextMeasurer;m=com.kingdee.bos.qing.analysiscenter.common;v=m.MyIcons;m=com.kingdee.bos.qing.publish.model;S=m.PublishSourceType;ua=m.PublishTargetType;I=m.FolderNode;Q=m.LeafNode})()})();
//qingVersionTag: 20250324