var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var w=0;return function(){return w<f.length?{done:!1,value:f[w++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,w,x){if(f==Array.prototype||f==Object.prototype)return f;f[w]=x.value;return f};$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var w=0;w<f.length;++w){var x=f[w];if(x&&x.Math==Math)return x}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,w){var x=$jscomp.propertyToPolyfillSymbol[w];if(null==x)return f[w];x=f[x];return void 0!==x?x:f[w]};
$jscomp.polyfill=function(f,w,x,y){w&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,w,x,y):$jscomp.polyfillUnisolated(f,w,x,y))};$jscomp.polyfillUnisolated=function(f,w,x,y){x=$jscomp.global;f=f.split(".");for(y=0;y<f.length-1;y++){var C=f[y];if(!(C in x))return;x=x[C]}f=f[f.length-1];y=x[f];w=w(y);w!=y&&null!=w&&$jscomp.defineProperty(x,f,{configurable:!0,writable:!0,value:w})};
$jscomp.polyfillIsolated=function(f,w,x,y){var C=f.split(".");f=1===C.length;y=C[0];y=!f&&y in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var O=0;O<C.length-1;O++){var R=C[O];if(!(R in y))return;y=y[R]}C=C[C.length-1];x=$jscomp.IS_SYMBOL_NATIVE&&"es6"===x?y[C]:null;w=w(x);null!=w&&(f?$jscomp.defineProperty($jscomp.polyfills,C,{configurable:!0,writable:!0,value:w}):w!==x&&(void 0===$jscomp.propertyToPolyfillSymbol[C]&&(x=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[C]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(C):$jscomp.POLYFILL_PREFIX+x+"$"+C),$jscomp.defineProperty(y,$jscomp.propertyToPolyfillSymbol[C],{configurable:!0,writable:!0,value:w})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(f){if(f)return f;var w=function(O,R){this.$jscomp$symbol$id_=O;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:R})};w.prototype.toString=function(){return this.$jscomp$symbol$id_};var x="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",y=0,C=function(O){if(this instanceof C)throw new TypeError("Symbol is not a constructor");return new w(x+(O||"")+"_"+y++,O)};return C},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(f){if(f)return f;f=Symbol("Symbol.iterator");for(var w="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),x=0;x<w.length;x++){var y=$jscomp.global[w[x]];"function"===typeof y&&"function"!=typeof y.prototype[f]&&$jscomp.defineProperty(y.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return f},"es6",
"es3");$jscomp.iteratorPrototype=function(f){f={next:f};f[Symbol.iterator]=function(){return this};return f};$jscomp.iteratorFromArray=function(f,w){f instanceof String&&(f+="");var x=0,y=!1,C={next:function(){if(!y&&x<f.length){var O=x++;return{value:w(O,f[O]),done:!1}}y=!0;return{done:!0,value:void 0}}};C[Symbol.iterator]=function(){return C};return C};$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(w){return w})}},"es6","es3");
(function(){function f(){var d=this,g,p,r,u,t,A,z,H,D,L,F,M,P,J;this.getSourceId=function(){return g};this.setSourceId=function(k){g=k};this.getSourceName=function(){return p&&p==f.HAS_DELETED?v.get("hasDeleted","\u6765\u6e90\u5df2\u88ab\u5220\u9664"):p};this.setSourceName=function(k){p=k};this.getSourcePathName=function(){return r};this.setSourcePathName=function(k){r=k};this.getSourcePathId=function(){return u};this.setSourcePathId=function(k){u=k};this.getSourceType=function(){return t};this.setSourceType=
function(k){t=k};this.getSourceTypeName=function(){return p&&p==f.HAS_DELETED?"":t==f.SOURCETYPE_SUBJECT?v.get("subject","\u4e1a\u52a1\u4e3b\u9898"):t==f.SOURCETYPE_DSB?v.get("dsb","\u4eea\u8868\u677f"):t==f.SOURCETYPE_BILL?v.get("bill","\u5355\u636e"):t==f.SOURCETYPE_PUBLISH?v.get("publish","\u53d1\u5e03\u8bb0\u5f55"):t==f.SOURCETYPE_REPORT?v.get("report","\u62a5\u8868\u6a21\u677f"):t==f.SOURCETYPE_DATASET?v.get("dataSet","\u6570\u636e\u96c6"):t==f.SOURCETYPE_COLLABORATION?v.get("collaborationSpace",
"\u534f\u4f5c\u7a7a\u95f4"):""};this.getPubTypeName=function(){return!J&&0!=J||F!=f.PUBTYPE_PUBLISH?F==f.PUBTYPE_PUSH?v.get("pushConfig","\u63a8\u9001\u914d\u7f6e"):"":v.get("publish","\u53d1\u5e03\u8bb0\u5f55")};this.getSourceCreatorId=function(){return A};this.setSourceCreatorId=function(k){A=k};this.getSourceCreatorName=function(){return z};this.setSourceCreatorName=function(k){z=k};this.getPubId=function(){return H};this.setPubId=function(k){H=k};this.getPubSourceType=function(){return D};this.setPubSourceType=
function(k){D=k};this.getPubName=function(){return L};this.setPubName=function(k){L=k};this.getPubType=function(){return F};this.setPubType=function(k){F=k};this.getPubPath=function(){return M};this.setPubPath=function(k){M=k};this.getPubPathName=function(){return P};this.setPubPathName=function(k){P=k};this.getPublishToType=function(){return J};this.setPublishToType=function(k){J=k};this.fromJsonObject=function(k){k&&(d.setSourceId(k.sourceId),d.setSourceName(k.sourceName),d.setSourcePathName(k.sourcePathName),
d.setSourcePathId(k.sourcePathId),d.setSourceType(k.sourceType),d.setSourceCreatorId(k.sourceCreatorId),d.setSourceCreatorName(k.sourceCreatorName),d.setPubId(k.pubId),d.setPubSourceType(k.pubSourceType),d.setPubName(k.pubName),d.setPubType(k.pubType),d.setPubPath(k.pubPath),d.setPubPathName(k.pubPathName),d.setPublishToType(k.publishToType))};this.toJsonObject=function(){var k={};k.sourceId=g;k.sourceName=p;k.sourcePathName=r;k.sourcePathId=u;k.sourceType=t;k.sourceCreatorId=A;k.sourceCreatorName=
z;k.pubId=H;k.pubSourceType=D;k.pubName=L;k.pubType=F;k.pubPath=M;k.pubPathName=P;k.publishToType=J;return k}}function w(){var d=this,g,p,r,u,t,A,z,H,D,L,F,M,P,J,k,V,Z,aa,ba,ca,da;this.getSourceId=function(){return g};this.setSourceId=function(l){g=l};this.getSourceOldName=function(){return p};this.setSourceOldName=function(l){p=l};this.getSourceNewName=function(){return r};this.setSourceNewName=function(l){r=l};this.getSourceType=function(){return u};this.setSourceType=function(l){u=l};this.getSourcePathName=
function(){return t};this.setSourcePathName=function(l){t=l};this.getSourcePathId=function(){return A};this.setSourcePathId=function(l){A=l};this.getPubSourceType=function(){return z};this.setPubSourceType=function(l){z=l};this.getPubId=function(){return H};this.setPubId=function(l){H=l};this.getPubOldName=function(){return D};this.setPubOldName=function(l){D=l};this.getPubNewName=function(){return L};this.setPubNewName=function(l){L=l};this.getPubType=function(){return F};this.setPubType=function(l){F=
l};this.getPubPath=function(){return M};this.setPubPath=function(l){M=l};this.getPubPathName=function(){return P};this.setPubPathName=function(l){P=l};this.getPublishToType=function(){return J};this.setPublishToType=function(l){J=l};this.getToUserId=function(){return k};this.setToUserId=function(l){k=l};this.getToUserName=function(){return V};this.setToUserName=function(l){V=l};this.getFromUserId=function(){return Z};this.setFromUserId=function(l){Z=l};this.getFromUserName=function(){return aa};this.setFromUserName=
function(l){aa=l};this.getCreatorId=function(){return ba};this.setCreatorId=function(l){ba=l};this.getCreatorName=function(){return ca};this.setCreatorName=function(l){ca=l};this.getCreateTime=function(){return da};this.setCreateTime=function(l){da=l};this.fromJsonObject=function(l){l&&(d.setSourceId(l.sourceId),d.setSourceOldName(l.sourceOldName),d.setSourceNewName(l.sourceNewName),d.setSourceType(l.sourceType),d.setSourcePathName(l.sourcePathName),d.setSourcePathId(l.sourcePathId),d.setPubSourceType(l.pubSourceType),
d.setPubId(l.pubId),d.setPubOldName(l.pubOldName),d.setPubNewName(l.pubNewName),d.setPubType(l.pubType),d.setPubPath(l.pubPath),d.setPubPathName(l.pubPathName),d.setPublishToType(l.publishToType),d.setToUserId(l.toUserId),d.setToUserName(l.toUserName),d.setFromUserId(l.fromUserId),d.setFromUserName(l.fromUserName),d.setCreatorId(l.creatorId),d.setCreatorName(l.creatorName),d.setCreateTime(l.createTime))}}function x(){var d=this,g,p;this.getJqUi=function(){throw Error("Override me.");};this.setUser=
function(r){g=r};this.getUser=function(){return g};this.setFunSelectedChangeListener=function(r){p=r};this.executeFunSelectedChangeListener=function(){p&&p(g)};this.show=function(){d.getJqUi().removeClass("management-handover-search-user-hide")};this.hide=function(){d.getJqUi().addClass("management-handover-search-user-hide")}}function y(){x.call(this);var d=this,g,p,r;this.getJqUi=function(){if(!g){g=$("<div>");p=new pa;p.setText(v.get("chooseUser2","\u8bf7\u9009\u62e9\u4e00\u4e2a\u7528\u6237"));
p.setReadonly("readonly");var u=p.getJqUi();u.on("click",d.showUserChooseForm);var t=$("<div>");G.Icons.background(t,"f7");t.css("z-index","1");t.css("cursor","pointer");t.on("click",d.showUserChooseForm);Q.layoutCtrl(u,0,0,180,23);Q.layoutCtrl(t,160,0,16,16);t.appendTo(g);u.appendTo(g)}return g};this.setShowDisabledFilter=function(u){r=u};this.showUserChooseForm=function(){var u=Ba;u.setCallBack(function(t){if(t=com.kingdee.bos.qing.handover.common.UserModelTransformer.getUserModel(t)){d.setUser(t);
if(p){t=p;var A=t.setText,z=v.get("chooseUser","\u8bf7\u9009\u62e9\u4e00\u4e2a\u7528\u6237");d.getUser()&&(z=d.getUser().getUserName());A.call(t,z)}d.executeFunSelectedChangeListener()}});u.openUserForm([],!0,r)}}function C(){x.call(this);var d=this,g,p,r;this.getJqUi=function(){g||u();return g};var u=function(){g=$("<div>");p=new pa;p.setPlaceholder(v.get("inputUserId","\u8bf7\u8f93\u5165\u7528\u6237id"));var t=p.getJqUi();r=new W;r.setText(v.get("searchUserId","\u67e5\u8be2"));r.addActionListener(function(){if(p&&
!p.getText())d.setUser(null);else if(p.getText()){var z=new qa;z.setUserName(p.getText());z.setUserId(p.getText());d.setUser(z)}d.executeFunSelectedChangeListener()});var A=r.getJqUi();A.css("margin-top","0px");Q.layoutCtrl(t,0,0,180,23);Q.layoutCtrl(A,180,-5,16,null);t.appendTo(g);A.appendTo(g)}}function O(d,g){Ca.call(this);var p=this,r=this.protectedMethod;(function(){r.setTitle(v.get("handOverRecord","\u79fb\u4ea4\u8bb0\u5f55"));p.setSize(640,480);r.setSelectable(!0);r.setContentPaneCreator(function(){if(d&&
0<d.length){var u=$("<ul>");u.addClass("management-handover-record-progress-ul");for(var t=0;t<d.length;t++){var A=new w;A.fromJsonObject(d[t]);var z=$("<li>");z.addClass("management-handover-record-progress-li");var H=$("<div>");H.addClass("management-handover-record-progress-li-content");var D=$("<p>");D.addClass("management-handover-record-progress-li-content-time");var L=new Da;L.setFormatString("yyyy-MM-dd HH:mm:ss");D.text(L.format(A.getCreateTime()));D.appendTo(H);D=$("<p>");D.addClass("management-handover-record-progress-li-content-text");
A=g.replace("#1",A.getCreatorName()).replace("#2",A.getFromUserName()).replace("#3",A.getToUserName());D.html(A);D.appendTo(H);H.appendTo(z);z.appendTo(u)}}else u=$("<div>"),u.addClass("management-handover-tips"),t=$("<div>"),t.addClass("management-handover-tips-background"),t.addClass("management-handover-tips-background-no-data"),t.css({width:"220px",height:"240px"}),G.Icons.background(t,"nodata"),z=$("<div>"),z.addClass("management-handover-tips-text"),z.css({top:"300px"}),z.text(v.get("noHandOverRecord",
"\u6682\u65e0\u79fb\u4ea4\u8bb0\u5f55")),u.append(t),u.append(z);return u});r.setFooterClosingOnly(!0);r.setClosingChecker2(null,function(u){r.destroy();return!0});r.setClosingAction(function(u){})})()}function R(d,g,p,r){Ea.call(this,d,g,p,r);var u=this.protectedMethod;this.queryDataByUserId=function(t){u.remote("queryDataByUserId",{userId:t})};this.handOver=function(t,A,z,H,D){u.remote("handOver",{handOvers:JSON.stringify(t),toUserId:A,publishedRuntimeUrl:z,paramPathPrefix:H,publishAppTypeMap:JSON.stringify(D)})};
this.queryHandOverRecords=function(t){u.remote("queryHandOverRecords",{handOver:JSON.stringify(t)})}}function Fa(){Ga.call(this);var d;this.getRemoteUrl=function(){return d};this.setRemoteUrl=function(g){d=g}}function qa(){var d,g;this.getUserName=function(){return d};this.setUserName=function(p){d=p};this.getUserId=function(){return g};this.setUserId=function(p){g=p}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos=
{});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});"undefined"==typeof com.kingdee.bos.qing.handover&&(com.kingdee.bos.qing.handover={});"undefined"==typeof com.kingdee.bos.qing.handover.common&&(com.kingdee.bos.qing.handover.common={});var G=com.kingdee.bos.qing.handover.common;G.AbstractHandOverPanel=function(){function d(e){KTDefaultCellRender.call(this,e);var b=this,m=this.paintCellUI;this.paintCellUI=function(c,a){var q=b.getCurrentRowIdx(),n=b.getCurrentRow(),B=b.getCurrentColIdx();
n=n.getUserObject();if(q<S.getHeadRowCount())B==V&&1==q?(T=new ra,T.setText(""),T.setChecked(!1),T.addCheckedListener(function(K,E){if(E)if(K.isChecked())for(E=0;E<I.length;E++)(K=I[E])&&K.setChecked(!0);else for(E=0;E<I.length;E++)(K=I[E])&&K.setChecked(!1)}),n=T.getJqUi(),a={position:"absolute",top:0,height:23,left:10,width:"100%"},n.css(a),c=$(c),c.append(n)):m(c,a);else if(B==V){if(n=I[q-S.getHeadRowCount()])n=n.getJqUi(),n.addClass("management-handover-data-table-cell-checkbox"),a={position:"absolute",
top:0,height:23,left:10,width:"100%"},n.css(a),c=$(c),c.addClass("management-handover-data-table-cell-btb"),c.addClass("management-handover-data-table-cell-merge"),c.append(n)}else B==Z?(c=$(c),c.addClass("management-handover-data-table-cell-btb"),c.addClass("management-handover-data-table-cell-merge"),a=$("<div>"),a.addClass("management-handover-data-table-cell"),(n=n.getSourceName())&&n==f.HAS_DELETED&&(n=v.get("hasDeleted","\u6765\u6e90\u5df2\u88ab\u5220\u9664")),h(a,J,n),a.attr("title",n),c.append(a)):
B==aa?(c=$(c),c.addClass("management-handover-data-table-cell-btb"),c.addClass("management-handover-data-table-cell-merge"),a=$("<div>"),a.addClass("management-handover-data-table-cell"),a.text(n.getSourceTypeName()),a.attr("title",n.getSourceTypeName()),c.append(a)):B==ba?(c=$(c),c.addClass("management-handover-data-table-cell-btb"),c.addClass("management-handover-data-table-cell-merge"),a=$("<div>"),a.addClass("management-handover-data-table-cell"),n=n.getSourcePathName(),h(a,J,n),a.attr("title",
n),c.append(a)):B==ca?(c=$(c),c.addClass("management-handover-data-table-cell-btb"),c.addClass("management-handover-data-table-cell-merge"),a=$("<div>"),a.addClass("management-handover-data-table-cell"),a.text(n.getSourceCreatorName()),a.attr("title",n.getSourceCreatorName()),c.append(a)):B==da?(c=$(c),c.addClass("management-handover-data-table-cell-btb"),c.addClass("management-handover-data-table-cell-bl"),a=$("<div>"),a.addClass("management-handover-data-table-cell"),n=n.getPubName(),h(a,J,n),a.attr("title",
n),c.append(a)):B==l?(c=$(c),c.addClass("management-handover-data-table-cell-btb"),a=$("<div>"),a.addClass("management-handover-data-table-cell"),a.text(n.getPubTypeName()),a.attr("title",n.getPubTypeName()),c.append(a)):B==Ha&&(c=$(c),c.addClass("management-handover-data-table-cell-btb"),a=$("<div>"),a.addClass("management-handover-data-table-cell"),n=n.getPubPathName(),h(a,J,n),a.attr("title",n),c.append(a))};var h=function(c,a,q){if(a&&q){a=a.toUpperCase();var n=q.toUpperCase(),B=n.split(a),K=
a.length,E;for(E in B){var N=n.indexOf(B[E]),ta=q.substr(sa,B[E].length);N+=B[E].length;var ea=n.length-N;n=n.substr(N,ea);q=q.substr(N,ea);N=$("<span>");N.text(ta);N.appendTo(c);if(E!=B.length-1&&1<B.length){var sa=n.indexOf(a);ta=q.substr(sa,K);N=sa+K;ea=n.length-N;n=n.substr(N,ea);q=q.substr(N,ea);N=$("<span>");N.text(ta);N.css("color","red");N.clone().appendTo(c)}}}else c.text(q)}}var g=this,p,r,u,t,A,z,H,D,L,F,M,P,J,k,V=-1,Z=-1,aa=-1,ba=-1,ca=-1,da=-1,l=-1,Ha=-1,U,T,I=[],fa={},ha=[],ua=new ka,
ia,ja,X,Y,va={},Ia;this.createJqUi=function(){if(!p){p=$("<div>");p.addClass("management-handover");var e=$("<div>");e.addClass("management-handover-filter");var b=new ka;b.setText(v.get("filter","\u7b5b\u9009\u6761\u4ef6"));b=b.getJqUi();b.attr("title",v.get("filter","\u7b5b\u9009\u6761\u4ef6"));b.children().css("font-size","14px");var m=new ka,h=v.get("user","\u62e5\u6709\u8005");m.setText(h);m=m.getJqUi();m.attr("title",h);h=$("<div tabIndex=-1>");h.addClass("management-handover-search-user-change-area");
h.on("mousedown",la);h.on("mouseup",la);h.on("keydown",la);h.on("keyup",la);e.append(h);u=new y;u.setShowDisabledFilter(!0);u.setFunSelectedChangeListener(wa);h=u.getJqUi();t=new C;t.setFunSelectedChangeListener(wa);t.hide();var c="en"==ma.getUrlParamValue("language")?50:0;Q.layoutCtrl(b,18,20,60+c,23);Q.layoutCtrl(m,92+c,20,40,23);Q.layoutCtrl(h,132+c,20,250,23);Q.layoutCtrl(t.getJqUi(),132+c,20,250,23);b.appendTo(e);m.appendTo(e);h.appendTo(e);t.getJqUi().appendTo(e);e.appendTo(p);A=$("<div>");
A.addClass("management-handover-toolbar");z=new W;z.setText(v.get("handOver","\u79fb\u4ea4"));z.setTooltips(v.get("handOverTBtnTips","\u79fb\u4ea4\u9009\u4e2d\u7684\u884c"));z.setIconSetter(function(a,q){G.Icons.background(a,q)});z.setIconName("handover");z.addActionListener(Ua);z.getJqUi().appendTo(A);H=new W;H.setText(v.get("handOverRecord","\u79fb\u4ea4\u8bb0\u5f55"));H.setTooltips(v.get("handOverRecordTBtnTips","\u67e5\u770b\u79fb\u4ea4\u8bb0\u5f55"));H.setIconName("handover_record");H.setIconSetter(function(a,
q){G.Icons.background(a,q)});H.addActionListener(Va);H.getJqUi().appendTo(A);D=new W;D.setText(v.get("refresh","\u5237\u65b0"));D.setTooltips(v.get("refresh","\u5237\u65b0"));D.setIconName("refresh");D.setIconSetter(function(a,q){G.Icons.background(a,q)});D.addActionListener(wa);D.getJqUi().appendTo(A);L=new W;L.setText(v.get("closeTab","\u9000\u51fa"));L.setTooltips(v.get("closeTab","\u9000\u51fa"));L.setIconName("close_tab");L.setIconSetter(function(a,q){G.Icons.background(a,q)});L.addActionListener(Wa);
L.getJqUi().appendTo(A);Xa();A.appendTo(p);0!=document.body.clientHeight&&0!=document.body.clientWidth||/Trident|MSIE/.test(window.navigator.userAgent)?Ja():(F&&F.unobserve(),F=new xa,F.setDelay(250),F.setCallback(function(){Ka();Ja()}),F.observe());g.initJqUiCallback()}return p};var Ja=function(){var e=$("<div>");e.addClass("management-handover-data");e.css("height",document.documentElement.clientHeight-100+"px");var b=$("<div>");b.addClass("management-handover-content");U=$("<div>");U.addClass("management-handover-tips");
Y=$("<div>");Y.addClass("management-handover-tips-background");G.Icons.background(Y,"tips-background");X=$("<div>");X.addClass("management-handover-tips-text");X.text(v.get("tips","\u8bf7\u5148\u9009\u62e9\u4e00\u4e2a\u7528\u6237"));U.append(Y);U.append(X);U.appendTo(b);b.appendTo(e);ia=ua.getJqUi();ia.addClass("management-handover-content-row-count");ia.appendTo(e);k=S.createTable();k.setColumnFitVisibleWidth(!0);k.setSyncMergeBlockWhenModelChanged(!1);k.setMergeBlockTextVisibleAlways(!0);k.addCellClickListener(Ya);
b=new d(k);b.setOutsideVisible(!1);k.setCellRender(b);k.setSyncUIWhenModelChanged(!0);g.createTableHead(k);b=$(k.getUI());b.addClass("management-handover-content-table");ja=b;ja.children().css("overflow-x","hidden");ja.appendTo(e);e.appendTo(p)};this.getMessageCurtain=function(){r||(r=new La,r.getJqUi().appendTo($("body")));return r};var Ua=function(){var e=[],b=[];if(I)for(var m=0;m<I.length;m++){var h=I[m];h&&h.isChecked()&&(h=h.getUserObject())&&0!=h.length&&(b.push(h),e.push(JSON.stringify(h[0].toJsonObject())))}g.loadHandOverInfo(b)&&
(0>=e.length?g.getMessageCurtain().showPrompt(v.get("needChooseRecord","\u8bf7\u81f3\u5c11\u9009\u4e2d\u4e00\u6761\u9700\u8981\u79fb\u4ea4\u7684\u8bb0\u5f55\u3002"),2E3):(b=new y,b.setFunSelectedChangeListener(function(c){if(c.getUserId()==u.getUser().getUserId())g.getMessageCurtain().showPrompt(v.get("reChooseUser","\u79fb\u4ea4\u76ee\u6807\u548c\u73b0\u62e5\u6709\u8005\u4e0d\u80fd\u662f\u540c\u4e00\u4e2a\u7528\u6237\uff0c\u8bf7\u91cd\u65b0\u9009\u62e9\u7528\u6237\u3002"),2E3);else{var a=na.createFeedbackDialog();
a.setOptionType(na.OPTION_OK_CANCEL);a.setMessage(v.get("confirmToHandOver","\u786e\u5b9a\u8981\u5c06\u9009\u4e2d\u7684\u8bb0\u5f55\u79fb\u4ea4\u7ed9\u201c#1\u201d\u5417\uff1f").replace("#1",c.getUserName()));a.setClosingChecker(function(q){q==na.RETURN_OK&&Za(e,c.getUserId());return!0});a.showDialog()}}),b.showUserChooseForm()))},Za=function(e,b){var m=new R(G.HandOverIntegration.getRemoteImpl(),function(a){var q=u.getUser().getUserId();g.handOverCallback(a,q,b);Ma(function(){g.getMessageCurtain().showSuccess(v.get("handOverSuccess",
"\u79fb\u4ea4\u6210\u529f\u3002"),2E3)})},function(a,q){return 911E4==a?(ya(a,q),!0):9110001==a?(g.getMessageCurtain().showError(v.get("qingFileStorageLimit","\u76ee\u6807\u7528\u6237\u8f7b\u5b58\u50a8\u7a7a\u95f4\u4e0d\u8db3\u3002"),2E3),!0):9110002==a?(g.getMessageCurtain().showError(v.get("notGetLappOpendId","\u83b7\u53d6\u76ee\u6807\u7528\u6237\u8f7b\u5e94\u7528\u4fe1\u606f\u5931\u8d25\uff0c\u8bf7\u5148\u540c\u6b65\u76ee\u6807\u7528\u6237\u8f7b\u5e94\u7528\u4fe1\u606f\u3002"),2E3),!0):9110003==
a?(g.getMessageCurtain().showError(v.get("isInHandOver","\u5b58\u5728\u8fdb\u884c\u4e2d\u7684\u79fb\u4ea4\u64cd\u4f5c\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\u3002"),2E3),!0):9110004==a?(g.getMessageCurtain().showError(v.get("handOverSourceNotExist","\u68c0\u6d4b\u5230\u539f\u62e5\u6709\u8005\u6570\u636e\u5185\u5bb9\u53d1\u751f\u53d8\u5316\uff0c\u8bf7\u5237\u65b0\u51fa\u6700\u65b0\u6570\u636e\u540e\u518d\u8fdb\u884c\u79fb\u4ea4\u64cd\u4f5c\u3002"),2E3),!0):9110005==a?(g.getMessageCurtain().showError(v.get("nothingToHandOver",
"\u6ca1\u6709\u53ef\u79fb\u4ea4\u7684\u5185\u5bb9\uff0c\u8bf7\u5237\u65b0\u6570\u636e\u540e\u518d\u8fdb\u884c\u79fb\u4ea4\u64cd\u4f5c\u3002"),2E3),!0):!1});m.setShowBlocking(!0);var h=G.HandOverIntegration.getPublishedRuntimeUrl(),c=G.HandOverIntegration.getParamPathPrefix();m.handOver(e,b,h,c,va)},Va=function(){var e=[],b=0;if(I)for(var m=0;m<I.length;m++){var h=I[m];if(h&&h.isChecked()){h=h.getUserObject();for(var c=0;c<h.length;c++)e.push(JSON.stringify(h[c].toJsonObject()));b++}}1!=b?g.getMessageCurtain().showPrompt(v.get("selectSingleRecordsToView",
"\u8bf7\u9009\u62e9\u5355\u7ec4\u8bb0\u5f55\u8fdb\u884c\u67e5\u770b\u3002"),2E3):(b=G.HandOverIntegration.getRemoteImpl(),b=new R(b,function(a){(new O(a,Ia)).showDialog()},function(a,q){return 911E4==a?(ya(a,q),!0):!1}),b.setShowBlocking(!0),b.queryHandOverRecords(e))},Wa=function(){Na.closeCurrentTab()},Xa=function(e){M?M.getJqUi().show():(M=new Oa,M.addSearchListener(oa),M.setSearchListenerDelay(1E3),M.setShowSearchIcon(!0),P=M.getJqUi(),P.addClass("management-handover-search-searchBox"),g.setSearchBoxProps(M),
P.children(".sa-ctrl-textfield-input").on("keydown",function(b){13==(b.keyCode||b.which||b.charCode)&&oa()}),P.on("mouseenter",function(){document.body.addEventListener("mousedown",Pa,!0)}),P.appendTo(A))},Pa=function(e){for(e=e.target;e!=document.body;){if(e==P[0])return;e=e.parentNode}document.body.removeEventListener("mousedown",Pa,!0)},oa=function(e){M&&(J=M.getText())&&(J=J.trim());var b=u.getUser();if(!b&&J)g.getMessageCurtain().showPrompt(v.get("chooseUser","\u8bf7\u9009\u62e9\u4e00\u4e2a\u7528\u6237\u3002"),
2E3);else if(b){var m=b.getUserId(),h=[];b=[];b.push(m);for(m=0;m<ha.length;m++){var c=new f;c.fromJsonObject(ha[m]);h.push(c)}va={};g.loadPublishAppTypeMap(b,h,function(a){va=a;$a(h,e)})}},Qa=function(e,b){for(var m=!1,h=0;h<e.length;h++){var c=e[h];if(b.getPubId()){if(c.getPubId()&&c.getPubId()==b.getPubId()){m=!0;break}}else if(!c.getPubId()){m=!0;break}}m||e.push(b)},$a=function(e,b){var m=[];if(J)for(var h=0;h<e.length;h++){var c=e[h],a=c.getSourceName();a&&a==f.HAS_DELETED&&(a=v.get("hasDeleted",
"\u6765\u6e90\u5df2\u88ab\u5220\u9664"));var q="";q=a?q+a.toLowerCase():q;q=c.getSourcePathName()?q+c.getSourcePathName().toLowerCase():q;q=c.getPubName()?q+c.getPubName().toLowerCase():q;q=c.getPubPathName()?q+c.getPubPathName().toLowerCase():q;-1<q.indexOf(J.toLowerCase())&&m.push(c)}else for(h=0;h<e.length;h++)m.push(e[h]);a={};q=[];for(h=0;h<m.length;h++){var n=m[h],B=n.getSourceId();if(a[B])var K=a[B];else K=[],q.push(B);Qa(K,n);for(var E=0;E<e.length;E++)c=e[E],c.getSourceId()==n.getSourceId()&&
c.getPubId()&&c.getPubId()!=n.getPubId()&&Qa(K,c);a[B]=K}e=[];for(h=0;h<q.length;h++)B=q[h],e=e.concat(a[B]);(m=m.length)?(m=v.get("totalRows","\u5171#1\u884c").replace("#1",m),ua.setText(m),ia.addClass("management-handover-content-row-count-show")):(m=v.get("totalRows","\u5171#1\u884c").replace("#1",0),ua.setText(m),ia.removeClass("management-handover-content-row-count-show"));F&&0!=document.body.clientHeight&&0!=document.body.clientWidth||/Trident|MSIE/.test(window.navigator.userAgent)?"boolean"==
typeof b&&b?(b=$.extend(!0,{},fa),Ra(e,b)):Ra(e):(F&&F.unobserve(),F=new xa,F.setDelay(250),F.setCallback(function(){Ka();oa(!0)}),F.observe())},za=!1,Aa=!1,Sa=!1,la=function(e){var b=e.type;e=e.keyCode;b&&"mousedown"===b&&(Aa=!0);b&&"mouseup"===b&&(Aa=!1);b&&e&&"keydown"===b&&"17"==e&&(za=!0);b&&e&&"keyup"===b&&"17"==e&&(za=!1);za&&Aa&&!Sa&&(Sa=!0,u.hide(),t.show(),b=u,u=t,t=b)},Ka=function(){document.body.style.height=document.documentElement.clientHeight+"px"};this.createTableHead=function(e){throw Error("Override me");
};this.loadHandOverInfo=function(e){throw Error("Override me");};this.loadPublishAppTypeMap=function(e,b,m){throw Error("Override me");};this.initJqUiCallback=function(){throw Error("Override me");};this.handOverCallback=function(e,b,m){throw Error("Override me");};this.setSearchBoxProps=function(e){throw Error("Override me");};this.setHandOverReCordDescTemplate=function(e){Ia=e};this.setTableColumnIndex=function(e,b,m,h,c,a,q,n){V=e;Z=b;aa=m;ba=h;ca=c;da=a;l=q;Ha=n};var wa=function(){Ma(null)},Ma=
function(e){var b=u.getUser();if(b){var m=G.HandOverIntegration.getRemoteImpl();m=new R(m,function(h){ha=h;oa();e&&e()},function(h,c){return 911E4==h?(ya(h,c),!0):!1});m.setShowBlocking(!0);m.queryDataByUserId(b.getUserId())}else g.getMessageCurtain().showPrompt(v.get("chooseUser","\u8bf7\u9009\u62e9\u4e00\u4e2a\u7528\u6237\u3002"),2E3)},ya=function(e,b){ma.getUrlParamValue("language");var m=ma.getUrlParamValue("appID");b=v.get("noHandOverPerm","\u6ca1\u6709\u79fb\u4ea4\u6743\u9650\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458\u5206\u914d\u6743\u9650");
var h=com.kingdee.bos.qing.common.Base64Util,c={};c.appID=m;com.kingdee.bos.qing.framework.common.RemoteFramework.openErrorPage(e,h.encode(encodeURI(b)),c)},Ra=function(e,b){I=[];fa=b?$.extend(!0,{},b):{};S.clear(k);if(e&&0<e.length){g.createTableHead(k);U.css("display","none");ja.css("display","block");var m={},h=3;b=[];for(var c=!1,a=0;a<e.length;a++){var q=e[a],n=q.getSourceCreatorId()+"_"+q.getSourceType()+"_"+q.getSourceId();if(m[n])B=m[n].getUserObject(),B.push(q),I.push(null);else{var B=[];
B.push(q);var K=new ra;K.setText("");K.setUserObject(B);fa[n]&&fa[n].isChecked()?K.setChecked(!0):K.setChecked(!1);I.push(K);m[n]=K}n=q.getSourceCreatorId()+"_"+q.getSourceType()+"_"+q.getSourceId();n==E?c=!0:(c&&(b.push([h,a+2,0,0]),b.push([h,a+2,1,1]),b.push([h,a+2,2,2]),b.push([h,a+2,3,3]),b.push([h,a+2,4,4])),h=a+3,c=!1);var E=n;c&&a==e.length-1&&(b.push([h,a+3,0,0]),b.push([h,a+3,1,1]),b.push([h,a+3,2,2]),b.push([h,a+3,3,3]),b.push([h,a+3,4,4]));n=S.createRow(k);n.setHeight(30);n.setUserObject(q)}fa=
m;e=k.getColumnsCount();E=[];for(c=0;c<b.length;c++)a=b[c],m=a[2],m<e&&E.push(new KTMergeBlock(a[0],a[1],m,a[3]<e?a[3]:e-1));k.clearMergeBlocks();k.addMergeBlocks(E);S.refresh(k);c=!0;for(a=0;a<I.length;a++)if((b=I[a])&&!b.isChecked()){c=!1;break}T.setChecked(c)}else G.Icons.background(Y,"nodata"),Y.addClass("management-handover-tips-background-no-data-icon"),ha&&0<ha.length&&J?X.text(v.get("noSearchData","\u6ca1\u6709\u7b26\u5408\u641c\u7d22\u6761\u4ef6\u7684\u7ed3\u679c")):X.text(v.get("nodata",
"\u6682\u65e0\u76f8\u5173\u6570\u636e")),U.css("display","block"),ja.css("display","none")},Ya=function(e,b){if(b.isLeftButton()&&(e=b.getRowIdx(),!(e<S.getHeadRowCount()))){b=k.getRow(e).getUserObject();if(I)for(e=0;e<I.length;e++){var m=I[e];if(m){var h=m.getUserObject()[0],c=b.getSourceCreatorId()+"_"+b.getSourceType()+"_"+b.getSourceId();h.getSourceCreatorId()+"_"+h.getSourceType()+"_"+h.getSourceId()==c&&m.setChecked(!m.isChecked())}}b=!0;for(e=0;e<I.length;e++)if((m=I[e])&&!m.isChecked()){b=
!1;break}T.setChecked(b)}}};G.HandOverVO=f;G.HandOverRecordDialog=O;G.UserSelectorDialog=y;G.UserModelTransformer=new function(){var d;this.getUserModel=function(g){if(d)return d(g);if(g&&g.content){g=g.content;var p=g.selecteds;if("cancel"==g.operation||"undefined"==p)g=void 0;else{g=Object.keys(p)[0];p=p[g];var r=new qa;r.setUserName(p);r.setUserId(g);g=r}}else g=void 0;return g};this.registImpl=function(g){d=g}};G.User=qa;var ma,Ta,Ga,Ea,Q,Da,S,v,Na,xa,W,Oa,ka,pa,La,na,Ca,ra,Ba;(function(){var d=
com.kingdee.bos.qing;ma=d.Seer;d=com.kingdee.bos.qing.framework.common;Ta=d.AbstractIcons;Ga=d.AbstractRemoteCall;Ea=d.AbstractFacade;d=com.kingdee.bos.qing.common;Q=d.DomUtil;Da=d.DateFormater;d=com.kingdee.bos.qing.common.ui;S=d.TableUtil;d=com.kingdee.bos.qing.framework.common;v=d.MultilanguageManager.createPackageAccessor(G);Na=d.TabbedUiUtil;xa=d.WindowResizeObserver;d=com.kingdee.bos.qing.ui.component;W=d.ToolbarButton;Oa=d.SearchBox;ka=d.Label;pa=d.TextField;La=d.MessageCurtain;na=d.MessageDialog;
Ca=d.AbstractModalDialog;ra=d.CheckBox;d=com.kingdee.bos.qing.integration;Ba=d.UserAndRoleForm})();f.SOURCETYPE_SUBJECT=0;f.SOURCETYPE_DSB=1;f.SOURCETYPE_BILL=2;f.SOURCETYPE_PUBLISH=3;f.SOURCETYPE_REPORT=4;f.SOURCETYPE_DATASET=5;f.SOURCETYPE_COLLABORATION=6;f.PUBTYPE_PUBLISH="PUBLISH";f.PUBTYPE_PUSH="PUSH";f.HAS_DELETED=" ";G.Icons=new function(){Ta.call(this);var d=this.protectedMethod;this.protectedInit=function(p,r){p=com.kingdee.bos.qing.handover.ComboIcon;if(!p)throw Error("com.kingdee.bos.qing.handover.ComboIcon not found.");
p.define(r,"management-sprite");r.setGap(1);r.setStartPosition(1,1);r.setIconSize(16,16);g(0,0,"f7");g(0,1,"handover");g(0,1,"handover_hover");g(0,2,"handover_record");g(0,2,"handover_record_hover");g(0,3,"refresh");g(0,3,"refresh_hover");g(0,4,"close_tab");g(0,4,"close_tab_hover");r.setStartPosition(1,41);r.setIconSize(17,17);g(0,0,"icon_search");g(1,0,"icon_search_hover");p.define(r,"tips-background");r.setStartPosition(0,0);r.setGap(0);r.setIconSize(264,191);g(0,0,"tips-background");p.define(r,
"nodata");r.setStartPosition(0,0);r.setGap(0);r.setIconSize(220,220);g(0,0,"nodata")};var g=function(p,r,u){d.registIcon(p,r,u)}};G.HandOverIntegration=new function(){var d,g,p=new Fa,r=new Fa;this.getParamPathPrefix=function(){return d};this.setParamPathPrefix=function(u){d=u};this.getPublishedRuntimeUrl=function(){return g};this.setPublishedRuntimeUrl=function(u){g=u};this.getRemoteImpl=function(){return p};this.setRemoteUrl=function(u){p.setRemoteUrl(u)};this.getPublishRemoteImpl=function(){return r};
this.setPublishRemoteImplUrl=function(u){r.setRemoteUrl(u)}}})();
//qingVersionTag: 20250324