(function(){function I(d){var h=d.getRootPath();this.setRootPath=function(f){h=f};var a=[],l=[];this.pushJs=function(f){t(l,f);a.push([h,f])};var n=[],v=[];this.pushCss=function(f){t(v,f);n.push([h,f])};var k=[],w=[];this.pushSkinJs=function(f,e){t(w,f+"//"+e);k.push([h,f,e])};var x=[],y=[];this.pushSkinCss=function(f,e){t(y,f+"//"+e);x.push([h,f,e])};var z=[],A=[];this.pushI18n=function(f,e){t(A,f+"//"+e);z.push([h,f,e])};var t=function(f,e){e=h+"|"+e;if(f[e])throw Error("Duplicated: "+e);f[e]=!0};
this.load=function(f){f&&d.setCallback(f);for(f=0;f<a.length;f++){var e=a[f],r=e[0],q=e[1];d.setRootPath(r);d.loadJs(q)}for(f=0;f<n.length;f++)e=n[f],r=e[0],q=e[1],d.setRootPath(r),d.loadCss(q);for(f=0;f<k.length;f++)e=k[f],r=e[0],q=e[1],e=e[2],d.setRootPath(r),d.loadSkinJs(q,e);for(f=0;f<x.length;f++)e=x[f],r=e[0],q=e[1],e=e[2],d.setRootPath(r),d.loadSkinCss(q,e);for(f=0;f<z.length;f++)e=z[f],r=e[0],q=e[1],e=e[2],d.setRootPath(r),d.loadI18n(q,e)}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&
(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});var m=com.kingdee.bos.qing;m.CodeLoader=new function(){var d=this,h=null,a=[],l=!1,n,v="/",k=".",w="pioneer",x="zh_CN",y={},z=[],A=!1,t;this.createSafety=function(){return new I(d)};var f=function(){l=!0;var b=new XMLHttpRequest;b.open("GET",k+"/resources.json?version="+(new Date).getTime(),!0);b.setRequestHeader("Content-type","application/json");b.onreadystatechange=
function(){if(4==b.readyState){if(200==b.status)try{h=JSON.parse(b.responseText)}catch(p){window.console&&console.log(p)}!h&&(h={});for(var c=0;c<a.length;c++){var g=a[c];F(g[0],g[1],g[2])}a=null;l=!1}};b.send()};this.getIconUrl=function(b,c){c&&(b=b+"/skin/"+w+"/res/"+c);return r(k,b)};this.setRootPath=function(b){k=b};this.getRootPath=function(){return k};this.setSkinName=function(b){w=b};this.getSkinName=function(){return w};this.setI18nLocal=function(b){x=b};this.setCdnUrls=function(b){n=b};this.setUrlBase=
function(b){var c=window.location.protocol+"//"+window.location.host+window.location.pathname,g=c.lastIndexOf("/");c=c.substring(0,g);g=c.indexOf(b);if(0<=g)c=c.substring(g+b.length);else throw Error("It must be part of current URL.");v=c};this.setCallback=function(b){e(b)};this.loadJsBatch=function(b,c){e(c);c=!1;for(var g=0;g<b.length;g++){var p=b[g],u=r(k,p);y[u]||(c=!0,q(p,"js"))}c||G()};this.loadJs=function(b,c){e(c);q(b,"js")};this.loadCss=function(b,c){e(c);q(b,"css")};this.loadSkinJs=function(b,
c,g){e(g);q((b?b+"/":"")+"skin/"+w+"/"+c+".js","js")};this.loadSkinCss=function(b,c,g){e(g);q((b?b+"/":"")+"skin/"+w+"/"+c+".css","css")};this.loadI18n=function(b,c,g){e(g);q((b?b+"/":"")+"i18n/"+c+"-"+x+".js","js")};var e=function(b){b&&(!t&&(t=[]),t.push(b))},r=function(b,c){if("."==b){var g=n?n.length:0;if(0==g)g="";else if(1==g)g=n[0];else{for(var p=0,u=0;u<c.length;u++)p+=c.charCodeAt(u);g=n[p%g]}g&&(b=v)}else if("/"==b.charAt(0))g="";else throw Error("Unsupported");p="";h&&(u=h[c])&&(p="?version="+
u);return g+(b?b+"/":"")+c+p},q=function(b,c){h?F(k,b,c):(a.push([k,b,c]),l||f())},F=function(b,c,g){b=r(b,c);z.push([b,g]);A||(A=!0,C())},G=function(){if(t){var b=t;t=null;for(var c=0;c<b.length;c++)(0,b[c])()}},C=function(){if(0<z.length){var b=z.shift(),c=b[0];b=b[1];if(y[c])C();else switch(b){case "js":J(c);break;case "css":K(c);break;default:throw Error("I don't know: "+b);}}else A=!1,G()},J=function(b){var c=document.createElement("script");c.src=b;c.onerror=function(){E(b)};c.onload=function(){B(b)};
document.head.appendChild(c)},K=function(b){var c=document.createElement("link");c.rel="stylesheet";c.href=b;var g=536>navigator.userAgent.replace(/.*(?:AppleWebKit|AndroidWebKit)\/?(\d+).*/i,"$1"),p="onload"in c;g||!p?(document.head.appendChild(c),setTimeout(function(){H(b,c,g,0)},1)):(p?(c.onerror=function(){E(b)},c.onload=function(){B(b)}):c.onreadystatechange=function(){/loaded|complete/.test(c.readyState)?B(b):E(b)},document.head.appendChild(c))},B=function(b){window.console&&console.log("Loading success: "+
b);y[b]=!0;C()},E=function(b){window.console&&console.error("Loading error: "+b);y[b]=!1;C()},H=function(b,c,g,p){var u=c.sheet;p+=1;if(3E5<p){var D=!0;c=null;B(b)}else{if(g)u&&(D=!0);else if(u)try{u.cssRules&&(D=!0)}catch(L){"NS_ERROR_DOM_SECURITY_ERR"===L.name&&(D=!0)}setTimeout(function(){D?B(b):H(b,c,g,p)},20)}}};m.CommonCodeImporter=new function(){var d=this;this.importRemoteProxy=function(a){a.loadJsBatch(["jquery/jquery.js","common/qing-table.js","common/qing-common.js","common/qing-remote-proxy.js"]);
a.loadSkinJs("common","skin");a.loadI18n("common","qing-common");a.loadSkinCss("common","qing-ui-component")};this.importCode=function(a){a.loadJsBatch("jquery/jquery.js common/qing-table.js common/qing-common.js common/qing-framework-remote.js core/qing-charts.js core/qing-main.js core/qing-scene.js".split(" "))};this.importSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinJs("core","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinCss("core","qing")};this.importI18n=function(a){a.loadI18n("common",
"qing-common");a.loadI18n("core","qing-core")};this.importDashboardDesignerCode=function(a){d.importCode(a);a.loadJsBatch(["dashboard/dsb-main.js","dashboard/dsb-scene.js"])};this.importDashboardDesignerSkin=function(a){d.importSkin(a);a.loadSkinJs("dashboard","skin");a.loadSkinCss("dashboard","dsb")};this.importDashboardDesignerI18n=function(a){d.importI18n(a);a.loadI18n("dashboard","dsb")};this.importMapDesignerCode=function(a){a.loadJsBatch("jquery/jquery.js common/qing-table.js common/qing-common.js common/qing-framework-remote.js core/qing-charts.js map-designer/map-designer.js".split(" "))};
this.importMapDesignerSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinJs("map-designer","skin");a.loadSkinCss("map-designer","map-designer")};this.importMapDesignerI18n=function(a){a.loadI18n("common","qing-common");a.loadI18n("map-designer","map-designer")};this.importDataModelingCode=function(a){a.loadJs("jquery/jquery.js");a.loadJs("common/qing-table.js");a.loadJs("common/qing-common.js");a.loadJs("common/qing-framework-remote.js");a.loadJs("common/qing-schedule.js");
a.loadJs("biz-common/qing-biz-common.js");a.loadJs("data-modeling/qing-data-modeling.js")};this.importDataModelingSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinJs("biz-common","skin");a.loadSkinJs("data-modeling","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinCss("biz-common","biz-common");a.loadSkinCss("data-modeling","dm-relationview");a.loadSkinCss("data-modeling","dm")};this.importDataModelingI18n=function(a){a.loadI18n("common","qing-common");a.loadJs("common/qing-framework-remote.js");
a.loadI18n("common","qing-schedule");a.loadI18n("biz-common","biz-common");a.loadI18n("data-modeling","qing-dm")};this.importLongerMobileCode=function(a,l){h(a,l);a.loadJs("lightapp/core/qing-lapp-longer-ui.js");a.loadJs("lightapp/scene/qing-lapp-longer-scene.js")};this.importSquareMobileCode=function(a,l){h(a,l);a.loadJs("lightapp/core/qing-lapp-square-ui.js");a.loadJs("lightapp/scene/qing-lapp-square-scene.js")};this.importDsbMobileCode=function(a,l){h(a,l);a.loadJs("dashboard/dsb-main-mobile.js");
a.loadJs("lightapp/dashboard/dsb-widget-ctrl-mobile.js");a.loadJs("dashboard/dsb-scene.js");a.loadJs("lightapp/core/qing-lapp-dsb-ui.js");a.loadJs("lightapp/scene/qing-lapp-dsb-scene.js")};var h=function(a,l){a.loadJs("common/qing-table.js");a.loadJs("common/qing-common.js");a.loadJs("common/qing-framework-remote.js");l?(a.loadJs("core/qing-charts.js"),a.loadJs("core/qing-main.js")):(a.loadJs("core/qing-mobile-charts.js"),a.loadJs("core/qing-mobile-main.js"));a.loadJs("core/qing-scene.js");a.loadJs("lightapp/common/qing-lapp-common.js")};
this.importLappSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinJs("core","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinCss("core","qing");a.loadCss("lightapp/common/qing-lapp.css")};this.importLappI18n=function(a){a.loadI18n("common","qing-common");a.loadI18n("core","qing-core");a.loadI18n("lightapp/core","qing-lapp-core")};this.lazyImportFunctionProvider=function(a){m.CodeLoader.setCallback(a);m.CodeLoader.loadJs("common/qing-functions.js");m.CodeLoader.loadI18n("common",
"qing-formula")}};m.Seer=new function(){this.getUrlParamValue=function(d){var h=window.location.search,a=d+"=";for(d=-1;!(d=h.indexOf(a,d+1),0>=d);){var l=h.charAt(d-1);if("&"==l||"?"==l)break}return-1!=d?(d+=a.length,a=h.indexOf("&",d),a=-1==a?h.length:a,window.decodeURIComponent(h.substring(d,a))):null}};m.SkinUtil=new function(){var d,h;this.setUrlParamValue=function(a){(a=a?a.split("_"):null)?(d=a[0],h=1<a.length?a[1]:null):h=d=null};this.getUrlParamValue=function(){return d?h?d+"_"+h:d:null};
this.getMainSkinName=function(){return d};this.getSkinColorTheme=function(){return h};this.changeColorTheme=function(a){var l=com.kingdee.bos.qing.common.ColorUtil.decodeStringToRgbArray(a);if(l){var n=com.kingdee.bos.qing.common.ColorUtil,v=n.rgbToHsv(l[0],l[1],l[2]),k=v[0],w=v[1]/100,x=v[2]/100;v=n.hsvToRgb(60<=k&&240>=k?0>k-2?k-2+360:k-2:360<k+2?k+2-360:k+2,Math.round(100*Math.max(.05,w-.18)),Math.round(100*Math.min(1,x+.08)));k=n.hsvToRgb(60<=k&&240>=k?0>k-10?k-10+360:k-10:360<k+10?k+10-360:k+
10,Math.round(100*Math.max(.05,w-.9)),Math.round(100*Math.min(1,x+.4)));n={};n["--color-main"]=a;n["--color-lightish"]="rgb("+v.join(",")+")";n["--color-tint"]="rgba("+l.join(",")+",0.5)";n["--color-pale"]="rgb("+k.join(",")+")";h=a;a=document.body.style;for(var y in n)a.setProperty(y,n[y])}else console&&console.error("Unsupported skin color theme: "+a)}};m.SkinUtil.ORANGE="orange";m.SkinUtil.BLUE="blue";m.SkinUtil.GRAPE="grape";m.SkinUtil.CYAN="cyan";m.SkinUtil.RED="red";(function(){var d=m.Seer.getUrlParamValue("skin");
m.SkinUtil.setUrlParamValue(d);(d=m.SkinUtil.getMainSkinName())&&m.CodeLoader.setSkinName(d);(d=m.Seer.getUrlParamValue("language"))&&m.CodeLoader.setI18nLocal(d);(d=m.Seer.getUrlParamValue("cdnUrl"))&&m.CodeLoader.setCdnUrls(d.split(";"));(d=m.Seer.getUrlParamValue("path"))&&m.CodeLoader.setUrlBase(d)})()})();
//qingVersionTag: 20250324