var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,p,n){if(f==Array.prototype||f==Object.prototype)return f;f[p]=n.value;return f};
$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var p=0;p<f.length;++p){var n=f[p];if(n&&n.Math==Math)return n}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,p){var n=$jscomp.propertyToPolyfillSymbol[p];if(null==n)return f[p];n=f[n];return void 0!==n?n:f[p]};$jscomp.polyfill=function(f,p,n,t){p&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,p,n,t):$jscomp.polyfillUnisolated(f,p,n,t))};
$jscomp.polyfillUnisolated=function(f,p,n,t){n=$jscomp.global;f=f.split(".");for(t=0;t<f.length-1;t++){var w=f[t];if(!(w in n))return;n=n[w]}f=f[f.length-1];t=n[f];p=p(t);p!=t&&null!=p&&$jscomp.defineProperty(n,f,{configurable:!0,writable:!0,value:p})};
$jscomp.polyfillIsolated=function(f,p,n,t){var w=f.split(".");f=1===w.length;t=w[0];t=!f&&t in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var G=0;G<w.length-1;G++){var T=w[G];if(!(T in t))return;t=t[T]}w=w[w.length-1];n=$jscomp.IS_SYMBOL_NATIVE&&"es6"===n?t[w]:null;p=p(n);null!=p&&(f?$jscomp.defineProperty($jscomp.polyfills,w,{configurable:!0,writable:!0,value:p}):p!==n&&(void 0===$jscomp.propertyToPolyfillSymbol[w]&&(n=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[w]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(w):$jscomp.POLYFILL_PREFIX+n+"$"+w),$jscomp.defineProperty(t,$jscomp.propertyToPolyfillSymbol[w],{configurable:!0,writable:!0,value:p})))};$jscomp.polyfill("Object.is",function(f){return f?f:function(p,n){return p===n?0!==p||1/p===1/n:p!==p&&n!==n}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(f){return f?f:function(p,n){var t=this;t instanceof String&&(t=String(t));var w=t.length;n=n||0;for(0>n&&(n=Math.max(n+w,0));n<w;n++){var G=t[n];if(G===p||Object.is(G,p))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(f,p,n){if(null==f)throw new TypeError("The 'this' value for String.prototype."+n+" must not be null or undefined");if(p instanceof RegExp)throw new TypeError("First argument to String.prototype."+n+" must not be a regular expression");return f+""};$jscomp.polyfill("String.prototype.includes",function(f){return f?f:function(p,n){return-1!==$jscomp.checkStringArgs(this,p,"includes").indexOf(p,n||0)}},"es6","es3");
$jscomp.findInternal=function(f,p,n){f instanceof String&&(f=String(f));for(var t=f.length,w=0;w<t;w++){var G=f[w];if(p.call(n,G,w,f))return{i:w,v:G}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(f){return f?f:function(p,n){return $jscomp.findInternal(this,p,n).v}},"es6","es3");
(function(){"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.extreport&&(com.kingdee.bos.extreport={});"undefined"==typeof com.kingdee.bos.extreport.runtime&&(com.kingdee.bos.extreport.runtime={});"undefined"==typeof com.kingdee.bos.extreport.runtime.exportmanage&&(com.kingdee.bos.extreport.runtime.exportmanage={});var f=com.kingdee.bos.extreport.runtime.exportmanage,p,
n;(function(){var t=com.kingdee.bos.qing.ui.component;p=t.MenuModel;n=t.MenuItemModel})();f.ExportMenuCreator=function(){var t,w,G,T,P;this.create=function(m,Q,N,U,S,W){T=N;t=S;P=new f.ExportManage;P.setDependentApi(T);P.setMenuStateUpdater(X,ca);P.setRptName(W);m&&(N=new p,N.addItemModel(V(da,"EXCEL...")),N.addItemModel(V(Y,"PDF...")),w=U(N,"btn_export",t("exportMenuMormal","\u5bfc\u51fa")),w.setEnabled(!1));Q&&(N=new p,N.addItemModel(V(R,t("printSubMenuPreview","\u6253\u5370")+"...")),N.addItemModel(V(q,
t("printSubMenuSetting","\u8bbe\u7f6e")+"...")),G=U(N,"btn_print",t("printMenuNormal","\u6253\u5370")),G.setEnabled(!1));return m&&Q?[w,G]:m?[w]:Q?[G]:[]};var V=function(m,Q){m=new n(m);m.setText(Q);return m},X=function(m){m?(w.setText(t("exportMenuDoing","\u6b63\u5728\u5bfc\u51fa...")),w.setEnabled(!1)):(w.setText(t("exportMenuMormal","\u5bfc\u51fa")),w.setEnabled(!0))},ca=function(m){m?(G.setText(t("printMenuDoing","\u6b63\u5728\u751f\u6210\u9884\u89c8...")),G.setEnabled(!1)):(G.setText(t("printMenuNormal",
"\u6253\u5370")),G.setEnabled(!0))},da=function(m){P.exportExcel2007()},Y=function(m){P.exportPdf()},R=function(m){P.printPreview()},q=function(m){P.printSetting()}}})();(function(){function f(){var b=210,g=297,r=f.VERITICAL,h=18,z=18,u=25,L=25,C=f.SCALING,K=100,y=1,H=1,E=new p,J=new p,F=!0,a=!0,d=!1;this.getPaperWidth=function(){return b};this.setPaperWidth=function(c){b=c};this.getPaperHeight=function(){return g};this.setPaperHeight=function(c){g=c};this.getPageMarginLeft=function(){return h};this.setPageMarginLeft=function(c){h=c};this.getPageMarginRight=function(){return z};this.setPageMarginRight=function(c){z=c};this.getPageMarginTop=function(){return u};this.setPageMarginTop=
function(c){u=c};this.getPageMarginBottom=function(){return L};this.setPageMarginBottom=function(c){L=c};this.getDirection=function(){return r};this.setDirection=function(c){r=c};this.getZoomType=function(){return C};this.setZoomType=function(c){C=c};this.getScaling=function(){return K};this.setScaling=function(c){K=c};this.getZoomOutPageWide=function(){return y};this.setZoomOutPageWide=function(c){y=c};this.getZoomOutPageTall=function(){return H};this.setZoomOutPageTall=function(c){H=c};this.getHeader=
function(){return E};this.getFooter=function(){return J};this.isPagingRowFirst=function(){return F};this.setPagingRowFirst=function(c){F=c};this.isTopHeaderAll=function(){return a};this.setTopHeaderAll=function(c){a=c};this.isLeftHeaderAll=function(){return d};this.setLeftHeaderAll=function(c){d=c};this.toJsonObject=function(){var c={};c.isAutoFit=C==f.SCALING?!1:!0;c.scale=K;c.autoFitWidth=y;c.autoFitHeight=H;var e={};e.paperWidth=b;e.paperHeight=g;e.isLandscape=r==f.HORIZONTAL?!0:!1;e.marginLeft=
h;e.marginRight=z;e.marginTop=u;e.marginBottom=L;e.scaleModel=c;e.listHeaderRow=E.toJsonObject();e.listFooterRow=J.toJsonObject();e.isRowFirst=F;e.isTopHeaderAll=a;e.isLeftHeaderAll=d;return e};this.fromJsonObject=function(c){var e=c.scaleModel;C=e.isAutoFit?f.ADJUSTMENT:f.SCALING;K=e.scale;y=e.autoFitWidth;H=e.autoFitHeight;b=c.paperWidth;g=c.paperHeight;r=c.isLandscape?f.HORIZONTAL:f.VERITICAL;h=c.marginLeft;z=c.marginRight;u=c.marginTop;L=c.marginBottom;E.fromJsonObject(c.listHeaderRow);J.fromJsonObject(c.listFooterRow);
F=c.isRowFirst;a=c.isTopHeaderAll;d=c.isLeftHeaderAll}}function p(){var b=[],g=[],r=[];this.getLeftText=function(){return b.join("\n")};this.setLeftText=function(h){b=h.split("\n")};this.getCenterText=function(){return g.join("\n")};this.setCenterText=function(h){g=h.split("\n")};this.getRightText=function(){return r.join("\n")};this.setRightText=function(h){r=h.split("\n")};this.toJsonObject=function(){return[b,g,r]};this.fromJsonObject=function(h){h[0]&&(b=h[0]);h[1]&&(g=h[1]);h[2]&&(r=h[2])};this.toString=
function(){var h=b.join(" "),z=g.join(" ");z&&(0<h.length&&(h+=", "),h+=z);if(z=r.join(" "))0<h.length&&(h+=", "),h+=z;return h}}function n(){var b,g;this.checkInvalid=function(){if(b.getDirection()==f.VERITICAL){var a=b.getPaperWidth();var d=b.getPaperHeight()}else a=b.getPaperHeight(),d=b.getPaperWidth();return b.getPageMarginLeft()+b.getPageMarginRight()>a/2||b.getPageMarginTop()+b.getPageMarginBottom()>d/2?m.get("invalidMarginPrompt","\u9875\u9762\u8fb9\u8ddd\u592a\u5927\uff0c \u4e0d\u9002\u5408\u5f53\u524d\u7eb8\u5f20\u5927\u5c0f"):
null};this.setModel=function(a){b=a};this.getJqUi=function(){if(!g){var a=new w;a.setTitle(m.get("paperMedia","\u7eb8\u5f20\u5c3a\u5bf8"));var d=new M(m.get("paperType","\u7c7b\u578b")),c=new M(m.get("paperSize","\u5927\u5c0f(mm)")),e=new M(m.get("paperWidth","\u5bbd")),k=new M(m.get("paperHeight","\u9ad8")),l=new Z,v=new O,A=new O;h(l,v,A);var x=a.getJqContainer();x.append(d.getJqUi());x.append(l.getJqUi());x.append(c.getJqUi());x.append(v.getJqUi());x.append(e.getJqUi());x.append(A.getJqUi());x.append(k.getJqUi());
q.layoutCtrl(d.getJqUi(),0,0,90,23);q.layoutCtrl(l.getJqUi(),90,0,200,23);q.layoutCtrl(c.getJqUi(),0,33,90,23);q.layoutCtrl(v.getJqUi(),90,33,60,23);q.layoutCtrl(e.getJqUi(),155,33,60,23);q.layoutCtrl(A.getJqUi(),230,33,60,23);q.layoutCtrl(k.getJqUi(),295,33,60,23);a=a.getJqUi();d=new w;d.setTitle(m.get("direction","\u65b9\u5411"));c=new S;c.setText(m.get("directionVertical","\u7eb5\u5411"));e=new S;e.setText(m.get("directionHorizontal","\u6a2a\u5411"));k=new W;k.addElement(c);k.addElement(e);u(k,
c,e);k=d.getJqContainer();k.append(c.getJqUi());k.append(e.getJqUi());q.layoutCtrl(c.getJqUi(),0,0,90,23);q.layoutCtrl(e.getJqUi(),90,0,90,23);d=d.getJqUi();c=new w;c.setTitle(m.get("margin","\u9875\u8fb9\u8ddd(mm)"));e=c.getJqContainer();k=[[m.get("marginLeft","\u5de6"),b.getPageMarginLeft,b.setPageMarginLeft],[m.get("marginRight","\u53f3"),b.getPageMarginRight,b.setPageMarginRight],[m.get("marginTop","\u4e0a"),b.getPageMarginTop,b.setPageMarginTop],[m.get("marginBottom","\u4e0b"),b.getPageMarginBottom,
b.setPageMarginBottom]];l=[];for(v=0;v<k.length;v++){x=k[v][0];var B=k[v][1],I=k[v][2];A=new O;L(A,B,I);x=new M(x);x.getJqUi().css("text-align","right");B=$("<div>");B.append(x.getJqUi());B.append(A.getJqUi());q.layoutCtrl(x.getJqUi(),0,0,50,23);q.layoutCtrl(A.getJqUi(),60,0,60,23);l[v]=B;e.append(B)}q.layoutCtrl(l[0],0,30,120,23);q.layoutCtrl(l[1],200,30,120,23);q.layoutCtrl(l[2],100,0,120,23);q.layoutCtrl(l[3],100,60,120,23);c=c.getJqUi();e=new w;e.setTitle(m.get("headerfooter","\u9875\u7709/\u9875\u811a"));
k=new M(m.get("hfHeader","\u9875\u7709"));l=new Z;v=new aa(m.get("hfSetting","\u81ea\u5b9a\u4e49"));A=new M(m.get("hfFooter","\u9875\u811a"));x=new Z;B=new aa(m.get("hfSetting","\u81ea\u5b9a\u4e49"));C(l,x,v,B);I=e.getJqContainer();I.append(k.getJqUi());I.append(l.getJqUi());I.append(v.getJqUi());I.append(A.getJqUi());I.append(x.getJqUi());I.append(B.getJqUi());q.layoutCtrl(k.getJqUi(),0,0,50,23);q.layoutCtrl(l.getJqUi(),50,0,210,23);q.layoutCtrl(v.getJqUi(),260,0,60,23);q.layoutCtrl(A.getJqUi(),
0,33,50,23);q.layoutCtrl(x.getJqUi(),50,33,210,23);q.layoutCtrl(B.getJqUi(),260,33,60,23);e=e.getJqUi();k=new w;k.setTitle(m.get("zoom","\u7f29\u653e"));l=new S;l.setText(m.get("zoomRatio","\u7f29\u653e\u6bd4\u4f8b"));v=new S;v.setText(m.get("zoomFitTo","\u4e0d\u8d85\u51fa"));x=new W;x.addElement(l);x.addElement(v);A=new O;B=new O;I=new O;E(x,l,v,A,B,I);x=new M("%");var ba=new M(m.get("zoomPagesWide","\u9875\u5bbd")),ia=new M(m.get("zoomPagesTall","\u9875\u9ad8"));B=r([[B,0,60],[ba,5,null],[I,10,
60],[ia,5,null]]);I=k.getJqContainer();I.append(l.getJqUi());I.append(v.getJqUi());I.append(A.getJqUi());I.append(x.getJqUi());I.append(B);q.layoutCtrl(l.getJqUi(),0,0,90,23);q.layoutCtrl(A.getJqUi(),90,0,60,23);q.layoutCtrl(x.getJqUi(),155,0,40,23);q.layoutCtrl(v.getJqUi(),0,33,90,23);q.layoutCtrl(B,90,33,260,23);k=k.getJqUi();l=new w;l.setTitle(m.get("pagingOrder","\u5206\u9875\u987a\u5e8f"));v=new S;A=new S;x=new W;x.addElement(v);x.addElement(A);F(x,v,A);I=new M(m.get("pagingOrderRowFirst","\u5148\u884c\u540e\u5217"));
x=new M(m.get("pagingOrderColFirst","\u5148\u5217\u540e\u884c"));ba=$("<div>");ba.css("background-image",Q.getIconUrl("export","icon_export-rowfirst.png"));B=$("<div>");B.css("background-image",Q.getIconUrl("export","icon_export-colfirst.png"));I=r([[I,0,null],[ba,5,23]]);x=r([[x,0,null],[B,5,23]]);B=l.getJqContainer();B.append(v.getJqUi());B.append(I);B.append(A.getJqUi());B.append(x);q.layoutCtrl(v.getJqUi(),0,0,20,23);q.layoutCtrl(I,20,0,130,23);q.layoutCtrl(A.getJqUi(),155,0,20,23);q.layoutCtrl(x,
175,0,130,23);l=l.getJqUi();g=$("<div>");g.append(a);g.append(d);g.append(k);g.append(l);g.append(c);g.append(e);q.layoutCtrlWithLRTB(a,0,null,"45%",0,null,110);q.layoutCtrlWithLRTB(d,0,null,"45%",110,null,70);q.layoutCtrlWithLRTB(c,0,null,"45%",180,null,130);q.layoutCtrlWithLRTB(e,0,null,"45%",310,null,110);q.layoutCtrlWithLRTB(k,null,0,"45%",0,null,110);q.layoutCtrlWithLRTB(l,null,0,"45%",110,null,70)}return g};var r=function(a){for(var d=$("<div>"),c=0;c<a.length;c++){var e=a[c][0],k=a[c][1],l=
a[c][2];e=e instanceof $?e:e.getJqUi();d.append(e);e.css("position","relative");e.css("float","left");e.css("margin-left",k+"px");e.css("height","23px");l&&e.css("width",l+"px")}return d},h=function(a,d,c){var e=[new t(297,420,"A3"),new t(210,297,"A4"),new t(148,210,"A5"),new t(353,500,"B3"),new t(250,353,"B4"),new t(176,250,"B5"),new t(0,0,m.get("paperMediaCustom","\u81ea\u5b9a\u4e49"))];a.setItemModels(e);z(e,a);a.addSelectedChangedListener(function(k,l,v){l=k.getSelected();k=l.getWidth();l=l.getHeight();
0<k&&0<l&&(b.setPaperWidth(k),b.setPaperHeight(l),d.setValue(k),c.setValue(l))});d.setConstraint(100,1E3,1);d.setValue(b.getPaperWidth());d.addValueChangedListener(function(k,l,v,A){A!=O.CHANGED_BY_API&&(b.setPaperWidth(v),z(e,a))});c.setConstraint(100,1E3,1);c.setValue(b.getPaperHeight());c.addValueChangedListener(function(k,l,v,A){A!=O.CHANGED_BY_API&&(b.setPaperHeight(v),z(e,a))})},z=function(a,d){for(var c=0;c<a.length;c++){var e=a[c];if(e.getWidth()==b.getPaperWidth()&&e.getHeight()==b.getPaperHeight()){d.setSelected(e);
return}}d.setSelected(a[a.length-1])},u=function(a,d,c){d.setUserObject(f.VERITICAL);d.setChecked(b.getDirection()==f.VERITICAL);c.setUserObject(f.HORIZONTAL);c.setChecked(b.getDirection()==f.HORIZONTAL);a.addChangedListener(function(e,k){k&&b.setDirection(e.getUserObject())})},L=function(a,d,c){a.setConstraint(0,1E3,1);a.setValue(d());a.addValueChangedListener(function(e,k,l,v){v!=O.CHANGED_BY_API&&c(l)})},C=function(a,d,c,e){a.setSelected(b.getHeader());d.setSelected(b.getFooter());var k=[new p,
K([[],[m.get("hfSelectableItem1","\u7b2c&[Page]\u9875")],[]]),K([[],[m.get("hfSelectableItem2","\u7b2c&[Page]\u9875 \u5171&[PageCount]\u9875")],[]]),K([[],[m.get("hfSelectableItem3","\u6253\u5370\u65e5\u671f:&[Date]")],[]]),K([[],[m.get("hfSelectableItem4","\u6253\u5370\u65f6\u95f4:&[Time]")],[]]),K([[],[m.get("hfSelectableItem5","&[Date] &[Time]")],[]])];a.setItemModels(k,y);a.addSelectedChangedListener(function(l,v,A){b.getHeader().fromJsonObject(A.toJsonObject())});d.setItemModels(k,y);d.addSelectedChangedListener(function(l,
v,A){b.getFooter().fromJsonObject(A.toJsonObject())});c.addActionListener(function(l){l=m.get("hfHeader","\u9875\u7709");H(l,!0,b.getHeader(),function(){a.setSelected(null);a.setSelected(b.getHeader())})});e.addActionListener(function(l){l=m.get("hfFooter","\u9875\u811a");H(l,!1,b.getFooter(),function(){d.setSelected(null);d.setSelected(b.getFooter())})})},K=function(a){var d=new p;d.fromJsonObject(a);return d},y=function(a,d){return a.getLeftText()==d.getLeftText()&&a.getCenterText()==d.getCenterText()&&
a.getRightText()==d.getRightText()},H=function(a,d,c,e){var k=new P;k.setTitle(a);k.setHeaderOrFooter(d);k.setHeaderFooterModel(c);k.setConfirmedCallback(e);k.showDialog()},E=function(a,d,c,e,k,l){d.setUserObject(f.SCALING);d.setChecked(b.getZoomType()==f.SCALING);c.setUserObject(f.ADJUSTMENT);c.setChecked(b.getZoomType()==f.ADJUSTMENT);a.addChangedListener(function(v,A){A&&b.setZoomType(v.getUserObject())});e.setConstraint(10,400,1);e.setValue(b.getScaling());e.addValueChangedListener(function(v,
A,x,B){B!=O.CHANGED_BY_API&&(b.setScaling(x),b.setZoomType(f.SCALING),d.setChecked(!0))});k.setCustomPainter(J);k.setConstraint(0,32767,1);k.setValue(b.getZoomOutPageWide());k.addValueChangedListener(function(v,A,x,B){B!=O.CHANGED_BY_API&&(b.setZoomOutPageWide(x),b.setZoomType(f.ADJUSTMENT),c.setChecked(!0))});l.setCustomPainter(J);l.setConstraint(0,32767,1);l.setValue(b.getZoomOutPageTall());l.addValueChangedListener(function(v,A,x,B){B!=O.CHANGED_BY_API&&(b.setZoomOutPageTall(x),b.setZoomType(f.ADJUSTMENT),
c.setChecked(!0))})},J=function(a){return 0<a?a:""},F=function(a,d,c){d.setUserObject(!0);d.setChecked(b.isPagingRowFirst());c.setUserObject(!1);c.setChecked(!b.isPagingRowFirst());a.addChangedListener(function(e,k){k&&b.setPagingRowFirst(e.getUserObject())})}}function t(b,g,r){this.getWidth=function(){return b};this.getHeight=function(){return g};this.toString=function(){return r}}function w(){var b,g=$("<div>"),r=$("<div>");this.setTitle=function(h){g.text(h)};this.getJqUi=function(){b||(g.css("color",
"#333"),g.css("line-height","24px"),g.css("font-size","14px"),g.css("border-bottom","solid 1px #d7dadd"),r.css("font-size","12px"),b=$("<div>"),b.append(g),b.append(r),q.layoutCtrlWithLRTB(g,0,0,null,0,null,24),q.layoutCtrlWithLRTB(r,10,10,null,34,10,null));return b};this.getJqContainer=function(){return r}}function G(){var b=this,g,r,h,z=0,u=0,L=function(){if(!g){g=new fa;var a=C();a.on("focus",H);a.on("blur",E);if(R.isIEBrowser())a.on("beforedeactivate",y)}return g},C=function(){return L().getJqUi().find("textarea")};
this.getJqUi=function(){return L().getJqUi()};this.requestFocus=function(){g.requestFocus()};this.setFocusListener=function(a){h=a};this.setAlign=function(a){C().css("text-align",a);r=m.get("left"==a?"hfSettingLeftPart":"right"==a?"hfSettingRightPart":"hfSettingCenterPart");J(!1)};this.setValue=function(a){L().setText(a);F(a)};this.getValue=function(){return L().getText()};this.insert=function(a){R.isIEBrowser()?u=z=K(a,z,u):K(a,C()[0].selectionStart,C()[0].selectionEnd);g.requestFocus()};var K=function(a,
d,c){var e=b.getValue();if("number"!=typeof d||"number"!=typeof c)c=d=e.length;b.setValue(e.substring(0,d)+a+e.substring(c,e.length));a=d+a.length;C()[0].setSelectionRange(a,a);return a},y=function(a){z=C()[0].selectionStart;u=C()[0].selectionEnd},H=function(a){J(!0);F(!0);h(b)},E=function(a){J(!1);F(b.getValue())},J=function(a){a?C().attr("placeholder",m.get("hfSettingInsertingTips","\u8bf7\u8f93\u5165\u5185\u5bb9")):C().attr("placeholder",r)},F=function(a){a?C().css("line-height",""):C().css("line-height",
"40px")}}function T(){var b,g=new G,r=new G,h=new G,z;this.setModelToModify=function(y){b=y;g.setValue(b.getLeftText());r.setValue(b.getCenterText());h.setValue(b.getRightText());z=b.getLeftText()?g:b.getCenterText()?r:b.getRightText()?h:g};this.acceptModified=function(){b.setLeftText(g.getValue());b.setCenterText(r.getValue());b.setRightText(h.getValue())};this.createJqUi=function(y){var H=L();y=u(y);var E=$("<div>");E.append(H);E.append(y);q.layoutCtrlWithLRTB(H,0,0,null,0,null,24);q.layoutCtrlWithLRTB(y,
0,0,null,32,null,112);setTimeout(function(){z.requestFocus()},0);return E};var u=function(y){g.setAlign("left");g.setFocusListener(C);r.setAlign("center");r.setFocusListener(C);h.setAlign("right");h.setFocusListener(C);var H=g.getJqUi(),E=r.getJqUi(),J=h.getJqUi(),F=Q.getIconUrl("export",y?"icon_export-bgheader.png":"icon_export-bgfooter.png"),a=$("<div>");a.css("background-image",F);a.css("background-repeat","repeat-x");a.append(H);a.append(E);a.append(J);F=y?8:null;y=y?null:8;q.layoutCtrlWithLRTB(H,
8,null,"30%",F,y,44);q.layoutCtrlWithLRTB(E,"35%",null,"30%",F,y,44);q.layoutCtrlWithLRTB(J,null,8,"30%",F,y,44);return a},L=function(){var y=$("<div>"),H=0,E=new M(m.get("hfSettingButtonsCaption","\u63d2\u5165"));q.layoutCtrl(E.getJqUi(),H,0,60,23);y.append(E.getJqUi());H=60;E=[["&[Page]",m.get("hfSettingBtnPage","\u9875\u7801")],["&[PageCount]",m.get("hfSettingBtnPageCount","\u603b\u9875\u6570")],["&[Date]",m.get("hfSettingBtnDate","\u65e5\u671f")],["&[Time]",m.get("hfSettingBtnTime","\u65f6\u95f4")]];
for(var J=0;J<E.length;J++){var F=E[J][0],a=new aa(E[J][1]);a.setUserObject(F);a.addActionListener(K);y.append(a.getJqUi());q.layoutCtrl(a.getJqUi(),H,0,72,23);H+=72}return y},C=function(y){z=y},K=function(y){y=y.getUserObject();z.insert(y)}}function P(){U.call(this);var b=this,g=this.protectedMethod,r,h,z;(function(){b.setSize(640,264);g.setSelectable(!0);g.setContentPaneCreator(function(){return h.createJqUi(r)});g.setClosingAction(function(u){u&&(h.acceptModified(),z())})})();this.setTitle=function(u){g.setTitle(u)};
this.setHeaderOrFooter=function(u){r=u};this.setHeaderFooterModel=function(u){h=new T;h.setModelToModify(u)};this.setConfirmedCallback=function(u){z=u}}function V(){U.call(this);var b=this,g=this.protectedMethod,r,h,z;(function(){b.setSize(860,540);g.setContentPaneCreator(function(){h=new n;h.setModel(r);return h.getJqUi()});g.setClosingChecker(function(){var u=h.checkInvalid();return u?(g.getMessageCurtain().showPrompt(u),!1):!0});g.setClosingAction(function(u){u&&z(r)})})();this.setTitle=function(u){g.setTitle(u)};
this.setSettingModel=function(u){r=u};this.setConfirmer=function(u){z=u}}function X(){var b=!0;this.setVerticalMerged=function(g){b=g};this.isVerticalMerged=function(){return b};this.toJsonObject=function(){var g={};g.isMergeExport=b;return g};this.fromJsonObject=function(g){b=g.isMergeExport}}function ca(){U.call(this);var b=this,g=this.protectedMethod,r,h,z;(function(){b.setSize(360,180);g.setContentPaneCreator(function(){h=new da;h.setModel(r);return h.getJqUi()});g.setClosingAction(function(u){u&&
z(r)})})();this.setTitle=function(u){g.setTitle(u)};this.setConfigModel=function(u){r=u};this.setConfirmer=function(u){z=u}}function da(){var b,g;this.setModel=function(h){b=h};this.getJqUi=function(){g||r();return g};var r=function(){g=$("<div>");var h=new ha;h.setText(m.get("keepVerticalMerged","\u4fdd\u6301\u5408\u5e76\u884c\u72b6\u6001"));h.setChecked(b.isVerticalMerged());h.addCheckedListener(function(z,u){u&&b.setVerticalMerged(z.isChecked())});h=h.getJqUi();h.appendTo(g);q.layoutCtrlWithLRTB(h,
0,0,null,0,null,23)}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.extreport&&(com.kingdee.bos.extreport={});"undefined"==typeof com.kingdee.bos.extreport.runtime&&(com.kingdee.bos.extreport.runtime={});"undefined"==typeof com.kingdee.bos.extreport.runtime.exportmanage&&(com.kingdee.bos.extreport.runtime.exportmanage={});var Y=com.kingdee.bos.extreport.runtime.exportmanage,
R,q,m,Q,N,U,S,W,Z,M,aa,ha,O,fa,ea,D;(function(){var b=com.kingdee.bos.qing.common;R=b.Util;q=b.DomUtil;b=com.kingdee.bos.qing.framework.common;m=b.MultilanguageManager.createPackageAccessor(Y);Q=b.Resource;N=b.RemoteFramework;b=com.kingdee.bos.qing.ui.component;U=b.AbstractModalDialog;S=b.RadioButton;W=b.RadioButtonGroup;Z=b.ComboBox;M=b.Label;aa=b.WorkButton;ha=b.CheckBox;O=b.Spinner;fa=b.TextArea;b=com.kingdee.bos.qing.longer.ui;ea=b.ExportHelper;b=com.kingdee.bos.qing.behavior;D=b.BehaviorManager})();
Y.ExportManage=function(){var b,g,r,h;this.setDependentApi=function(a){b=a};this.setRptName=function(a){h=a};this.setMenuStateUpdater=function(a,d){g=a;r=d};this.exportExcel2007=function(){C("excel2007")};this.exportExcel=function(){C("excel")};this.exportPng=function(){g(!0);F("PNG",".png")};this.exportPdf=function(){var a=K(),d=z();a=u(a,d);var c=new V;c.setTitle(m.get("exportPdfDialogTitle","\u5bfc\u51fa\u4e3aPDF"));c.setSettingModel(a);c.setConfirmer(function(e){e=L(e,d);y(e);g(!0);F("pdf",".pdf")});
c.showDialog()};this.printSetting=function(){var a=K(),d=z();a=u(a,d);var c=new V;c.setTitle(m.get("printSettingDialogTitle","\u6253\u5370\u8bbe\u7f6e"));c.setSettingModel(a);c.setConfirmer(function(e){e=L(e,d);y(e)});c.showDialog()};this.printPreview=function(){r(!0);var a=K(),d=z();a=u(a,d);y(a);J()};var z=function(){var a,d=b.isPreview,c=b.isHyperlink,e=b.currentUserId;b.publishId?a=b.publishId+"_"+e:b.snapId?a=b.snapId:b.extReportId&&d?a=b.extReportId:b.extReportId&&c&&(a=b.extReportId);return a+
"rpt_setup_local"},u=function(a,d){d=localStorage.getItem(d);a||(a=new f);d&&d&&a.fromJsonObject(JSON.parse(d));return a},L=function(a,d){var c=a.toJsonObject();c.createTime=new Date;try{localStorage.setItem(d,JSON.stringify(c))}catch(k){if(k.code===f.QUOTA_EXCEEDED_ERR_CODE){for(itemKey in window.localStorage)if(window.localStorage.hasOwnProperty(itemKey)&&itemKey.includes("rpt_setup_local")){var e=window.localStorage.getItem(itemKey);864E5<Math.abs(c.createTime-new Date(JSON.parse(e).createTime))&&
localStorage.removeItem(itemKey)}localStorage.setItem(d,JSON.stringify(c))}}return a},C=function(a){var d=H();!d&&(d=new X);var c=new ca;c.setTitle(m.get("exportExcelDialogTitle","\u5bfc\u51fa\u4e3aExcel"));c.setConfigModel(d);c.setConfirmer(function(e){var k=e.toJsonObject();k=JSON.stringify(k);b.setExportConfig(k);b.setMegerExport(e.isVerticalMerged());g(!0);"excel"==a?F("excel",".xls"):"excel2007"==a&&F("excel2007",".xlsx")});c.showDialog()},K=function(){var a=b.getExportSetting();if(a){a=JSON.parse(a);
var d=new f;d.fromJsonObject(a);return d}return null},y=function(a){a=a.toJsonObject();a=JSON.stringify(a);b.setExportSetting(a)},H=function(){var a=b.getExportConfig();if(a){a=JSON.parse(a);var d=new X;d.fromJsonObject(a);return d}return null},E=function(a){var d=R.formatDate("yyyyMMdd_HHmmss");return null!=h&&""!=h?h+"-"+d+a:"ExtReport-"+d+a},J=function(){var a=(new Date).getTime(),d=E(".pdf"),c=b.createJsonModelWrapper(),e=b.createFacade(function(k){if(b.publishId){var l=R.createUUID();D.initAccessRecordParams(b.publishId,
l,D.SourceType.QING_PUBLISH,D.AppType.QING_RPT);D.recordResourceOperation(D.OperationType.QING_PRINT)}else"A"==b.snapGroupType&&(l=R.createUUID(),D.initAccessRecordParams(b.snapId,l,D.SourceType.QING_SNAPSHOT,D.AppType.QING_RPT),D.recordResourceOperation(D.OperationType.QING_PRINT));r(!1);l=m.get("printPreviewTabbedTitle","\u6253\u5370\u9884\u89c8");N.previewFile(l,d,k);D.interestInBehavior(D.PRINT_PREVIEW,1,(new Date).getTime()-a)},function(k,l){r(!1);return ea.facadeErrorHandler(k,l)},void 0);e.setShowBlocking(!1);
e.exportToFile("pdf",c)},F=function(a,d){var c=(new Date).getTime(),e=E(d);d=b.createJsonModelWrapper();var k=b.createFacade(function(l){if(b.publishId){var v=R.createUUID();D.initAccessRecordParams(b.publishId,v,D.SourceType.QING_PUBLISH,D.AppType.QING_RPT);D.recordResourceOperation(D.OperationType.QING_EXPORT)}else"A"==b.snapGroupType&&(v=R.createUUID(),D.initAccessRecordParams(b.snapId,v,D.SourceType.QING_SNAPSHOT,D.AppType.QING_RPT),D.recordResourceOperation(D.OperationType.QING_EXPORT));g(!1);
N.downloadFile(e,l);D.interestInBehavior(D.EXPORT_TYPE,a,(new Date).getTime()-c)},function(l,v){g(!1);return ea.facadeErrorHandler(l,v)},void 0);k.setShowBlocking(!1);k.exportToFile(a,d)}};f.SCALING="SCALING";f.ADJUSTMENT="ADJUSTMENT";f.HORIZONTAL="HORIZONTAL";f.VERITICAL="VERITICAL";f.QUOTA_EXCEEDED_ERR_CODE=22})();
//qingVersionTag: 20250324