var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,a,h){c instanceof String&&(c=String(c));for(var d=c.length,g=0;g<d;g++){var k=c[g];if(a.call(h,k,g,c))return{i:g,v:k}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,h){if(c==Array.prototype||c==Object.prototype)return c;c[a]=h.value;return c};$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<c.length;++a){var h=c[a];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(c,a){var h=$jscomp.propertyToPolyfillSymbol[a];if(null==h)return c[a];h=c[h];return void 0!==h?h:c[a]};
$jscomp.polyfill=function(c,a,h,d){a&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(c,a,h,d):$jscomp.polyfillUnisolated(c,a,h,d))};$jscomp.polyfillUnisolated=function(c,a,h,d){h=$jscomp.global;c=c.split(".");for(d=0;d<c.length-1;d++){var g=c[d];if(!(g in h))return;h=h[g]}c=c[c.length-1];d=h[c];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:a})};
$jscomp.polyfillIsolated=function(c,a,h,d){var g=c.split(".");c=1===g.length;d=g[0];d=!c&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<g.length-1;k++){var f=g[k];if(!(f in d))return;d=d[f]}g=g[g.length-1];h=$jscomp.IS_SYMBOL_NATIVE&&"es6"===h?d[g]:null;a=a(h);null!=a&&(c?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:a}):a!==h&&(void 0===$jscomp.propertyToPolyfillSymbol[g]&&(h=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+h+"$"+g),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[g],{configurable:!0,writable:!0,value:a})))};$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(a,h){return $jscomp.findInternal(this,a,h).v}},"es6","es3");
function KTColumn(c,a){var h=this,d=c,g=a?a:"col"+ ++KTColumn.iFlowId,k=72,f,n,l=!1,t;this.setKey=function(v){g=v};this.getKey=function(){return g};this.setWidth=function(v){if(k!=v){var J=k;k=v;d(this,KTColumn.WIDTH,k,J)}};this.getWidth=function(){return k};this.$innerDestroy=function(){this.setStyle(null);this.setBorder(null);d=null};this.setStyle=function(v){v!=f&&(null!=f&&f.removeChangeListener(E),f=v,null!=f&&f.addChangeListener(E))};this.getStyle=function(){return f};this.setBorder=function(v){v!=
n&&(null!=n&&n.removeChangeListener(E),n=v,null!=n&&n.addChangeListener(E))};this.getBorder=function(){return n};var E=function(v,J,y,w){d(h,J,y,w)};this.setHide=function(v){l!=v&&(l=v,d(h,KTColumn.HIDE,l,!l))};this.isHide=function(){return l};this.setUserObject=function(v){t=v};this.getUserObject=function(){return t}}KTColumn.WIDTH="width";KTColumn.HIDE="columnHide";KTColumn.iFlowId=100;
function KTRow(c,a){var h=this,d=a,g="row"+ ++KTRow.iFlowId,k=20,f=[],n,l,t=!1,E,v=!1;this.getKey=function(){return g};this.setHeight=function(w){k!=w&&(k=w,d(this,KTRow.HEIGHT,k,w))};this.getHeight=function(){return k};this.getCell=function(w,B){var H=f[w];B||H||(H=new KTCell(J),f[w]=H);return H};this.getCellForDraw=function(w){return f[w]};this.setStyle=function(w){w!=n&&(null!=n&&n.removeChangeListener(y),n=w,null!=n&&n.addChangeListener(y))};this.getStyle=function(){return n};this.setBorder=function(w){w!=
l&&(null!=l&&l.removeChangeListener(y),l=w,null!=l&&l.addChangeListener(y))};this.getBorder=function(){return l};this.$innerDestroy=function(){this.setStyle(null);this.setBorder(null);d=null;for(var w=0;w<f.length;w++){var B=f[w];B&&B.$innerDestroy()}f=null};this.$innerInsertCell=function(w){f.splice(w,0,null)};this.$innerRemoveCell=function(w){var B=f[w];B&&B.$innerDestroy();f.splice(w,1)};var J=function(w,B,H,I){var P;for(P=0;P<f.length&&f[P]!=w;P++);w=new KTCell.Path(h,P,w);d(w,B,H,I)},y=function(w,
B,H,I){d(h,B,H,I)};this.setHide=function(w){t!=w&&(t=w,d(h,KTRow.HIDE,t,!t))};this.isHide=function(){return t};this.setUserObject=function(w){E=w};this.getUserObject=function(){return E};this.clearAsSkeleton=function(){for(var w=0;w<f.length;w++){var B=f[w];B&&B.$innerDestroy()}f=[];v=!0};this.isSkeleton=function(){return v};this.rescueSkeleton=function(){v=!1}}KTRow.HEIGHT="height";KTRow.HIDE="rowHide";KTRow.iFlowId=0;
function KTCell(c){var a=this,h=c,d,g,k,f,n;this.setValue=function(E){if(d!=E){var v=d;d=E;"undefined"!=typeof v&&h(this,KTCell.VALUE,d,v)}};this.getValue=function(){return d};this.setUserObject=function(E){n=E};this.getUserObject=function(){return n};this.$innerDestroy=function(){this.setStyle(null);this.setBorder(null);h=null};this.setStyle=function(E){E!=g&&(null!=g&&g.removeChangeListener(l),g=E,null!=g&&g.addChangeListener(l))};this.getStyle=function(){return g};this.setBorder=function(E){E!=
k&&(null!=k&&k.removeChangeListener(l),k=E,null!=k&&k.addChangeListener(l))};this.getBorder=function(){return k};var l=function(E,v,J,y){h(a,v,J,y)};this.setTreeModel=function(E){f&&f.$innerBindChangeListener(null);if(f=E)f.$innerBindChangeListener(t),h(a,KTCell.TREE_EXPANDING)};this.getTreeModel=function(){return f};var t=function(E){E==KTCellTreeModel.EXPANDED&&h(a,KTCell.TREE_EXPANDING)}}KTCell.VALUE="value";KTCell.TREE_EXPANDING="treeExpanding";
KTCell.Path=function(c,a,h){var d,g;this.$innerSetInfo=function(k,f){d=k;g=f};this.getRowIndex=function(){return d};this.getColIndex=function(){return a};this.getRow=function(){return c};this.getCol=function(){return g};this.getCell=function(){return h}};
function KTAbstractStyle(){var c=null,a=[],h=!0;this.setChangeListenerSilence=function(g){h=g};this.$innerDirty=function(g,k,f,n){c=null;if(!h)for(var l=0;l<a.length;l++)a[l](g,k,f,n)};this.addChangeListener=function(g){h||0>d(g)&&a.push(g)};this.removeChangeListener=function(g){g=d(g);0<=g&&a.splice(g,1)};var d=function(g){for(var k=0;k<a.length;k++)if(a[k]==g)return k;return-1};this.copy=function(){throw Error("Override me.");};this.toCssString=function(){null==c&&(c=this.protectedCreateCssString());
return c};this.protectedCreateCssString=function(){throw Error("Override me.");};KTAbstractStyle.createCssItem=function(g,k,f){var n=typeof k;return"undefined"==n||null==k?"":"string"==n&&0<k.indexOf(" ")?g+':"'+k+'";':g+":"+k+(f?f:"")+";"};this.toString=function(){return this.toCssString()}}
function KTStyle(){KTAbstractStyle.call(this);var c=this,a,h,d,g,k,f,n,l,t,E,v,J,y,w,B,H,I,P=function(u){c.$innerDirty(c,u?u:KTStyle.STYLE_COMMON)};this.setFontName=function(u){a=u;P()};this.getFontName=function(){return a};this.setFontSize=function(u){h=u;P()};this.getFontSize=function(){return h};this.setBold=function(u){d=u;P()};this.isBold=function(){return d};this.setItalic=function(u){g=u;P()};this.getItalic=function(){return g};this.setUnderLine=function(u){k=u;P()};this.isUnderLine=function(){return k};
this.setLineThrough=function(u){f=u;P()};this.isLineThrough=function(){return f};this.setColor=function(u){n=u;P()};this.getColor=function(){return n};this.setBackgroundColor=function(u){l=u;P()};this.getBackgroundColor=function(){return l};this.setTextAlign=function(u){t=u;P()};this.getTextAlign=function(){return t};this.setVerticalAlign=function(u){E=u;P(KTStyle.STYLE_TEXT_SPECIAL)};this.getVerticalAlign=function(){return E};this.setWrapText=function(u){v=u;P(KTStyle.STYLE_TEXT_SPECIAL)};this.isWrapText=
function(){return v};this.setShrinkText=function(u){B=u;P(KTStyle.STYLE_TEXT_SPECIAL)};this.isShrinkText=function(){return B};this.setVerticalText=function(u){w=u;P(KTStyle.STYLE_TEXT_SPECIAL)};this.isVerticalText=function(){return w};this.setIndent=function(u){J=u;P()};this.getIndent=function(){return J};this.setRotation=function(u){y=u;P()};this.getRotation=function(){return y};this.setCursor=function(u){H=u};this.getCursor=function(){return H};this.setFontUnit=function(u){I=u};this.getFontUnit=
function(){return I};this.getFontSizeWithUnit=function(){return h||0==h?h+(I?I:KTStyle.DEFAULT_FONT_UNIT):h};this.copy=function(){var u=new KTStyle;u.setFontName(a);u.setFontSize(h);u.setBold(d);u.setItalic(g);u.setUnderLine(k);u.setLineThrough(f);u.setColor(n);u.setBackgroundColor(l);u.setTextAlign(t);u.setVerticalAlign(E);u.setWrapText(v);u.setVerticalText(w);u.setCursor(H);u.setFontUnit(I);return u};this.protectedCreateCssString=function(){var u=""+KTAbstractStyle.createCssItem("font-family",a);
u+=KTAbstractStyle.createCssItem("font-size",h,I?I:KTStyle.DEFAULT_FONT_UNIT);1==d?u+=KTAbstractStyle.createCssItem("font-weight","bold"):0==d&&(u+=KTAbstractStyle.createCssItem("font-weight","normal"));1==g?u+=KTAbstractStyle.createCssItem("font-style","italic"):0==g&&(u+=KTAbstractStyle.createCssItem("font-style","normal"));f&&k?u+=KTAbstractStyle.createCssItem("text-decoration","underline line-through"):k?u+=KTAbstractStyle.createCssItem("text-decoration","underline"):f&&(u+=KTAbstractStyle.createCssItem("text-decoration",
"line-through"));u+=KTAbstractStyle.createCssItem("color",n);u+=KTAbstractStyle.createCssItem("background-color",l);u+=KTAbstractStyle.createCssItem("text-align",t);u+=KTAbstractStyle.createCssItem("vertical-align",E);!0===v?(u+=KTAbstractStyle.createCssItem("white-space","pre-wrap"),u+=KTAbstractStyle.createCssItem("word-break","break-word"),u+=KTAbstractStyle.createCssItem("*white-space","pre"),u+=KTAbstractStyle.createCssItem("*word-wrap","break-word")):!1===v&&(u+=KTAbstractStyle.createCssItem("white-space",
"nowrap"));return u}}KTStyle.CSS_ID_PREFIXE="style";KTStyle.STYLE_COMMON="styleCommon";KTStyle.STYLE_TEXT_SPECIAL="styleTextSpecial";KTStyle.DEFAULT_FONT_UNIT="pt";
function KTBorderStyle(){KTAbstractStyle.call(this);var c=this,a=Array(4),h=Array(4),d=Array(4),g=function(k){c.$innerDirty(c,k?k:KTBorderStyle.BORDER_COMMON)};this.setTopBorderPen=function(k){a[0]=k;g()};this.getTopBorderPen=function(){return a[0]};this.setRightBorderPen=function(k){a[1]=k;g()};this.getRightBorderPen=function(){return a[1]};this.setBottomBorderPen=function(k){a[2]=k;g()};this.getBottomBorderPen=function(){return a[2]};this.setLeftBorderPen=function(k){a[3]=k;g()};this.getLeftBorderPen=
function(){return a[3]};this.setBorderPen=function(k){for(var f=0;4>f;f++)a[f]=k;g()};this.getBorderPen=function(){return a[0]==a[1]&&a[0]==a[2]&&a[0]==a[3]?a[0]:null};this.setTopBorderWidth=function(k){h[0]=k;g(KTBorderStyle.BORDER_WIDTH)};this.getTopBorderWidth=function(){return h[0]};this.setRightBorderWidth=function(k){h[1]=k;g(KTBorderStyle.BORDER_WIDTH)};this.getRightBorderWidth=function(){return h[1]};this.setBottomBorderWidth=function(k){h[2]=k;g(KTBorderStyle.BORDER_WIDTH)};this.getBottomBorderWidth=
function(){return h[2]};this.setLeftBorderWidth=function(k){h[3]=k;g(KTBorderStyle.BORDER_WIDTH)};this.getLeftBorderWidth=function(){return h[3]};this.setBorderWidth=function(k){for(var f=0;4>f;f++)h[f]=k;g(KTBorderStyle.BORDER_WIDTH)};this.getBorderWidth=function(){return h[0]==h[1]&&h[0]==h[2]&&h[0]==h[3]?h[0]:null};this.setTopBorderColor=function(k){d[0]=k;g()};this.getTopBorderColor=function(){return d[0]};this.setRightBorderColor=function(k){d[1]=k;g()};this.getRightBorderColor=function(){return d[1]};
this.setBottomBorderColor=function(k){d[2]=k;g()};this.getBottomBorderColor=function(){return d[2]};this.setLeftBorderColor=function(k){d[3]=k;g()};this.getLeftBorderColor=function(){return d[3]};this.setBorderColor=function(k){for(var f=0;4>f;f++)d[f]=k;g()};this.getBorderColor=function(){return d[0]==d[1]&&d[0]==d[2]&&d[0]==d[3]?d[0]:null};this.copy=function(){var k=new KTBorderStyle;k.setTopBorderPen(this.getTopBorderPen());k.setRightBorderPen(this.getRightBorderPen());k.setBottomBorderPen(this.getBottomBorderPen());
k.setLeftBorderPen(this.getLeftBorderPen());k.setTopBorderWidth(this.getTopBorderWidth());k.setRightBorderWidth(this.getRightBorderWidth());k.setBottomBorderWidth(this.getBottomBorderWidth());k.setLeftBorderWidth(this.getLeftBorderWidth());k.setTopBorderColor(this.getTopBorderColor());k.setRightBorderColor(this.getRightBorderColor());k.setBottomBorderColor(this.getBottomBorderColor());k.setLeftBorderColor(this.getLeftBorderColor());return k};this.protectedCreateCssString=function(){var k="",f=this.getBorderPen();
null==f?(k+=KTAbstractStyle.createCssItem("border-top-style",this.getTopBorderPen()),k+=KTAbstractStyle.createCssItem("border-right-style",this.getRightBorderPen()),k+=KTAbstractStyle.createCssItem("border-bottom-style",this.getBottomBorderPen()),k+=KTAbstractStyle.createCssItem("border-left-style",this.getLeftBorderPen())):k+=KTAbstractStyle.createCssItem("border-style",f);f=this.getBorderWidth();null==f?(k+=KTAbstractStyle.createCssItem("border-top-width",this.getTopBorderWidth(),"px"),k+=KTAbstractStyle.createCssItem("border-right-width",
this.getRightBorderWidth(),"px"),k+=KTAbstractStyle.createCssItem("border-bottom-width",this.getBottomBorderWidth(),"px"),k+=KTAbstractStyle.createCssItem("border-left-width",this.getLeftBorderWidth(),"px")):k+=KTAbstractStyle.createCssItem("border-width",f,"px");f=this.getBorderColor();null==f?(k+=KTAbstractStyle.createCssItem("border-top-color",this.getTopBorderColor()),k+=KTAbstractStyle.createCssItem("border-right-color",this.getRightBorderColor()),k+=KTAbstractStyle.createCssItem("border-bottom-color",
this.getBottomBorderColor()),k+=KTAbstractStyle.createCssItem("border-left-color",this.getLeftBorderColor())):k+=KTAbstractStyle.createCssItem("border-color",f);return k}}KTBorderStyle.CSS_ID_PREFIXE="border";KTBorderStyle.BORDER_COMMON="borderCommon";KTBorderStyle.BORDER_WIDTH="borderWidth";
function KTStyleManager(){var c=new KTStyleManager.MultiMaps,a=function(h,d){d=c.getMap(d);var g=d[h];if(!g){if(h instanceof KTStyle)g=KTStyle.CSS_ID_PREFIXE;else if(h instanceof KTBorderStyle)g=KTBorderStyle.CSS_ID_PREFIXE;else throw Error("New type, modify here.");g+=++KTStyleManager.iStyleFlowId;g=[h,g];d[h]=g}return g};this.getShareStyle=function(h,d){return a(h,d)[0]};this.getShareStyleId=function(h,d){return a(h,d)[1]}}KTStyleManager.iStyleFlowId=0;KTStyleManager.PRIORITY_TABLE=0;
KTStyleManager.PRIORITY_ROW=1;KTStyleManager.PRIORITY_COLUMN=2;KTStyleManager.PRIORITY_CELL=3;KTStyleManager.MultiMaps=function(){var c=[];this.getMap=function(a){var h=c[a];h||(h={},c[a]=h);return h}};
function KTSelectionModel(c){var a=this,h=KTSelectionModel.MODE_NONE,d=KTSelectionModel.POLICY_CELL,g=[],k=new KTListenerProxy;this.setMode=function(f){h=f};this.getMode=function(){return h};this.setPolicy=function(f){d=f};this.getPolicy=function(){return d};this.isPolicySetting=function(f){return(d&f)==f};this.addChangeListener=function(f){k.addListener(KTSelectionModel.CHANGE_ADD,f);k.addListener(KTSelectionModel.CHANGE_REMOVE,f)};this.removeChangeListener=function(f){k.removeListener(KTSelectionModel.CHANGE_ADD,
f);k.removeListener(KTSelectionModel.CHANGE_REMOVE,f)};this.addSelected=function(f){if(!(f instanceof KTSelectionModel.Target))throw Error("Illegal argument.");g.push(f);k.fireListener(KTSelectionModel.CHANGE_ADD,[f])};this.appendSelected=function(f){if(!(f instanceof KTSelectionModel.Target))throw Error("Illegal argument.");if(this.hasSelected()){var n=this.getSelected(),l=a.parseBlockRange(f),t=a.parseBlockRange(n),E=Math.min(Math.min(Math.min(l[0],l[2]),t[0]),t[2]),v=Math.min(Math.min(Math.min(l[1],
l[3]),t[1]),t[3]),J=Math.max(Math.max(Math.max(l[0],l[2]),t[0]),t[2]);l=Math.max(Math.max(Math.max(l[1],l[3]),t[1]),t[3]);if(f.isSingleRow())v=E==J?a.createRowTarget(E):new KTSelectionModel.Target(Math.min(E,J),-1,Math.max(E,J));else if(f.isSingleColumn())v=v==l?a.createColumnTarget(v):new KTSelectionModel.Target(-1,Math.min(v,l),null,Math.max(v,l));else if(a.isPolicySetting(KTSelectionModel.POLICY_BLOCK))v=a.createBlockTarget(E,v,J,l);else{for(n=E;n<=J;n++)for(f=v;f<=l;f++)E=a.createCellTarget(n,
f),a.isContains(E)||a.addSelected(E);return}a.removeSelected(n);a.addSelected(v)}else a.addSelected(f)};this.removeSelected=function(f){for(var n=g.length-1;0<=n;n--){var l=g[n];if(l.equals(f))return g.splice(n,1),k.fireListener(KTSelectionModel.CHANGE_REMOVE,[l]),!0}return!1};this.removeAllSelecteds=function(){var f=g.slice(0);g=[];k.fireListener(KTSelectionModel.CHANGE_REMOVE,f)};this.setSelected=function(f){this.hasSelected()&&this.removeAllSelecteds();this.addSelected(f)};this.getSelecteds=function(){return g.concat()};
this.getSelected=function(){return this.hasSelected()?g[g.length-1]:null};this.hasSelected=function(){return 0<g.length};this.isSingleSelected=function(){return 1==g.length};this.isContains=function(f){for(var n=0;n<g.length;n++)if(g[n].equals(f))return!0;return!1};this.createCellTarget=function(f,n){var l=c.searchMergeBlock(f,n);return l?new KTSelectionModel.Target(l.getRowIdxFrom(),l.getColIdxFrom(),l.getRowIdxTo(),l.getColIdxTo()):new KTSelectionModel.Target(f,n)};this.createRowTarget=function(f){return KTSelectionModel.Target.createRow(f,
-1)};this.createColumnTarget=function(f){return KTSelectionModel.Target.createColumn(-1,f)};this.createBlockTarget=function(f,n,l,t){return f==l&&n==t?a.createCellTarget(f,n):new KTSelectionModel.Target(Math.min(f,l),Math.min(n,t),Math.max(f,l),Math.max(n,t))};this.parseBlockRange=function(f){var n=f.getRowIdx(),l=f.getColIdx(),t=f.getEndRowIdx(),E=f.getEndColIdx();if(f.isSingleCell())t=n,E=l;else if(f.isSingleRow()||f.isRows())f.isSingleRow()&&(t=n),l=0,E=c.getColumnsCount()-1;else if(f.isSingleColumn()||
f.isColumns())f.isSingleColumn()&&(E=l),n=0,t=c.getRowsCount()-1;return[n,l,t,E]}}KTSelectionModel.MODE_NONE="selection_mode_none";KTSelectionModel.MODE_SINGLE="selection_mode_single";KTSelectionModel.MODE_MULTI="selection_mode_multi";KTSelectionModel.POLICY_CELL=1;KTSelectionModel.POLICY_BLOCK=2;KTSelectionModel.POLICY_ROW=4;KTSelectionModel.POLICY_COLUMN=8;KTSelectionModel.CHANGE_ADD="selectionChange-add";KTSelectionModel.CHANGE_REMOVE="selectionChange-remove";
KTSelectionModel.Target=function(c,a,h,d){var g=h||0==h?h:null,k=d||0==d?d:null;this.getRowIdx=function(){return c};this.getColIdx=function(){return a};this.getEndRowIdx=function(){return g};this.getEndColIdx=function(){return k};this.equals=function(f){return this.getRowIdx()==f.getRowIdx()&&this.getColIdx()==f.getColIdx()&&this.getEndRowIdx()==f.getEndRowIdx()&&this.getEndColIdx()==f.getEndColIdx()};this.toString=function(){return c+","+a+"~"+g+","+k};this.isSingleCell=function(){return null==g&&
null==k&&-1!=c&&-1!=a};this.isSingleRow=function(){return null==g&&-1==a};this.isSingleColumn=function(){return-1==c&&null==k};this.isBlock=function(){return null!=g&&-1!=c&&null!=k&&-1!=a};this.isRows=function(){return null!=g&&g!=c&&-1==a};this.isColumns=function(){return-1==c&&null!=k&&k!=a}};KTSelectionModel.Target.createRow=function(c){return new KTSelectionModel.Target(c,-1)};KTSelectionModel.Target.createColumn=function(c){return new KTSelectionModel.Target(-1,c)};
function KTMergeBlock(c,a,h,d){var g=c,k=a,f=h,n=d;this.setRowIdxFrom=function(l){g=l};this.getRowIdxFrom=function(){return g};this.setRowIdxTo=function(l){k=l};this.getRowIdxTo=function(){return k};this.setColIdxFrom=function(l){f=l};this.getColIdxFrom=function(){return f};this.setColIdxTo=function(l){n=l};this.getColIdxTo=function(){return n};this.isInvalid=function(){return g>a||h>d||g==a&&f==d};this.equals=function(l){return l instanceof KTMergeBlock?l.getRowIdxFrom()==g&&l.getRowIdxTo()==k&&
l.getColIdxFrom()==f&&l.getColIdxTo()==n:!1};this.isContainCell=function(l,t){return l>=g&&l<=k&&t>=f&&t<=n}}
function KTMergeBlockSet(){function c(){var l=[],t=[],E=[],v=[];this.getStartFromMe=function(){return l};this.getAcrossFromHorizontal=function(){return t};this.getAcrossFromVertical=function(){return E};this.getAcrossFromBoth=function(){return v}}var a=[],h=null,d;this.clear=function(){a=[];h=null};this.remove=function(l){for(var t=0;t<a.length;t++)if(l.equals(a[t]))return a.splice(t,1),h=null,!0;return!1};this.append=function(l){var t=f(a,l.getRowIdxFrom(),l.getColIdxFrom());return l.equals(t)?!1:
(a.push(l),h=null,!0)};this.appendArray=function(l){a=a.concat(l);h=null};this.requestBucketing=function(){h=null};this.bucketing=function(l,t,E,v){if(null==h)for(h={},d=1E6<l?1E4:1E4<l?1E3:100,l=0;l<a.length;l++){t=a[l];for(var J=g(t.getRowIdxFrom(),E),y=g(t.getRowIdxTo(),E),w=J;w<=y;w+=d){var B=h[w];B||(B={},h[w]=B);for(var H=k(t.getColIdxFrom(),v),I=k(t.getColIdxTo(),v),P=H;P<=I;P+=100){var u=B[P];u||(u=new c,B[P]=u);(w==J?P==H?u.getStartFromMe():u.getAcrossFromHorizontal():P==H?u.getAcrossFromVertical():
u.getAcrossFromBoth()).push(t)}}}};var g=function(l,t){l<t?t=0:(l=parseInt((l-t)/d),t+=l*d);return t},k=function(l,t){l<t?t=0:(l=parseInt((l-t)/100),t+=100*l);return t};this.search=function(l,t,E,v){var J=null;if(0<a.length)if(h){if(E=g(l,E),E=h[E])if(v=k(t,v),v=E[v])J=f(v.getStartFromMe(),l,t),!J&&(J=f(v.getAcrossFromVertical(),l,t)),!J&&(J=f(v.getAcrossFromHorizontal(),l,t)),!J&&(J=f(v.getAcrossFromBoth(),l,t))}else J=f(a,l,t);return J};var f=function(l,t,E){for(var v=0;v<l.length;v++){var J=l[v];
if(J.isContainCell(t,E))return J}return null};this.visit=function(l,t,E,v,J,y,w){if(0!=a.length)if(h){var B=[t,E,v,J];t=g(t,y);E=g(E,y);for(y=t;y<=E;y+=d){var H=h[y];if(H)for(var I=k(v,w),P=k(J,w),u=I;u<=P;u+=100){var V=H[u];if(V){if(y==t&&u==I){if(n(l,B,V.getAcrossFromBoth())||n(l,B,V.getAcrossFromVertical())||n(l,B,V.getAcrossFromHorizontal()))return}else if(y==t){if(n(l,B,V.getAcrossFromVertical()))return}else if(u==I&&n(l,B,V.getAcrossFromHorizontal()))return;if(n(l,B,V.getStartFromMe()))return}}}}else for(w=
0;w<a.length&&(B=a[w],B.getRowIdxTo()<t||E<B.getRowIdxFrom()||B.getColIdxTo()<v||J<B.getColIdxFrom()||!l(B));w++);};this.visitAll=function(l){for(var t=0;t<a.length&&!l(a[t]);t++);};var n=function(l,t,E){var v=t[0],J=t[1],y=t[2];t=t[3];for(var w=0;w<E.length;w++){var B=E[w];if(!(B.getRowIdxTo()<v||J<B.getRowIdxFrom()||B.getColIdxTo()<y||t<B.getColIdxFrom())&&l(B))return!0}return!1};this.syncMergeBlocks=function(l,t,E){if(l){l="setRowIdxFrom";var v="getRowIdxFrom";var J="setRowIdxTo";var y="getRowIdxTo"}else l=
"setColIdxFrom",v="getColIdxFrom",J="setColIdxTo",y="getColIdxTo";for(var w=a.length-1;0<=w;w--){var B=a[w];if(E)t<=B[v]()?(B[l](B[v]()+1),B[J](B[y]()+1),h=null):t<=B[y]()&&(B[J](B[y]()+1),h=null);else{var H=!1;t<B[v]()?(B[l](B[v]()-1),B[J](B[y]()-1),H=!0,h=null):t<=B[y]()&&(B[J](B[y]()-1),H=!0,h=null);H&&B.isInvalid()&&a.splice(w,1)}}}}
function KTListenerProxy(){var c={};this.addListener=function(a,h){var d=c[a];d||(d=[],c[a]=d);for(a=0;a<d.length;a++)if(d[a]==h)return;d.push(h)};this.removeListener=function(a,h){if(a=c[a])for(var d=a.length-1;0<=d;d--)if(a[d]==h){a.splice(d,1);break}};this.fireListener=function(a,h){var d=c[a];if(d)for(var g=d.length-1;0<=g;g--)d[g](a,h)}}
function KTEmbedObject(c,a,h,d,g){var k=this,f,n=c,l=a,t=h,E=d,v=g,J,y,w,B,H,I,P=!1;this.$innerBindChangeListener=function(u){f=u};this.setId=function(u){n=u};this.getId=function(){return n};this.setX=function(u){l!=u&&(l=u,f&&f(k,KTEmbedObject.BOUND,void 0,void 0))};this.getX=function(){return l};this.setY=function(u){t!=u&&(t=u,f&&f(k,KTEmbedObject.BOUND,void 0,void 0))};this.getY=function(){return t};this.setWidth=function(u){E!=u&&(E=u,f&&f(k,KTEmbedObject.BOUND,void 0,void 0))};this.getWidth=
function(){return E};this.setHeight=function(u){v!=u&&(v=u,f&&f(k,KTEmbedObject.BOUND,void 0,void 0))};this.getHeight=function(){return v};this.setType=function(u){J=u};this.getType=function(){return J};this.setUserObject=function(u){var V=y;y=u;f&&f(k,KTEmbedObject.DATA,y,V)};this.getUserObject=function(){return y};this.setRowFrom=function(u){w=u};this.getRowFrom=function(){return w};this.setColFrom=function(u){B=u};this.getColFrom=function(){return B};this.setEndRowFrom=function(u){H=u};this.getEndRowFrom=
function(){return H};this.setEndColFrom=function(u){I=u};this.getEndColFrom=function(){return I};this.setFrozenFixed=function(u){P=u};this.isFrozenFixed=function(){return P}}KTEmbedObject.BOUND="embedObjectXYWH";KTEmbedObject.DATA="embedObjectData";
function KTCellTreeModel(c,a){var h,d=a?!0:!1,g=-1,k=!1,f=!0,n;g=-1;this.$innerBindChangeListener=function(l){h=l};this.isHorizontal=function(){return d};this.getLevel=function(){return c};this.setHaveHandlerAlways=function(l){k=l};this.isHaveHandlerAlways=function(){return k};this.setExpanded=function(l){f!=l&&(f=l,h&&h(KTCellTreeModel.EXPANDED))};this.isExpanded=function(){return f};this.setLazyLoaded=function(l){n=l};this.isLazyLoaded=function(){return n};this.setLastChildLevel=function(l){g=l};
this.getLastChildLevel=function(){return g}}KTCellTreeModel.EXPANDED="expanded";
function KTDiagonalModel(){var c=KTDiagonalModel.BASE_LEFT_UP,a=1,h=1,d=[],g=[],k=[];this.setBasePoint=function(n){c=n};this.getBasePoint=function(){return c};this.setCrossRows=function(n){a=n};this.getCrossRows=function(){return a};this.setCrossColumns=function(n){h=n};this.getCrossColumns=function(){return h};this.setLinkToRows=function(n){d=n};this.getLinkToRows=function(){return d};this.setLinkToColumns=function(n){g=n};this.getLinkToColumns=function(){return g};this.getTriangleSize=function(){return d.length+
g.length+2};var f=function(n){var l=k[n];l||(l={text:"",lean:!0},k[n]=l);return l};this.setText=function(n,l){f(l).text=n};this.getText=function(n){return f(n).text};this.setLean=function(n,l){f(l).lean=n};this.isLean=function(n){return f(n).lean};this.setStyle=function(n,l){f(l).style=n};this.getStyle=function(n){return f(n).style};this.setSlashBorder=function(n,l){f(l).slashStyle=n};this.getSlashBorder=function(n){return f(n).slashStyle}}KTDiagonalModel.BASE_LEFT_UP="left-up";
KTDiagonalModel.BASE_RIGHT_UP="right-up";KTDiagonalModel.BASE_LEFT_DOWN="left-down";KTDiagonalModel.BASE_RIGHT_DOWN="right-down";function KTableUI(c){function a(){this.fireEvent=function(r,G){P.fireListener(r,G)};this.isScrollDynamicRepaint=function(){return h.isScrollDynamicRepaint()};this.isDynamicRepaintWithCache=function(){return h.isDynamicRepaintWithCache()};this.isDynamicUpdateModel=function(){return H?!0:!1};this.getDynamicUpdateModelAliveDeltaRows=function(){return I};this.fireDynamicUpdateModelEvent=function(r,G,M){pa(r,G,M)};this.buildStyle=function(r,G,M){return Y(r,G,M)};this.buildBorder=function(r,G,M){var Q=
"";M&&(Q+=aa(M.getBorder(),KTStyleManager.PRIORITY_CELL));Q+=aa(G.getBorder(),KTStyleManager.PRIORITY_COLUMN);Q+=aa(r.getBorder(),KTStyleManager.PRIORITY_ROW);return Q+=aa(d.getBorder(),KTStyleManager.PRIORITY_TABLE)};this.searchRowIdx=function(r){r=!u||1>=u.length?-1:D(u,r);return r};this.searchCell=function(r,G){return z(r,G)};this.getRowY=function(r){return ma(r)};this.getColX=function(r){return V[r]};var e=!1;this.notifyScrolling=function(){e=!0};this.notifyStopScroll=function(){e=!1};this.isScrolling=
function(){return e}}KTableUI.INSERT_COL="insertColumn";KTableUI.REMOVE_COL="removeColumn";KTableUI.INSERT_ROW="insertRow";KTableUI.REMOVE_ROW="removeRow";KTableUI.ADD_MERGEBLOCK="addMergeBlock";KTableUI.REMOVE_MERGEBLOCK="removeMergeBlock";KTableUI.FROZEN_ROW="frozenRow";KTableUI.FROZEN_COL="frozenCol";var h=this,d=c,g=$("<div>"),k,f,n,l,t=[],E=new KTableUIDraggableAdjustingHandler,v,J,y=!0,w=!1,B=!0,H,I,P=new KTListenerProxy,u=[],V=[],ha=!1;this.getHtmlElement=function(){if(!(0<g.children().length)){g.css("overflow",
"hidden");g.css("white-space","nowrap");var e=W().getUI();e.attr("id",d.getId()+W().getName());S(e);e.css("position","absolute");e.css("left",0);e.css("top",0);e.width("100%");e.height("100%");e.css("z-index",0);e.appendTo(g);C()}return g[0]};this.setScrollerVisible=function(e,r,G){var M=W().getUI();M.css("overflow-x",e?e:"hidden");M.css("overflow-y",r?r:"auto");G&&G(M)};var W=function(){if(!k){var e=new a;k=new KTableUIMainView(d,e);h.addListener("scroll",ka);h.addListener("scroll",b);h.addListener("mousedown",
b);h.addListener("mousedown",K);h.addListener("mousemove",K);h.addListener("mouseup",K);h.addListener("mousemove",Z);g.on("mouseleave",qa);h.addListener("mousedown",E.mouseEventHandler);h.addListener("mousemove",E.mouseEventHandler);E.setContext(d,g,{getRowY:ma,getColX:na,getScrollLeft:fa,getScrollTop:ba,isScrolling:e.isScrolling})}return k};this.setSyncUIWhenModelChanged=function(e){y=e};this.isSyncUIWhenModelChanged=function(){return y};this.setScrollDynamicRepaint=function(e,r){w=e?!0:!1;B=r||
"undefined"==typeof r?!0:!1;0<g.children().length&&h.updateUI()};this.isScrollDynamicRepaint=function(){return w};this.isDynamicRepaintWithCache=function(){return B};this.setScrollDynamicUpdateModelListener=function(e,r){I=e;H=r};var pa=function(e,r,G){H&&!ha&&H(e,r,function(){G();n&&n.repaint();F()})};this.updateUI=function(e,r){d.getCellRender().reset();d.bucketingMergeBlocks();if(d.isColumnFitVisibleWidth()){for(var G=0,M=0,Q=d.getColumnsCount();M<Q;M++){var U=d.getColumn(M);U.isHide()||(G+=U.getWidth())}var ca=
g.prop("clientWidth")-1,ia=d.isSyncUIWhenModelChanged();d.setSyncUIWhenModelChanged(!1);G=ca/G;M=0;for(Q=d.getColumnsCount();M<Q;M++)if(U=d.getColumn(M),!U.isHide()){var ta=parseInt(U.getWidth()*G);U.setWidth(ta);ca-=ta}if(0<ca)for(M=d.getColumnsCount()-1;0<=M;M--)if(U=d.getColumn(M),!U.isHide()){U.setWidth(U.getWidth()+ca);break}d.setSyncUIWhenModelChanged(ia)}x(-1);la(-1);var oa;e&&(oa=r?r:h.keepScrollStatus());ha=!0;W().updateUI();ea();f&&f.updateUI();n&&n.updateUI();l&&l.updateUI();if(0<t.length)for(r=
0;r<t.length;r++)t[r]&&t[r].updateUI();A();F();ha=!1;e&&h.restoreScrollStatus(oa)};this.keepScrollStatus=function(){var e=W().getUI().prop("scrollTop"),r=W().getUI().prop("scrollLeft");return{v:e,h:r}};this.restoreScrollStatus=function(e){var r=e.v;e=e.h;W().getUI().prop("scrollTop",r);W().getUI().prop("scrollLeft",e)};this.scrollCellVisible=function(e,r,G){r=V[r];e=u[e];G?W().getUI().animate({scrollTop:e,scrollLeft:r}):W().getUI().prop({scrollTop:e,scrollLeft:r})};this.showPromptForLazyAppendData=
function(e){e?(J||(J=$('<div style="position:absolute; left:0; right:0; top:0; bottom:0">'),J.css("z-index",128),e=$('<div style="position:absolute; left:0; right:0; top:0; bottom:0">'),e.css("background-color","#CCCCCC"),e.css("opacity",.5),e.appendTo(J),e=$("<div>"),e.css("position","absolute"),e.width(120),e.height(20),e.css("padding",10),e.css("background-color","#D0E3F6"),e.css("border","1px solid #97B3CB"),e.text("\u6570\u636e\u52a0\u8f7d\u4e2d..."),e.appendTo(J)),J.appendTo(g),e=J.find(":last-child"),
e.css("left",(g.width()-e.width())/2),e.css("top",(g.height()-e.height())/2)):J&&J.remove()};this.repaintAfterLazyAppendData=function(e){d.getCellRender().reset();la(e);W().reset();W().repaint();W().adjustFootPlaceholder();n&&(n.reset(),n.repaint(),n.adjustFootPlaceholder());F()};this.searchCell=function(e,r){x(-1);la(-1);return z(e,r)};var la=function(e){var r=d.getRowsCount();u.length>r+1&&(u.length=r+1);for(var G=0<=e?u[e]:0,M=e=0<=e?e:0;M<r;M++){u[M]=G;var Q=d.getRow(M);Q.isHide()||(Q=Q.getHeight(),
G+=Q)}u[r]=G;r=e;if(c.isAutoAdjustRowHeight())for(e=0,r=0<=r?r:0,G=u.length-1;r<G;r++){Q=d.getRow(r);if(!Q.isHide()){for(var U=M=0,ca=d.getColumnsCount();U<=ca;U++){var ia=Q.getCellForDraw(U);if(ia){var ta=d.getColumn(U);if(d.getStyleValue(ia,ta,Q,"getStyle","isWrapText",!1)){var oa=r;var ua=U,va=Q,wa=ia;ia=d.searchMergeBlock(oa,ua);if(!ia||oa==ia.getRowIdxFrom()&&ua==ia.getColIdxFrom()){var xa=(ia?V[ia.getColIdxTo()+1]-V[ia.getColIdxFrom()]:ta.getWidth())-4;if(0>xa)oa=0;else{var za=Y(va,ta,wa),ya=
d.getCellRender();ya.setContext(va,ta,wa,oa,ua,NaN,NaN,xa,NaN);oa=ya.calculateCellHeight(za);ia&&(oa-=u[ia.getRowIdxTo()+1]-u[ia.getRowIdxFrom()+1],oa=0>oa?0:oa);oa+=4}}else oa=0;M=oa>M?oa:M}}}Q=Q.getHeight();M>Q&&(e+=M-Q)}u[r+1]+=e}},x=function(e){var r=d.getColumnsCount();V.length>r+1&&(V.length=r+1);var G=0<=e?V[e]:0;for(e=0<=e?e:0;e<r;e++){V[e]=G;var M=d.getColumn(e);M.isHide()||(M=M.getWidth(),G+=M)}V[r]=G},z=function(e,r){if(!V||1>=V.length||!u||1>=u.length||e>=V[V.length-1]||r>=u[u.length-
1])return null;e=D(V,e,!0);return[D(u,r,!0),e]},D=function(e,r,G){for(var M,Q=[0,e.length-2];Q;){var U=Q[0],ca=Q[1];if(U==ca){M=U;break}var ia=U+ca>>1;if(e[ia]==r){M=ia;break}else if(e[ia]<r)Q[0]=ia+1,Q[1]=ca;else if(e[ia]>r){if(ia-1<U){M=ia;break}Q[0]=U;Q[1]=ia-1}else throw Error("Prevent endless loop.");}if(G){for(;e[M]>r&&0<M;)--M;for(;e[M+1]<=r&&M<e.length-2;)M+=1}return M};this.modelChangeHandler=function(e,r){if(y&&0<g.children().length){var G=W().modelChangeHandler(e,r);f&&(G=G||f.modelChangeHandler(e,
r));n&&(G=G||n.modelChangeHandler(e,r));l&&(G=G||l.modelChangeHandler(e,r));if(0<t.length)for(var M=0;M<t.length;M++)t[M]&&(G=G||t[M].modelChangeHandler(e,r));G&&h.updateUI(!0)}};this.propertyChangeHandler=function(e,r,G,M){if(y&&0<g.children().length)switch(r){case KTColumn.WIDTH:x(d.getColumnIndex(e));L(e,r,G,M);ea();ra();break;case KTRow.HEIGHT:la(d.getRowIndex(e));L(e,r,G,M);sa();break;case KTableUI.FROZEN_ROW:case KTableUI.FROZEN_COL:C();h.updateUI();break;case KTRow.HIDE:var Q=d.getRowIndex(e);
la(Q);L(e,r,G,M);ea();ra();sa();break;case KTColumn.HIDE:Q=d.getColumnIndex(e);x(Q);L(e,r,G,M);ea();ra();sa();break;case KTEmbedObject.DATA:W().propertyChangeHandler(e,r,G,M);break;default:L(e,r,G,M)}};var L=function(e,r,G,M){var Q=W().propertyChangeHandler(e,r,G,M);f&&(Q=Q||f.propertyChangeHandler(e,r,G,M));n&&(Q=Q||n.propertyChangeHandler(e,r,G,M));l&&(Q=Q||l.propertyChangeHandler(e,r,G,M));if(0<t.length)for(var U=0;U<t.length;U++)t[U]&&(Q=Q||t[U].propertyChangeHandler(e,r,G,M));Q&&h.updateUI(!0)};
this.addListener=function(e,r){P.addListener(e,r)};this.removeListener=function(e,r){P.removeListener(e,r)};var C=function(){var e=d.getFrozenRows(),r=d.getFrozenColumns();e=0<e;r=0<r;var G=e&&r;e&&!f?(f=new KTableUITopFrozenView(d,new a),T(f,1)):!e&&f&&(da(f),f=null);r&&!n?(n=new KTableUILeftFrozenView(d,new a),T(n,1)):!r&&n&&(da(n),n=null);G&&!l?(l=new KTableUICornerFrozenView(d,new a),T(l,2)):!G&&l&&(da(l),l=null)},S=function(e){var r=d.getUICustomStyleMap();r=r?r["background-color"]:null;e.css("background-color",
r?r:"#fff")},T=function(e,r){e=e.getUI();e.appendTo(g);e.css("z-index",r);e.css("top",0);e.css("left",0);S(e)},da=function(e){e.getUI().remove();e.destroy()};this.relayoutViews=function(){W().repaint();ea();ra();sa();A();F()};var ea=function(){if(f){var e=W().getUI().prop("clientWidth");f.getUI().width(e)}n&&(e=W().getUI().prop("clientHeight"),n.getUI().height(e))},ka=function(e,r){r.isHorizontalScroll()&&(ra(),A(),f&&q("left",fa()-r.getLastScrollLeft()));r.isVerticalScroll()&&(sa(),F(),n&&q("top",
ba()-r.getLastScrollTop()))},ra=function(){if(f){var e=fa();f.getUI().prop("scrollLeft",e)}},sa=function(){if(n){var e=ba();n.getUI().prop("scrollTop",e);h.isScrollDynamicRepaint()&&(n.setBlankFirstImmediately(k.isBlankFirstImmediately()),n.repaint(),n.setBlankFirstImmediately(!1))}},q=function(e,r){if(!(0==t.length||f&&n))for(var G=0;G<t.length;G++)if(t[G]){var M=parseInt(t[G].getUI().css(e));t[G].getUI().css(e,M-r+"px")}},A=function(){if(d.isMergeBlockTextVisibleAlways()&&1<V.length){var e=fa(),
r=e+W().getUI().prop("clientWidth");e+=n?n.getUI().prop("offsetWidth"):0;var G=D(V,e,!0),M=D(V,r,!0);(f?f:W()).adjustHorizontalFrontierCell(e,r,G,M)}},F=function(){if(d.isMergeBlockTextVisibleAlways()&&1<u.length){var e=ba(),r=e+W().getUI().prop("clientHeight");e+=f?f.getUI().prop("offsetHeight"):0;var G=D(u,e,!0),M=D(u,r,!0);(n?n:W()).adjustVerticalFrontierCell(e,r,G,M)}};this.popupMenu=function(e,r,G,M,Q){b();if(G&&0!=G.length){if(Q){var U=Q["background-color"];var ca=Q["border-color"];var ia=Q["font-size"];
var ta=Q["selection-color"]}U=U?U:"#D0E3F6";ca=ca?ca:"#97B3CB";ia=ia?ia:12;ta=ta?ta:"#FFE358";v=$("<div>");v.css("z-index",64);v.css("position","absolute");v.css("cursor","pointer");v.css("border","1px solid");v.css("border-color",ca);v.css("background-color",U);v.css("font-size",ia);for(Q=0;Q<G.length;Q++)U=G[Q],ca=$("<div>"),ca.text(U.getText()),ca.css("padding",2),ca.css("max-width",300),ca.css("text-overflow","ellipsis"),ca.css("overflow","hidden"),ca.click(N(M,U)),ca.mouseover(function(oa){$(oa.target).css("background-color",
ta)}),ca.mouseout(function(oa){$(oa.target).css("background-color","")}),v.append(ca);g.append(v);e+v.width()>g.width()&&(v.width(v.width()+2),e=g.width()-v.width()-5,e=0>e?0:e);r+v.height()>g.height()&&(r=g.height()-v.height()-5,r=0>r?0:r);v.css("left",e);v.css("top",r)}};var N=function(e,r){return function(G){b();e&&e(r)}},b=function(){v&&v.remove()},m=!1,p=!1,O=null,K=function(e,r){r.isStopped()||d.getSelectionModel().getMode()==KTSelectionModel.MODE_NONE||null===d.getSelectionRender()||("mousedown"==
e?r.isLeftButton()&&(e=r.getMouseTargetModel(),e instanceof KTCell.Path&&(m=!0,O=d.getSelectionModel().createCellTarget(e.getRowIndex(),e.getColIndex()))):"mouseup"==e?(p&&(R(null),e=r.getMouseTargetModel(),e instanceof KTCell.Path&&(e=d.getSelectionModel().createCellTarget(e.getRowIndex(),e.getColIndex()),e.equals(O)||d.getSelectionModel().appendSelected(e))),m=p=!1,O=null):"mousemove"==e&&d.getSelectionModel().isPolicySetting(KTSelectionModel.POLICY_BLOCK)&&(m&&!p&&(p=!0),p&&(e=r.getMouseTargetModel(),
R(e))))},R=function(e){var r=null;if(e instanceof KTCell.Path){r=d.getSelectionModel();e=r.createCellTarget(e.getRowIndex(),e.getColIndex());e=r.parseBlockRange(e);var G=r.parseBlockRange(O);r=r.createBlockTarget(Math.min(Math.min(Math.min(e[0],e[2]),G[0]),G[2]),Math.min(Math.min(Math.min(e[1],e[3]),G[1]),G[3]),Math.max(Math.max(Math.max(e[0],e[2]),G[0]),G[2]),Math.max(Math.max(Math.max(e[1],e[3]),G[1]),G[3]))}k.showDragingMarkBundle(r);l&&l.showDragingMarkBundle(r);n&&n.showDragingMarkBundle(r);
f&&f.showDragingMarkBundle(r)},X=function(e,r){e==KTSelectionModel.CHANGE_ADD&&(e=d.getSelectionModel().parseBlockRange(r[0]),P.fireListener("new-select",[V[e[1]],u[e[0]],V[e[3]+1],u[e[2]+1]]))},Y=function(e,r,G){var M="";G&&(M+=aa(G.getStyle(),KTStyleManager.PRIORITY_CELL));M+=aa(r.getStyle(),KTStyleManager.PRIORITY_COLUMN);M+=aa(e.getStyle(),KTStyleManager.PRIORITY_ROW);return M+=aa(d.getStyle(),KTStyleManager.PRIORITY_TABLE)},aa=function(e,r){if(!e)return"";var G=d.getStyleManager().getShareStyleId(e,
r),M=KTableUI.oMapsCssName.getMap(r);if(!M[G]){M[G]=!0;M="."+G;e=e.toCssString();r=KTableUI.sStyleNodeIdPrefix+r;for(var Q,U=document.styleSheets.length-1;0<=U;U--){var ca=document.styleSheets[U];if((ca.id||""==ca.id?ca.id:ca.ownerNode.id)==r){Q=ca;break}}Q.addRule?Q.addRule(M,e):Q.insertRule(M+"{"+e+"}",Q.cssRules.length)}return" "+G};this.selectByPoint=function(e,r){r=z(e,r);if(!r)return!1;e=d.getSelectionModel();r=e.isPolicySetting(KTSelectionModel.POLICY_ROW)?e.createRowTarget(r[0]):e.isPolicySetting(KTSelectionModel.POLICY_COLUMN)?
e.createColumnTarget(r[1]):e.createCellTarget(r[0],r[1]);e.removeAllSelecteds();e.addSelected(r);return!0};var Z=function(e,r){if(e=d.getCellAcrossListener())if(r.isCellPointed()){var G=r.getMouseTargetModel(),M=d.getSelectionModel().createCellTarget(G.getRowIndex(),G.getColIndex());G=M.getRowIdx();M=M.getColIdx();r=$(r.getOriginalEvent().currentTarget);var Q=KTableUIAbstractView.createCellId(d.getRow(G),d.getColumn(M));r=r.find("#"+Q);e(r,G,M,ja)}else e(null,-1,-1,ja)},qa=function(e){(e=d.getCellAcrossListener())&&
e(null,-1,-1,ja)},ja=function(e,r){if(void 0===r){var G="*[id*='"+KTableUIAbstractView.createCellId(d.getRow(e))+"']";return g.find(G)}G="#"+KTableUIAbstractView.createCellId(d.getRow(e),d.getColumn(r));e=function(M){return(M=M?M.getCellsContainer().find(G):null)&&0<M.length?M:null};return e(l)||e(n)||e(f)||e(k)},fa=function(){return W().getUI().prop("scrollLeft")},ba=function(){return W().getUI().prop("scrollTop")},ma=function(e){return e>=u.length?u[u.length-1]:u[e]},na=function(e){return V[e]};
(function(){if(!KTableUI.sStyleNodeIdPrefix){KTableUI.sStyleNodeIdPrefix="_ktable_style_";var e=$("head"),r=KTableUI.sStyleNodeIdPrefix+KTStyleManager.PRIORITY_TABLE;e.append($('<style type="text/css" id="'+r+'">'));r=KTableUI.sStyleNodeIdPrefix+KTStyleManager.PRIORITY_ROW;e.append($('<style type="text/css" id="'+r+'">'));r=KTableUI.sStyleNodeIdPrefix+KTStyleManager.PRIORITY_COLUMN;e.append($('<style type="text/css" id="'+r+'">'));r=KTableUI.sStyleNodeIdPrefix+KTStyleManager.PRIORITY_CELL;e.append($('<style type="text/css" id="'+
r+'">'))}d.getSelectionModel().addChangeListener(X)})()}KTableUI.sStyleNodeIdPrefix=null;KTableUI.oMapsCssName=new KTStyleManager.MultiMaps;
function KTableUIAbstractView(c,a){function h(q,A,F,N,b,m,p,O){KTAbstractMouseEvent.call(this,q,A,F,N,b);var K;this.getOriginalEvent=function(){return q};this.isCellPointed=function(){return m instanceof KTCell.Path};this.getMouseTargetModel=function(){return m};this.isPointTreeHandler=function(){return p};this.isPointScrollBar=function(){return O};this.setXYCellAtTable=function(R,X){K=[R,X]};this.getXYCellAtTable=function(){return K}}function d(){KTableSelectionRender.call(this);var q=$("<div>"),
A=$("<div>"),F=$("<div>"),N=$("<div>");this.show=function(p,O,K,R,X){--O;--K;--R;--X;var Y=R-O,aa=X-K;b(q,O,K,Y,0);b(F,O,X,Y,0);b(N,O,K,0,aa);b(A,R,K,0,aa);p.append(q);p.append(A);p.append(F);p.append(N)};this.remove=function(){q.remove();A.remove();F.remove();N.remove()};this.current=function(){m(q);m(F);m(N);m(A)};var b=function(p,O,K,R,X){p.attr("ktableUiMark","selectionBundle");p.css("z-index",64);p.css("position","absolute");p.css("left",O);p.css("top",K);p.width(R);p.height(X);p.css("overflow",
"hidden");p.css("border-width","1px");p.css("border-style","solid");m(p)};this.letOthersOld=function(p){p.children("div[ktableUiMark='selectionBundle']").css("border-color","#ffcc33")};var m=function(p){p.css("border-color","#aa6600")}}var g=this,k=$("<div>"),f,n={};this.getName=function(){throw Error("Override me.");};this.getViewTag=function(){throw Error("Override me.");};this.destroy=function(){};this.getUI=function(){return k};this.getCellsContainer=function(){f||(f=$("<div>"),f.attr("ktableUiMark",
"allCellLayer"),f.css("z-index",1),f.css("position","absolute"),f.css("left",0),f.css("top",0),k.append(f));return f};this.updateUI=function(){g.protectedBeforeUpdateUI();k.children(":not([ktableUiMark='allCellLayer'])").remove();g.getCellsContainer().empty();g.repaint();g.adjustFootPlaceholder();g.adjustRightPlaceholder()};this.protectedBeforeUpdateUI=function(){};this.adjustFootPlaceholder=function(){var q=a.getRowY(c.getRowsCount())+1;g.getCellsContainer().css("height",q)};this.adjustRightPlaceholder=
function(){var q=c.getDraggableAdjusting(),A=0;q&&(A=(A=q?q[2]:null)?A.getTailBlankForDragging():60);q=a.getColX(c.getColumnsCount())+1;q+=A;g.getCellsContainer().css("width",q)};this.protectedBeforeRepaint=function(q){throw Error("Override me.");};this.protectedIsNeedCreatingRow=function(q,A,F,N){return!0};this.protectedAfterRepaint=function(q,A,F){};this.protectedGetPaintRect=function(){throw Error("Override me.");};this.repaint=function(){l();y()};this.adjustVerticalFrontierCell=function(q,A,F,
N){var b=g.protectedBeforeRepaint();c.visitMergeBlocks(F,N,b[2],b[3],function(m){if(m.getRowIdxFrom()!=m.getRowIdxTo()){var p=D(m);if(p.length){var O=p[p.length-1];p=$(O);var K=a.getRowY(m.getRowIdxFrom()),R=a.getRowY(m.getRowIdxTo()+1),X=Math.max(q,K),Y=Math.min(A,R)-X-(R-K);R=p.width();Y=p.height()+Y;if(!(20>Y)||F<m.getRowIdxFrom()&&m.getRowIdxTo()<N)if(K=X-K,a.isDynamicUpdateModel())$(O).children().css({top:K,height:Y,"line-height":Y+"px"});else{X=m.getRowIdxFrom();var aa=m.getColIdxFrom(),Z=c.getRow(X),
qa=c.getColumn(aa),ja=Z.getCell(aa);0==X&&0==aa&&ja&&ja.getValue()instanceof KTDiagonalModel||(p.empty(),I(O,X,aa,Z,qa,ja,m,0,K,R,Y))}}}})};this.adjustHorizontalFrontierCell=function(q,A,F,N){var b=g.protectedBeforeRepaint();c.visitMergeBlocks(b[0],b[1],F,N,function(m){if(m.getColIdxFrom()!=m.getColIdxTo()){var p=D(m);if(p.length){var O=p[p.length-1];p=$(O);var K=a.getColX(m.getColIdxFrom()),R=a.getColX(m.getColIdxTo()+1),X=Math.max(q,K),Y=Math.min(A,R)-X-(R-K);R=m.getRowIdxFrom();var aa=m.getColIdxFrom(),
Z=c.getRow(R),qa=c.getColumn(aa),ja=Z.getCell(aa);if(!(0==R&&0==aa&&ja&&ja.getValue()instanceof KTDiagonalModel)){Y=p.width()+Y;var fa=p.height();K=X-K;p.empty();I(O,R,aa,Z,qa,ja,m,K,0,Y,fa)}}}})};this.createVisibleRect=function(){var q=g.getUI().prop("clientWidth");!q&&(q=window.screen.width);var A=g.getUI().prop("clientHeight");!A&&(A=window.screen.height);var F=g.getUI().prop("scrollLeft");return[F,iY1,F+q,iY1+A]};var l=function(q){g.protectedBeforeRepaint(function(A,F,N,b,m){q?g.getCellsContainer().empty():
a.isScrollDynamicRepaint()?(g.getUI().find("*[isProxyFirstCell='true']").remove(),a.isDynamicUpdateModel()&&g.getUI().find("*[isBlankFirst=true]").remove()):g.getCellsContainer().empty();if(!(-1==A&&-1==F||-1==N&&-1==b)){for(var p=A,O=[],K=!0,R=document.createDocumentFragment(),X=A;X<=F;X++){var Y=c.getRow(X);K&&(Y.isHide()?p++:K=!1);if(!Y.isHide()&&g.protectedIsNeedCreatingRow(X,p,x,m))for(var aa=a.getRowY(X),Z=N;Z<=b;Z++){var qa=c.getColumn(Z);if(!qa.isHide()){var ja=Y.getCellForDraw(Z),fa=a.getColX(Z);
a:{var ba=X;var ma=Z,na=Y,e=fa,r=aa,G=O;fa=u(ba,ma,p);var M=na,Q=!1;if(!1===fa){var U=a.getColX(ma+1)-a.getColX(ma);var ca=a.getRowY(ba+1)-a.getRowY(ba);fa=null}else if(fa){fa instanceof Array&&(Q=fa[1],fa=fa[0]);if(fa.getRowIdxFrom()!=ba||fa.getColIdxFrom()!=ma)ba=fa.getRowIdxFrom(),na=c.getRow(ba),ma=fa.getColIdxFrom(),qa=c.getColumn(ma),a.isDynamicUpdateModel()&&ja?(U=ja.getValue(),ja=na.getCell(ma),ja.setValue(U)):ja=na.getCellForDraw(ma),r=a.getRowY(ba),e=a.getColX(ma);U=fa.getColIdxTo()+1;ca=
fa.getRowIdxTo()+1;U=U>c.getColumnsCount()?c.getColumnsCount():U;ca=ca>c.getRowsCount()?c.getRowsCount():ca;U=a.getColX(U)-a.getColX(fa.getColIdxFrom());ca=a.getRowY(ca)-a.getRowY(fa.getRowIdxFrom())}else{ba=null;break a}pa(U,ca,ja,qa,na,G);var ia=G[0],ta=G[1],oa=G[2];G=G[3];M=x(M,qa);e=P("div",e+ia,r+ta,oa,G);e.id=M;e.style.zIndex=ja&&ja.getValue()?2:1;fa&&$(e).attr("mergeBlock",z(fa));r=a.buildStyle(na,qa,ja);r+=a.buildBorder(na,qa,ja);e.className=r;Q&&$(e).attr("isProxyFirstCell","true");if(ja&&
ja.getValue()instanceof KTDiagonalModel){if(ba=c.getDiagonalRender().create(c,ja.getValue(),ba,ma,U,ca))e.appendChild(ba),ba.style.position="absolute",ba.style.left=ia+"px",ba.style.top=ta+"px",ba.style.width=U+"px",ba.style.height=ca+"px"}else I(e,ba,ma,na,qa,ja,fa,0,0,oa,G);ba=e}ba&&(m&&$(ba).attr("isBlankFirst",!0),ma=ba.id,ma=$(g.getCellsContainer()[0]).find("#"+ma),0<ma.length&&ma.remove(),R.appendChild(ba))}}}g.getCellsContainer()[0].appendChild(R);m||g.protectedAfterRepaint(A,F,x)}})},t={},
E={},v={},J={},y=function(){var q=c.getEmbedObjects(),A=g.protectedGetPaintRect(),F=A[0],N=A[1],b=A[2];A=A[3];for(var m=0;m<q.length;m++){var p=q[m];if(!(p.getY()+p.getHeight()<F||p.getY()>N||p.getX()+p.getWidth()<b||p.getX()>A)){var O=la(p);if(0===k.find("#"+O).length){var K=p.getUserObject();if(!p.getColFrom()||!p.getRowFrom())if(0===K.anchorMode){var R=K.positionCellLT&&K.positionCellLT.split("_");var X=K.positionCellRB&&K.positionCellRB.split("_");R&&X||(R=a.searchCell(p.getX(),p.getY()),X=a.searchCell(p.getX()+
p.getWidth()-1,p.getY()+p.getHeight()-1));R&&X&&(p.setColFrom(R[1]),p.setRowFrom(R[0]),p.setEndColFrom(Number(X[1])+1),p.setEndRowFrom(Number(X[0])+1))}else if(R=1===K.anchorMode?K.positionCellLT&&K.positionCellLT.split("_"):a.searchCell(p.getX(),p.getY()))p.setColFrom(R[1]),p.setRowFrom(R[0]);if(void 0!==p.getColFrom()&&void 0!==p.getRowFrom())if(0===K.anchorMode){K=w(p.getColFrom());R=w(p.getEndColFrom());X=B(p.getRowFrom());var Y=B(p.getEndRowFrom());void 0===t[p.getId()]&&(t[p.getId()]=p.getX()-
K-1,v[p.getId()]=R-p.getX()-p.getWidth(),E[p.getId()]=p.getY()-X-1,J[p.getId()]=Y-p.getY()-p.getHeight());p.setX(K+1+t[p.getId()]);p.setY(X+1+E[p.getId()]);p.setWidth(R-v[p.getId()]-p.getX());p.setHeight(Y-J[p.getId()]-p.getY())}else 1===K.anchorMode&&(K=w(p.getColFrom()),X=B(p.getRowFrom()),void 0===t[p.getId()]&&(t[p.getId()]=p.getX()-K-1,E[p.getId()]=p.getY()-X-1),p.setX(K+1+t[p.getId()]),p.setY(X+1+E[p.getId()]));K=P("div",p.getX(),p.getY(),p.getWidth(),p.getHeight());K.id=O;K.style.zIndex=128;
O=$(K);O.appendTo(k);K=c.getEmbedObjectRender();K.setViewTag(g.getViewTag());K.paintEmbedObject(p,O)}}}},w=function(q){for(var A=0,F=0;F<q;F++){var N=c.getColumn(F);N&&(A+=N.getWidth())}return A},B=function(q){for(var A=0,F=0;F<q;F++){var N=c.getRow(F);N&&(A+=N.getHeight())}return A},H=function(){for(var q=c.getEmbedObjects(),A=0,F=q.length;A<F;A++)$(c.getUI()).find("div[id$='"+q[A].getId()+"']").remove()},I=function(q,A,F,N,b,m,p,O,K,R,X){var Y=R,aa=X;if(m&&m.getTreeModel()){var Z=c.getTreeHandlerRender();
Z.setUiDependence(a);Z.setMergeBlock(p);O=Z.create(m.getTreeModel(),A,F,O,K,R,X);if(K=O[0])K.ktableUiMark="treeHandler",K.style.zIndex=2,q.appendChild(K);(K=O[2])&&q.appendChild(K);if(Z=O[1])Z.ktableUiMark="textSpan",Z.style.zIndex=1,q.appendChild(Z),Y=parseInt(Z.style.width),aa=parseInt(Z.style.height);K=O=0}if(m&&m.getValue()instanceof KTDiagonalModel){if(q=(new KTDiagonalRender).createCanvas(c,m.getValue(),A,F,iCellWidth,iCellHeight))htmlDiv.appendChild(q),q.style.position="absolute",q.style.left=
O+"px",q.style.top=K+"px"}else p=c.getCellRender(),p.setContext(N,b,m,A,F,R,X,Y,aa),p.setTextOffset(O,K),p.paintCellUI(q,Z)},P=function(q,A,F,N,b){q=document.createElement(q);q.style.overflow="hidden";q.style.position="absolute";q.style.left=A+"px";q.style.top=F+"px";q.style.width=N+"px";q.style.height=b+"px";return q},u=function(q,A,F){var N=c.searchMergeBlock(q,A);if(N){if(q==N.getRowIdxFrom()&&A==N.getColIdxFrom())return N;if(q==F&&N.getRowIdxFrom()<F&&A==N.getColIdxFrom())return[N,!0];F=N.getRowIdxFrom()-
1;for(var b=null;F<q&&(null==b||b.isHide());)b=c.getRow(++F);if(F==q){q=N.getColIdxFrom()-1;for(F=null;q<A&&(null==F||F.isHide());)F=c.getColumn(++q);if(q==A)return[N,!1]}return null}return!1},V=function(q,A,F,N){N.removeClass(function(){return W($(this),KTStyle.CSS_ID_PREFIXE)});N.addClass(a.buildStyle(q,A,F))},ha=function(q,A,F,N){N.removeClass(function(){return W($(this),KTBorderStyle.CSS_ID_PREFIXE)});N.addClass(a.buildBorder(q,A,F,N))},W=function(q,A){if(q=q.attr("class")){var F=q.split(" ");
q="";for(var N=0;N<F.length;N++)0==F[N].indexOf(A)&&(0<q.length&&(q+=" "),q+=F[N])}return q},pa=function(q,A,F,N,b,m){var p=c.getStyleValue(F,N,b,"getBorder","getRightBorderWidth",0),O=c.getStyleValue(F,N,b,"getBorder","getLeftBorderWidth",0),K=c.getStyleValue(F,N,b,"getBorder","getTopBorderWidth",0);N=c.getStyleValue(F,N,b,"getBorder","getBottomBorderWidth",0);F=O>>1;q=q-(O-F)-(p>>1);p=K>>1;A=A-(K-p)-(N>>1);m[0]=-F;m[1]=-p;m[2]=0>q?0:q;m[3]=0>A?0:A},la=function(q){return c.getId()+g.getName()+"_Embed_"+
q.getId()},x=function(q,A){return KTableUIAbstractView.createCellId(q,A)},z=function(q){return[q.getRowIdxFrom(),q.getRowIdxTo(),q.getColIdxFrom(),q.getColIdxTo()].join()},D=function(q){return g.getUI().find("[mergeBlock='"+z(q)+"']")};this.propertyChangeHandler=function(q,A,F,N){switch(A){case KTColumn.WIDTH:return this.protectedUpdateColumnWidth(),!0;case KTRow.HEIGHT:return this.protectedUpdateRowHeight(),!0;case KTCell.VALUE:C(q);break;case KTStyle.STYLE_COMMON:case KTStyle.STYLE_TEXT_SPECIAL:case KTBorderStyle.BORDER_COMMON:case KTBorderStyle.BORDER_WIDTH:if(q instanceof
KTable)return!0;if(q instanceof KTCell.Path)F=A==KTBorderStyle.BORDER_WIDTH?a.getColX(q.getColIndex()):0,N=A==KTBorderStyle.BORDER_WIDTH?a.getRowY(q.getRowIndex()):0,L(q.getRow(),q.getCol(),q.getCell(),A,F,N),C(q);else if(q instanceof KTRow){var b=c.getRowIndex(q);N=A==KTBorderStyle.BORDER_WIDTH?a.getRowY(c.getRowIndex(q)):0;for(var m=0,p=c.getColumnsCount();m<p;m++){var O=c.getColumn(m),K=q.getCellForDraw(m);F=a.getColX(R);L(q,O,K,A,F,N);K=new KTCell.Path(q,m,K);K.$innerSetInfo(b,O);C(K)}}else if(q instanceof
KTColumn){F=A==KTBorderStyle.BORDER_WIDTH?a.getColX(c.getColumnIndex(q)):0;b=c.getColumnIndex(q);var R=0;for(m=c.getRowsCount();R<m;R++)p=c.getRow(R),K=p.getCellForDraw(b),N=a.getRowY(R),L(p,q,K,A,F,N),K=new KTCell.Path(p,b,K),K.$innerSetInfo(R,q),C(K)}break;case KTRow.HIDE:this.protectedUpdateByRowHide();break;case KTColumn.HIDE:this.protectedUpdateByColumnHide();break;case KTEmbedObject.DATA:A=la(q),A=k.find("#"+A),0<A.length&&(R=c.getEmbedObjectRender(),R.setViewTag(g.getViewTag()),R.paintEmbedObject(q,
A))}return!1};this.modelChangeHandler=function(q,A){switch(A){case KTableUI.INSERT_COL:case KTableUI.REMOVE_COL:return!0;case KTableUI.INSERT_ROW:case KTableUI.REMOVE_ROW:return!0;case KTableUI.ADD_MERGEBLOCK:case KTableUI.REMOVE_MERGEBLOCK:return!0}return!1};this.protectedUpdateColumnWidth=function(){l(!0);g.adjustRightPlaceholder();H();y()};this.protectedUpdateRowHeight=function(){l(!0);g.adjustFootPlaceholder();H();y()};this.protectedUpdateByRowHide=function(){l();g.adjustFootPlaceholder()};this.protectedUpdateByColumnHide=
function(){l();g.adjustRightPlaceholder()};var L=function(q,A,F,N,b,m){var p=x(q,A);p=k.find("#"+p);if(0!=p.length)if(N==KTStyle.STYLE_COMMON||N==KTStyle.STYLE_TEXT_SPECIAL)V(q,A,F,p);else if(N==KTBorderStyle.BORDER_COMMON)ha(q,A,F,p);else if(N==KTBorderStyle.BORDER_WIDTH){ha(q,A,F,p);N=[];var O=c.getRowIndex(q);O=a.getRowY(O+1)-a.getRowY(O);var K=c.getColumnIndex(A);K=a.getColX(K+1)-a.getColX(K);pa(K,O,F,A,q,N);p.css("left",b+N[0]);p.css("top",m+N[1]);p.width(N[2]);p.height(N[3])}},C=function(q){var A=
x(q.getRow(),q.getCol());A=k.find("#"+A);if(0!=A.length){for(var F=null,N=A.width(),b=A.height(),m=A.find("span"),p=0;p<m.length;p++)if("textSpan"==m[p].ktableUiMark){F=m[p];b=$(F);N=b.width();b=b.height();break}m=c.getCellRender();m.setContext(q.getRow(),q.getCol(),q.getCell(),q.getRowIndex(),q.getColIndex(),A.width(),A.height(),N,b);m.paintCellUI(A[0],F)}},S=[-65535,-65535],T=0,da=function(q){var A=q.type;"click"!=A&&("mouseup"==A?5>Math.abs(S[0]-q.screenX)&&5>Math.abs(S[1]-q.screenY)&&ea(q,"click"):
"mousedown"==A&&(300>(new Date).getTime()-T&&(ea(q,"dblclick"),T=0),T=(new Date).getTime(),S=[q.screenX,q.screenY]),ea(q,A))},ea=function(q,A){var F=k[0],N=0,b=0,m=q.target;m==F&&(N=F.scrollLeft,b=F.scrollTop);for(var p=c.getId()+g.getName()+"_Embed_";m!=F;){if(!m||m.id&&"string"==typeof m.id&&0==m.id.indexOf(p))return;m=m.parentNode}for(m=q.target;m&&m!=F;)N+=m.offsetLeft,b+=m.offsetTop,m=m.parentNode;p=N+(void 0==q.offsetX?q.originalEvent.layerX:q.offsetX);var O=b+(void 0==q.offsetY?q.originalEvent.layerY:
q.offsetY),K=p-F.scrollLeft,R=O-F.scrollTop,X=!1;if(K>=F.clientWidth||R>=F.clientHeight)if("mousemove"==A)X=!0;else return;m=q.target;for(var Y,aa=!1;m&&m!=F&&(!aa||!(Y=KTableUIAbstractView.searchCellModelById(c,m.id)));)aa||"treeHandler"!=m.ktableUiMark||(aa=!0),m=m.parentNode;if(!Y)if(m=a.searchCell(p,O),null==m)Y=null;else{F=m[0];Y=m[1];var Z=c.getRow(F);m=c.getColumn(Y);var qa=Z.getCellForDraw(Y);Y=new KTCell.Path(Z,Y,qa);Y.$innerSetInfo(F,m)}q=new h(q,p,O,K,R,Y,aa,X);q.setXYCellAtTable(N,b);
a.fireEvent(A,q)},ka=function(q,A,F,N){A=a.getColX(A);q=a.getRowY(q);N=a.getColX(N+1);F=a.getRowY(F+1);return[A,q,N,F]},ra=function(){var q=c.getSelectionRender();q=q?q:d;q=new q;q.setTable(c);return q},sa=null;this.showDragingMarkBundle=function(q){sa&&(sa.remove(),sa=null);if(q){var A=c.getSelectionModel().getSelected(),F=n[A];F&&F.remove();q=c.getSelectionModel().parseBlockRange(q);q=ka(q[0],q[1],q[2],q[3]);sa=ra();sa.show(k,q[0],q[1],q[2],q[3])}else if(A=c.getSelectionModel().getSelected(),F=
n[A])q=c.getSelectionModel().parseBlockRange(A),q=ka(q[0],q[1],q[2],q[3]),F.show(k,q[0],q[1],q[2],q[3])};this.getMaxFrozenRowIdx=function(){return Math.min(c.getFrozenRows()-1,c.getRowsCount()-1)};this.getMaxFrozenColumnIdx=function(){return Math.min(c.getFrozenColumns()-1,c.getColumnsCount()-1)};k.css("position","absolute");k.mouseup(da);k.mousedown(da);k.mousemove(da);k.dblclick(da);c.getSelectionModel().addChangeListener(function(q,A){if(null!==c.getSelectionRender())for(var F=0;F<A.length;F++){var N=
A[F];if(q==KTSelectionModel.CHANGE_ADD){var b=c.getSelectionModel().parseBlockRange(N);b=ka(b[0],b[1],b[2],b[3]);var m=ra();n[N]=m;m.letOthersOld(k);m.show(k,b[0],b[1],b[2],b[3])}else q==KTSelectionModel.CHANGE_REMOVE&&n[N]&&(n[N].remove(),delete n[N],N=c.getSelectionModel().getSelected(),(N=n[N])&&N.current())}})}KTableUIAbstractView.createCellId=function(c,a){var h="cell_I_";c&&(h+=c.getKey()+"_I_",a&&(h+=a.getKey()));return h};
KTableUIAbstractView.searchCellModelById=function(c,a){if(!a||0!=a.indexOf("cell_I_"))return null;a=a.split("_I_");if(3!=a.length)return null;var h=a[1],d=a[2];a=-1;for(var g=0,k=c.getRowsCount();g<k;g++){var f=c.getRow(g);if(f.getKey()==h){a=g;break}}if(-1==a)return null;h=c.getColumn(d);c=c.getColumnIndex(h);d=f.getCellForDraw(c);f=new KTCell.Path(f,c,d);f.$innerSetInfo(a,h);return f};
function KTableSelectionRender(){var c;this.setTable=function(a){c=a};this.getTable=function(){return c};this.show=function(a,h,d,g,k){};this.remove=function(){};this.current=function(){};this.letOthersOld=function(a){}}
function KTableUIManyRowsView(c,a){KTableUIAbstractView.call(this,c,a);var h=this,d,g,k,f,n=!1;this.setBlankFirstImmediately=function(y){n=y?!0:!1};this.isBlankFirstImmediately=function(){return n};this.reset=function(){d=[]};var l=function(){var y=h.getUI().prop("clientHeight");y||(y=window.screen.height);return y};this.getScrollRepaintDelta=function(){return k};this.protectedBeforeUpdateUI=function(){d=[];var y=l();a.isDynamicUpdateModel()?(k=0,f=.5*y):(k=.5*y,f=1*y)};this.createPaintSection=function(){if(a.isScrollDynamicRepaint()){var y=
h.getUI().prop("scrollTop");var w=l();var B=y-f;y=y+w+f}else B=0,y=2147483647;return[B,y]};this.createRowsRange=function(){if(a.isScrollDynamicRepaint()){var y=this.createPaintSection();var w=y[1];y=a.searchRowIdx(y[0]);w=a.searchRowIdx(w)}else y=0,w=c.getRowsCount()-1;return[y,w]};this.protectedIsNeedCreatingRow=function(y,w,B,H){if(a.isScrollDynamicRepaint()){var I=d[y];if(I)if(y==w)!0===I&&(I=t(y,B)),I.remove();else return!0!==I&&h.getCellsContainer().append(I),!1;H||(d[y]=!0)}return!0};this.protectedAfterRepaint=
function(y,w,B){a.isScrollDynamicRepaint()&&setTimeout(function(){for(var H=g?g[0]:-1,I=g?g[1]:-2,P=a.isDynamicRepaintWithCache();H<=I;H++)if(H<y||H>w){var u=d[H];u&&(!0===u&&(u=t(H,B),P?d[H]=u:delete d[H]),u.remove())}g=[y,w]},10)};var t=function(y,w){y=c.getRow(y);return h.getUI().find("*[id*='"+w(y)+"']")},E=this.protectedUpdateByRowHide;this.protectedUpdateByRowHide=function(){a.isScrollDynamicRepaint()&&(d=[]);E()};var v=this.protectedUpdateByColumnHide;this.protectedUpdateByColumnHide=function(){a.isScrollDynamicRepaint()&&
(d=[]);v()};var J=this.protectedUpdateColumnWidth;this.protectedUpdateColumnWidth=function(){a.isScrollDynamicRepaint()&&(d=[]);J()}}
function KTableUIMainView(c,a){function h(J){this.isHorizontalScroll=function(){var y=d.getUI().prop("scrollLeft");return k!=y};this.isVerticalScroll=function(){var y=d.getUI().prop("scrollTop");return g!=y};this.isScrollToBottom=function(){var y=d.getUI().prop("scrollTop"),w=d.getUI().prop("clientHeight"),B=d.getUI().prop("scrollHeight");return y+w>=B-2};this.getLastScrollLeft=function(){return k};this.getLastScrollTop=function(){return g}}KTableUIManyRowsView.call(this,c,a);var d=this,g=0,k=0,f,
n,l=0;this.getName=function(){return"MainView"};this.getViewTag=function(){return KTableViewTag.MAIN};var t=this.protectedBeforeUpdateUI;this.protectedBeforeUpdateUI=function(){t();k=g=l=0};this.protectedBeforeRepaint=function(J){var y=this.createRowsRange(),w=y[0],B=y[1],H=0,I=c.getColumnsCount()-1;c.getCrossFrozenRenderMode()==KTCrossFrozenRenderMode.STUPID_LIGHT&&(w=Math.max(d.getMaxFrozenRowIdx()+1,w),H=d.getMaxFrozenColumnIdx()+1);if(J)(new Date).getTime(),d.setBlankFirstImmediately(!1),E(w,
B,function(P){d.setBlankFirstImmediately(P);J(w,B,H,I,P)});else return[w,B,H,I]};var E=function(J,y,w){if(a.isDynamicUpdateModel()){for(var B=J,H=y,I=!1;J<=y;J++)if(c.getRow(J).isSkeleton())I||(I=!0,B=J),H=J;else if(I)break;I?(w(!0),y=c.getFrozenRows(),a.fireDynamicUpdateModelEvent(B-y,H-y,w)):w()}else w()};this.protectedGetPaintRect=function(){var J=this.createPaintSection(),y=J[0];J=J[1];var w=a.getColX(d.getMaxFrozenColumnIdx()+1);return[y,J,w,2147483647]};var v=this.protectedAfterRepaint;this.protectedAfterRepaint=
function(J,y,w){v(J,y,w);if(a.isScrollDynamicRepaint()&&a.isDynamicUpdateModel()){J-=.5*a.getDynamicUpdateModelAliveDeltaRows();y+=a.getDynamicUpdateModelAliveDeltaRows();w=c.getFrozenRows();for(var B=c.getRowsCount();w<B;w++)w>J&&w<y||c.getRow(w).clearAsSkeleton()}};d.getUI().css("overflow","auto");d.getUI().scroll(function(J){a.notifyScrolling();clearTimeout(f);f=setTimeout(function(){a.notifyStopScroll()},1E3);a.isScrollDynamicRepaint()?(clearTimeout(n),n=setTimeout(function(){var y=d.getUI().prop("scrollTop");
d.getUI().prop("clientHeight");if(y<l-d.getScrollRepaintDelta()||y>l+d.getScrollRepaintDelta())d.repaint(),l=y;a.fireEvent("scroll",new h(J));g=d.getUI().prop("scrollTop");k=d.getUI().prop("scrollLeft")},50)):(a.fireEvent("scroll",new h(J)),g=d.getUI().prop("scrollTop"),k=d.getUI().prop("scrollLeft"))})}
function KTableUILeftFrozenView(c,a){KTableUIManyRowsView.call(this,c,a);var h=this;this.getName=function(){return"LeftView"};this.getViewTag=function(){return KTableViewTag.LEFT};var d=this.protectedBeforeUpdateUI;this.protectedBeforeUpdateUI=function(){d();k()};this.protectedBeforeRepaint=function(f){var n=this.createRowsRange(),l=n[0];n=n[1];var t=h.getMaxFrozenColumnIdx();c.getCrossFrozenRenderMode()==KTCrossFrozenRenderMode.STUPID_LIGHT&&(l=Math.max(h.getMaxFrozenRowIdx()+1,l));if(f)f(l,n,0,
t,h.isBlankFirstImmediately());else return[l,n,0,t]};this.protectedGetPaintRect=function(){var f=this.createPaintSection(),n=f[0];f=f[1];var l=h.getUI().width();return[n,f,0,l]};var g=this.protectedUpdateColumnWidth;this.protectedUpdateColumnWidth=function(){k();g()};var k=function(){var f=h.getMaxFrozenColumnIdx();f=a.getColX(f+1);h.getUI().width(f+1)};h.getUI().css("overflow","hidden")}
function KTableUITopFrozenView(c,a){KTableUIAbstractView.call(this,c,a);var h=this;this.getName=function(){return"TopView"};this.getViewTag=function(){return KTableViewTag.TOP};this.protectedBeforeUpdateUI=function(){var d=h.getMaxFrozenRowIdx();d=a.getRowY(d+1);h.getUI().height(d+1)};this.protectedBeforeRepaint=function(d){var g=h.getMaxFrozenRowIdx(),k=0,f=c.getColumnsCount()-1;c.getCrossFrozenRenderMode()==KTCrossFrozenRenderMode.STUPID_LIGHT&&(k=h.getMaxFrozenColumnIdx()+1);if(d)d(0,g,k,f);else return[0,
g,k,f]};this.protectedGetPaintRect=function(){var d=h.getUI().height(),g=a.getColX(h.getMaxFrozenColumnIdx()+1);return[0,d,g,2147483647]};h.getUI().css("overflow","hidden")}
function KTableUICornerFrozenView(c,a){KTableUIAbstractView.call(this,c,a);var h=this;this.getName=function(){return"CornerView"};this.getViewTag=function(){return KTableViewTag.LEFT&KTableViewTag.TOP};this.protectedBeforeUpdateUI=function(){var k=h.getMaxFrozenRowIdx();k=a.getRowY(k+1);h.getUI().height(k+1);g()};this.protectedBeforeRepaint=function(k){var f=h.getMaxFrozenRowIdx(),n=h.getMaxFrozenColumnIdx();if(k)k(0,f,0,n);else return[0,f,0,n]};this.protectedGetPaintRect=function(){return[0,h.getUI().height(),
0,h.getUI().width()]};var d=this.protectedUpdateColumnWidth;this.protectedUpdateColumnWidth=function(){g();d()};var g=function(){var k=h.getMaxFrozenColumnIdx();k=a.getColX(k+1);h.getUI().width(k+1)};h.getUI().css("overflow","hidden")}
function KTableUIEmbedFrozenView(c,a,h){KTableUIAbstractView.call(this,c,a);var d=this;this.getName=function(){return"EmbedView"};this.getViewTag=function(){return KTableViewTag.EMBED};this.protectedBeforeUpdateUI=function(){d.getUI().height(h.getHeight());d.getUI().width(h.getWidth())};this.protectedBeforeRepaint=function(){return[0,0,0,0]};this.protectedGetPaintRect=function(){var k=[h.getX(),h.getHeight(),h.getY(),h.getWidth()];h.setX(0);h.setY(0);return k};var g=this.protectedUpdateColumnWidth;
this.protectedUpdateColumnWidth=function(){d.getUI().width(h.getWidth());g()};d.getUI().css("overflow","hidden")}
function KTDefaultCellRender(c){var a=this,h,d,g,k,f,n,l,t,E,v,J,y,w,B=!1,H=2,I=1;this.setOutsideVisible=function(x){B=x};this.setPaddingHV=function(x,z){H=x;I=z};this.reset=function(){y=null};this.setContext=function(x,z,D,L,C,S,T,da,ea){h=x;d=z;g=D;k=L;f=C;n=S;l=T;t=da;E=ea;J=v=0};this.setTextOffset=function(x,z){v=x;J=z};this.calculateCellHeight=function(x){if(!g||!g.getValue())return 0;var z=pa();z.className=x;return la(z)};this.paintCellUI=function(x,z){if(g&&void 0!=g.getValue()){var D=pa(x),
L=a.getStyleValue("isWrapText"),C=a.getStyleValue("getVerticalAlign");"middle"==C?L?(C=la(D,x),D.style.left=v+"px",D.style.top=J+(E-C>>1)+"px",D.style.height=C+"px"):(C=E-2*I,C=(0>C?0:C)+"px",D.style.lineHeight=C,D.style.height=C,D.style.top=J+I+"px"):"bottom"==C?D.style.bottom=parseInt(x.style.height)-J-E+I+"px":D.style.top=J+I+"px";if(!0===a.getStyleValue("isVerticalText")){var S=a.getStyleValue("getTextAlign");"right"===S?(D.style.lineHeight="unset",D.style.top="unset",D.style.textAlign="center",
D.style.width="unset",D.style.left="unset",D.style.right=0):"left"===S?(D.style.lineHeight="unset",D.style.top="unset",D.style.textAlign="center"):(C=t-2*I,D.style.lineHeight=(0>C?0:C)+"px")}C=z?z:x;(S=C.firstChild)&&C.removeChild(S);C.appendChild(D);S=a.getStyleValue("isLineThrough");var T=a.getStyleValue("isUnderLine");S&&T?D.style.textDecoration="line-through underline":S?D.style.textDecoration="line-through":T&&(D.style.textDecoration="underline");if(B&&(y&&y[0]==k||(y=[k,W(k)]),T=y[1],!L&&!T[f])){S=
a.getStyleValue("getTextAlign");var da=L=-1;if("left"==S||"center"==S||null==S){L=0;for(var ea=c.getColumnsCount(),ka=f+1;ka<ea;ka++){var ra=T[ka]?T[ka]:h.getCellForDraw(ka);if(ra&&void 0!==ra.getValue())break;c.getColumn(ka).isHide()||(L+=c.getColumn(ka).getWidth())}}if("right"==S||"center"==S)if(da=0,!g.getTreeModel()||g.getTreeModel().isHorizontal())for(ka=f-1;0<=ka&&(!(ra=T[ka]?T[ka]:h.getCellForDraw(ka))||void 0===ra.getValue());ka--)c.getColumn(ka).isHide()||(da+=c.getColumn(ka).getWidth());
T=t;0<=L&&(T+=L,ea=T-w-H,D.style.width=(0>ea?0:ea)+"px");0<=da&&(ea=document.createElement("span"),ea.style.overflow="hidden",ea.style.position="absolute",ea.style.left=-da+"px",ea.style.width=T+da+"px",0>E&&(E=0),ea.style.height=E+"px",D.style.width="","center"==S?(D.style.whiteSpace="nowrap",S=la(D,x,"offsetWidth"),D.style.left=(t-S>>1)+da+"px"):(D.style.right=0,D.style.left=""),ea.appendChild(D),C.appendChild(ea));da=0<L||0<da}x.style.overflow=da?"visible":"hidden";z&&(z.style.overflow=da?"visible":
"hidden");g.getStyle()&&g.getStyle().getCursor()&&"auto"!=g.getStyle().getCursor()&&(x=document.createElement("div"),x.style.position="absolute",x.style.height=C.style.height,x.style.width=C.style.width,x.style.cursor=g.getStyle().getCursor(),x.style.backgroundImage="url(data:;base64,AAABAYA=)",C.appendChild(x));if(a.getStyleValue("isShrinkText")){z=a.getStyleValue("getFontSize");x=g.getValue();C=n-2*H-2;L=document.createElement("canvas").getContext("2d");L.font=z+"px Arial Blod";S=L.measureText(x);
for(S=S.width;S>C;)z-=.05,L.font=z+"px Arial Blod",S=L.measureText(x),S=S.width;D.style.fontSize=z+"px";D.style.transformOrigin="0";D.style.width="unset"}x=a.getStyleValue("getRotation");0<x&&(C=a.getStyleValue("getFontSize"),z=g.getValue(),L=document.createElement("canvas").getContext("2d"),L.font=C+"px Arial Blod",z=L.measureText(z).width-H,D.style.width=t+"px",x=x*Math.PI/180,L=a.getStyleValue("getTextAlign"),"right"===L?(D.style.left="unset",C/=2,L=a.getStyleValue("getVerticalAlign"),"top"===
L?u(x,C,D,z,!0):"middle"===L?(z=Math.sin(x)*(t/2-z/2),x=ha(x,C),D.style.top=-z+"px",D.style.right=x+"px"):P(x,C,D,!1)):"left"===L?(C/=2,L=a.getStyleValue("getVerticalAlign"),"top"===L?P(x,C,D,!0):"middle"===L?(z=(t/2-z/2)*Math.sin(x),x=ha(x,C),D.style.top=z+"px",D.style.left=x+"px"):u(x,C,D,z,!1)):(x=V(x,C,z)+I,z=a.getStyleValue("getVerticalAlign"),"top"===z?D.style.top=x+"px":"bottom"===z&&(D.style.bottom=x+"px"),D.style.left="0px"))}};var P=function(x,z,D,L){var C=V(x,2*z,t);x=ha(x,z);L?(D.style.top=
C+"px",D.style.left=x+"px"):(D.style.bottom=C+"px",D.style.right=x+"px")},u=function(x,z,D,L,C){if(L>t/2){var S=Math.atan(z/(L/2));L=I+z-L/2/Math.cos(S)*Math.cos(90*Math.PI/180-(x+S))}else L=Math.atan(z/(t/2-L+2*H)),L=z/Math.sin(L)*Math.sin(x-L)-I;x=ha(x,z);C?(D.style.top=-L+"px",D.style.right=x+"px"):(D.style.bottom=-L+"px",D.style.left=x+"px")},V=function(x,z,D){var L=Math.atan(z/2/(D/2));return D/2/Math.cos(L)*Math.sin(x-L)-z/2-I+z*Math.sin(90*Math.PI/180-x)},ha=function(x,z){z=Math.atan(z/2/(t/
2));return t/2/Math.cos(z)*Math.cos(x-z)-t/2},W=function(x){var z=[];c.visitMergeBlocks(x,x,-1,-1,function(D){for(var L=c.getRow(D.getRowIdxFrom()).getCellForDraw(D.getColIdxFrom()),C=D.getColIdxFrom();C<=D.getColIdxTo();C++)z[C]=L});return z},pa=function(x){w=H;var z=a.getStyleValue("getIndent"),D=a.getStyleValue("getRotation");if(0<z){var L=a.getStyleValue("getTextAlign");if("left"==L||null==L)L=document.createElement("span"),"undefined"!=typeof L.textContent?L.textContent="A":L.innerText="A",x=
la(L,x,"offsetWidth"),w+=x*z}L=document.createElement("span");L.style.paddingLeft=w+"px";L.style.paddingRight=H+"px";L.style.overflow="hidden";L.style.position="absolute";L.style.transform="rotate("+D+"deg)";L.style.left=v+"px";z=t-w-H;L.style.width=(0>z?0:z)+"px";"undefined"!=typeof L.textContent?L.textContent=g.getValue():L.innerText=g.getValue();a.getStyleValue("isVerticalText")&&(L.style.writingMode="vertical-lr",L.style.textOrientation="upright");return L},la=function(x,z,D){var L=x.style.left,
C=x.style.top;x.style.left="-32768px";x.style.top="-32768px";if(z){if(z=z.className){var S=z.split(" ");z="";for(var T=0;T<S.length;T++)0!=S[T].indexOf(KTBorderStyle.CSS_ID_PREFIXE)&&(0<z.length&&(z+=" "),z+=S[T])}else z="";x.className=z}document.body.appendChild(x);D=x[D?D:"offsetHeight"];document.body.removeChild(x);x.className="";x.style.left=L;x.style.top=C;return D};this.getStyleValue=function(x){return c.getStyleValue(g,d,h,"getStyle",x,null)};this.getCurrentRow=function(){return h};this.getCurrentCol=
function(){return d};this.getCell=function(){return g};this.getCurrentRowIdx=function(){return k};this.getCurrentColIdx=function(){return f};this.getCellWidth=function(){return n};this.getCellHeight=function(){return l};this.getTextAreaWidth=function(){return t};this.getTextAreaHeight=function(){return E};this.protectedMethod=new function(){this.setTextAreaHeight=function(x){E=x}}}
function KTDefaultEmbedObjectRender(){var c;this.setViewTag=function(a){c=a};this.getViewTag=function(){return c};this.paintEmbedObject=function(a,h){}}
function KTDefaultTreeHandlerRender(c){var a=9,h,d;this.setHandlerSize=function(n){a=n};this.setUiDependence=function(n){h=n};this.setMergeBlock=function(n){d=n};this.create=function(n,l,t,E,v,J,y){if(n.isHorizontal()){var w=E;var B=11*n.getLevel();var H=J;var I=2+a+2+1;var P=E;var u=B+I}else w=17*n.getLevel(),B=v,H=2+a+2+3,I=y,P=w+H,u=v;if(n.isHorizontal()){var V=J-a-2>>1;var ha=2}else{V=2;var W=c.getRow(l);ha=c.getColumn(t);var pa=W.getCell(t);"top"==c.getStyleValue(pa,ha,W,"getStyle","getVerticalAlign",
"top")?(W=c.getStyleValue(pa,ha,W,"getStyle","getFontSize",20),ha=Math.max(2,W-a-2>>1)):ha=y-a-2>>1}t=(W=k(n,l,t))||n.isHaveHandlerAlways();l=null;t&&(l=f("div",w,B,H,I),l.style.cursor="pointer",w=f("div",V,ha,a,a),w.style.border="1px solid #8A9EBF","undefined"!=typeof w.style.borderRadius&&(w.style.borderRadius="3px"),w.style.backgroundColor="#FFFFFF",l.appendChild(w),n.isExpanded()?(B=a-2,B=f("div",1,1,B,B>>1),B.style.borderBottom="1px solid black",w.appendChild(B)):(H=a-2>>1,B=f("div",1,1,H,H),
B.style.borderBottom="1px solid black",B.style.borderRight="1px solid black",H=f("div",1+H,1+H,H,H),H.style.borderTop="1px solid black",H.style.borderLeft="1px solid black",w.appendChild(B),w.appendChild(H)));w=null;if(c.isMultiTreeSupported()){t=!t;V=E+V+(a>>1);w=v+ha+(a>>1);ha=document.createDocumentFragment();B=n.isHorizontal();H=n.getLevel();I=n.getLastChildLevel();n=W&&n.isExpanded();W=0<=I?n?0:H-I:0;var la=H-W;if(B){H=E;I=w;pa=J;var x=0}else H=V,I=v,pa=0,x=y;for(var z=0;z<la;z++)g(ha,B,H,I,
pa,x),H+=B?0:17,I+=B?11:0;for(z=0;z<W;z++){la=ha;var D=B,L=pa,C=x;L+=D?-4:a>>1;C+=D?a>>1:-4;L=f("div",H,I,L,C);la.appendChild(L);D?(L.style.borderTop="1px dotted #8A9EBF",L.style.borderRight="1px dotted #8A9EBF"):(L.style.borderLeft="1px dotted #8A9EBF",L.style.borderBottom="1px dotted #8A9EBF");H+=B?0:17;I+=B?11:0}H=B?V:H;I=B?I:w;n&&g(ha,B,H,I,pa,x);t&&(n=f("div",H,I,0,0),ha.appendChild(n),n.style.border="1px solid #8A9EBF");w=ha}n=[l,P,u,w];P=n[0];u=n[1];l=n[2];n=n[3];E=f("span",u,l,E+J-u,v+y-l);
return[P,E,n]};var g=function(n,l,t,E,v,J){t=f("div",t,E,v,J);n.appendChild(t);l?t.style.borderTop="1px dotted #8A9EBF":t.style.borderLeft="1px dotted #8A9EBF"},k=function(n,l,t){if(n.isHorizontal())for(var E=c.getColumnsCount()-1;t<E&&(t++,d&&d.isContainCell(l,t)););else for(E=c.getRowsCount()-1;l<E&&(l++,d&&d.isContainCell(l,t)););return(l=c.getRow(l).getCellForDraw(t))&&l.getTreeModel()&&l.getTreeModel().getLevel()>n.getLevel()},f=function(n,l,t,E,v){n=document.createElement(n);n.style.overflow=
"hidden";n.style.position="absolute";n.style.left=l+"px";n.style.top=t+"px";n.style.width=(0>E?0:E)+"px";n.style.height=(0>v?0:v)+"px";return n};this.protectedMethod={getTable:function(){return c},getUiDependence:function(){return h},isTreeNodeHasChildren:k,createAbsoluteHtmlElement:f}}
function KTableUIDraggableAdjustingHandler(){var c,a,h,d=-1,g=-1,k=-1,f=-1,n=-1,l=-1,t=!0,E=!0,v,J=-1,y=-1,w=!1,B,H,I;this.setContext=function(x,z,D){c=x;h=z;a=D;h.on("mouseenter",u);h.on("mouseleave",pa)};this.mouseEventHandler=function(x,z){if(!a.isScrolling()&&c.getDraggableAdjusting())if("mousemove"==x)a:{y=J=-1;var D=z.getXAtTable(),L=z.getYAtTable(),C=D>n-6;x=L>l-6;var S=C||x,T=z.isCellPointed()&&!z.isPointTreeHandler();if((T||S)&&!z.isPointScrollBar()&&D<n&&L<l&&(D<d||L<g)){z=z.getMouseTargetModel();
if(E&&(T||C)){C=z?z.getColIndex():-1;S=-1;if(-1==C)S=c.getColumnsCount();else if(D>a.getColX(C+1)-3)S=C+1;else for(;0<C&&D<a.getColX(C)+3&&(S=C,C--,c.getColumn(C).isHide()););if(0<S&&v.isColumnDraggable(c,S-1)){y=S;h.css("cursor","col-resize");break a}}if(t&&(T||x)){z=z?z.getRowIndex():-1;D=-1;if(-1==z)D=c.getRowsCount();else if(L>a.getRowY(z+1)-3)D=z+1;else for(;0<z&&L<a.getRowY(z)+3&&(D=z,z--,c.getRow(z).isHide()););if(0<D&&v.isRowDraggable(c,D-1)){J=D;h.css("cursor","row-resize");break a}}}h.css("cursor")&&
h.css("cursor","")}else if("mousedown"==x){T=z||window.event;C=$(".chart-change-menu");x=T.getOriginalEvent().clientX;T=T.getOriginalEvent().clientY;if(0<C.length){C=C[0].getBoundingClientRect();S=C.x+C.width;var da=C.y+C.height;x=x>C.x&&x<S&&T>C.y&&T<da}else x=void 0;!x&&($(".chart-change-menu")&&$(".chart-change-menu").remove(),$(".chart-selected")&&$(".chart-selected").removeClass("chart-selected"),x=0<y,T=0<J,x||T)&&(z.stop(),w=!0,C=$("<div>"),C.css("z-index",65535),C.css("position","absolute"),
C.css("top",0),C.css("left",0),C.css("width","100%"),C.css("height","100%"),C.css("background-color","rgba(255, 255, 255, 0.1)"),I=C,I.on("mousemove",V),I.on("mouseup",ha),I.appendTo(h),C=$("<div>"),C.css("z-index",65534),C.css("position","absolute"),C.css("top",0),C.css("left",0),C.css("width",0),C.css("height",0),C.css("border-style","dashed"),C.css("border-width","0"),C.css("border-color","#000"),C.css("background-color","rgba(0, 0, 0, 0.2)"),H=C,H.appendTo(h),x?(L=a.getColX(y-1),D=L-(L<k?0:a.getScrollLeft()),
B=c.getColumn(y-1).getWidth(),C=a.getRowY(c.getRowsCount())-a.getScrollTop(),L=z.getOriginalEvent().screenX,H.css("border-right-width","1px"),H.css("left",D),H.css("width",B),H.css("height",C),z=y-1,D=-Math.max(0,c.getColumn(z).getWidth()-v.getMinColumnWidthLimited(c,z))):T&&(L=a.getRowY(J-1),D=L-(L<f?0:a.getScrollTop()),B=c.getRow(J-1).getHeight(),C=a.getColX(c.getColumnsCount())-a.getScrollLeft(),L=z.getOriginalEvent().screenY,H.css("border-bottom-width","1px"),H.css("top",D),H.css("height",B),
H.css("width",C),z=J-1,D=-Math.max(0,c.getRow(z).getHeight()-v.getMinRowHeightLimited(c,z))),x||T)&&(H.data("kt_startMouse",L),H.data("kt_minDelta",D))}};var P=function(){var x=c.getDraggableAdjusting(),z=x[0],D=x[1];v=(v=x[2])?v:new KTableUIDraggableAdjustingHandler.CustomExpendor;t=0!==D;E=0!==z;z=z?0<z?z:c.getRowsCount():0===z?0:c.getFrozenRows();D=D?0<D?D:c.getColumnsCount():0===D?0:c.getFrozenColumns();g=a.getRowY(z)+3;d=a.getColX(D)+3;f=a.getRowY(c.getFrozenRows());k=a.getColX(c.getFrozenColumns());
l=a.getRowY(c.getRowsCount())+3;n=a.getColX(c.getColumnsCount())+3},u=function(x){c.getDraggableAdjusting()&&P()},V=function(x){w=!0;x=W(x);x=B+x;0<y?H.css("width",x):H.css("height",x)},ha=function(x){w&&(x=W(x),0<y?v.columnDraggedAction(c,y-1,x):v.rowDraggedAction(c,J-1,x));la();P()},W=function(x){x=(0<y?x.screenX:x.screenY)-H.data("kt_startMouse");var z=H.data("kt_minDelta");x<z&&(x=z);return x},pa=function(x){la()},la=function(){w=!1;y=-1;H&&H.remove();I&&I.remove()}}
KTableUIDraggableAdjustingHandler.CustomExpendor=function(){this.isRowDraggable=function(c,a){return!0};this.isColumnDraggable=function(c,a){return!0};this.getMinRowHeightLimited=function(c,a){return 3};this.getMinColumnWidthLimited=function(c,a){return 4};this.rowDraggedAction=function(c,a,h){var d=c.isSyncUIWhenModelChanged();c.setSyncUIWhenModelChanged(!0);a=c.getRow(a);a.setHeight(a.getHeight()+h);c.setSyncUIWhenModelChanged(d)};this.columnDraggedAction=function(c,a,h){var d=c.isSyncUIWhenModelChanged();
c.setSyncUIWhenModelChanged(!0);a=c.getColumn(a);a.setWidth(a.getWidth()+h);c.setSyncUIWhenModelChanged(d)};this.getTailBlankForDragging=function(){return 60}};function KTDiagonalRender(){this.create=function(d,g,k,f,n,l){try{var t=document.createElement("canvas");t.width=n;t.height=l;var E=k,v=g.getLinkToRows(),J=0,y=Array(v.length+2);y[0]=J;for(var w=0;w<v.length;w++){for(var B=0;B<v[w];B++)J+=d.getRow(E++).getHeight();y[w+1]=J}y[v.length+1]=l;l=f;var H=g.getLinkToColumns();E=0;var I=Array(H.length+2);I[0]=E;for(v=0;v<H.length;v++){for(J=0;J<H[v];J++)E+=d.getColumn(l++).getWidth();I[v+1]=E}I[H.length+1]=n;var P=t.getContext("2d"),u=d.getRow(k),V=d.getColumn(f),
ha=u.getCell(f),W=d.getStyleValue(ha,V,u,"getBorder","getRightBorderColor","#aaaaaa");P.save();P.strokeStyle=W;P.lineWidth=.8;var pa=I[I.length-1],la=y[y.length-1];for(n=1;n<y.length;n++)P.moveTo(0,0),P.lineTo(pa,y[n]);for(n=1;n<I.length;n++)P.moveTo(0,0),P.lineTo(I[n],la);P.stroke();P.restore();var x=d.getRow(k),z=d.getColumn(f),D=x.getCell(f),L=d.getStyleValue(D,z,x,"getStyle","getFontSizeWithUnit"),C=d.getStyleValue(D,z,x,"getStyle","getFontName");L&&C&&(P.font=L+" "+C);d=[];var S=I[I.length-1],
T=y[y.length-1];k=[0,0];for(f=0;f<y.length-1;f++){var da=[S,y[f]],ea=[S,y[f+1]];d.push([k,da,ea])}for(f=I.length-1;0<f;f--)da=[I[f],T],ea=[I[f-1],T],d.push([k,da,ea]);for(y=0;y<d.length;y++){var ka=d[y];var ra=[Math.floor((ka[0][0]+ka[1][0]+ka[2][0])/3+.5),Math.floor((ka[0][1]+ka[1][1]+ka[2][1])/3+.5)];I=[0,0];var sa=ra[0]-I[0];var q=0==sa?PI/2:Math.atan((ra[1]-I[1])/sa);var A=g.getText(y);P.save();if(g.isLean(y)){I=P;S=A;ea=ra;T=q;k=!0;for(da=0;da<S.length;da++)if(127<S.charCodeAt(da)){k=!1;break}I.translate(ea[0],
ea[1]);I.rotate(T);var F=h(I,S,!0,T);I.translate(F[0],F[1]);if(k)I.fillText(S,0,0);else for(da=ea=0;da<S.length;da++){var N=S.charAt(da);I.translate(ea,0);I.rotate(-T);I.fillText(N,0,0);I.rotate(T);ea=I.measureText(N).width}}else{I=P;S=A;T=ra;var b=h(I,S,!1,q);I.fillText(S,T[0]+b[0],T[1]+b[1])}P.restore()}return t}catch(m){return null}};var c=[[Math.PI/18,.1],[Math.PI/12,.2],[Math.PI/9,.3],[Math.PI/6,.4],[Math.PI/2,.5]],a=[[Math.PI/9,.2],[Math.PI/6,.3],[Math.PI/5,.4],[Math.PI/4,.6],[Math.PI/2,.7]],
h=function(d,g,k,f){k=k?a:c;var n=Math.abs(f);f=.5;for(var l=0;l<k.length;l++)if(n<=k[l][0]){f=k[l][1];break}g=d.measureText(g);k=-g.width*f;g=d.measureText("\u58f9");return[k,.5*g.width]}};function KTable(){var c=this,a="table"+ ++KTable.iFlowId,h=new KTListenerProxy,d=[],g=[],k=new KTMergeBlockSet,f,n,l=[],t=new KTStyleManager,E=new KTSelectionModel(this),v,J,y,w,B,H,I=0,P=0,u=KTCrossFrozenRenderMode.STUPID_HEAVY,V,ha=!0,W=!1,pa=!1,la=!0,x,z,D,L=!1;this.getId=function(){return a};var C=function(){v||(v=new KTableUI(c),v.addListener("scroll",ra),v.addListener("mousedown",A),v.addListener("click",A),v.addListener("click",ka));return v};this.setUICustomStyleMap=function(b){J=b};this.getUICustomStyleMap=
function(){return J};this.getUI=function(){return C().getHtmlElement()};this.addColumn=function(b){return this.insertColumn(d.length,b)};this.addColumns=function(b){for(var m=0;m<b;m++)this.addColumn()};this.insertColumn=function(b,m){if(0>b||b>d.length)throw Error("Illegal argument.");m=new KTColumn(sa,m);d.splice(b,0,m);for(var p=0;p<g.length;p++)g[p].$innerInsertCell(b);la&&k.syncMergeBlocks(!1,b,!0);q(m,KTableUI.INSERT_COL);return m};this.removeColumn=function(b){if(0>b||b>d.length)throw Error("Illegal argument.");
var m=d[b];m.$innerDestroy();d.splice(b,1);for(var p=0;p<g.length;p++)g[p].$innerRemoveCell(b);la&&k.syncMergeBlocks(!1,b,!1);q(m,KTableUI.REMOVE_COL)};this.removeAllColumns=function(){for(var b=d.length-1;0<=b;b--)d[b].$innerDestroy();d.length=0;k.clear();q(null,KTableUI.REMOVE_COL)};this.getColumnsCount=function(){return d.length};this.getColumn=function(b){var m=typeof b;if("number"==m){if(0>b||b>d.length)throw Error("Illegal argument.");return d[b]}if("string"==m){for(m=0;m<d.length;m++)if(d[m].getKey()==
b)return d[m];return null}throw Error("Unknown argument.");};this.getColumnIndex=function(b){var m=!1;if(b instanceof KTColumn)m=!0;else if("string"!=typeof b)throw Error("Unknown argument.");for(var p=0;p<d.length;p++)if(m){if(d[p]==b)return p}else if(d[p].getKey()==b)return p;return-1};this.addRow=function(){return this.insertRow(g.length)};this.addRows=function(b){for(var m=0;m<b;m++)this.addRow()};this.insertRow=function(b){if(0>b||b>g.length)throw Error("Illegal argument.");var m=new KTRow(this.getColumnsCount(),
sa);g.splice(b,0,m);la&&k.syncMergeBlocks(!0,b,!0);q(m,KTableUI.INSERT_ROW);return m};this.removeRow=function(b){if(0>b||b>g.length)throw Error("Illegal argument.");var m=g[b];m.$innerDestroy();g.splice(b,1);la&&k.syncMergeBlocks(!0,b,!1);q(m,KTableUI.REMOVE_ROW)};this.removeAllRows=function(){for(var b=g.length-1;0<=b;b--)g[b].$innerDestroy();g.length=0;k.clear();q(null,KTableUI.REMOVE_ROW)};this.getRowsCount=function(){return g.length};this.getRow=function(b){return g[b]};this.getRowIndex=function(b){for(var m=
0;m<g.length;m++)if(g[m]==b)return m;return-1};this.updateUI=function(b,m){C().updateUI(b,m)};var S,T;this.lazyAppendData=function(b){b?(T=c.getRowsCount(),S=c.isSyncUIWhenModelChanged(),c.setSyncUIWhenModelChanged(!1)):(C().repaintAfterLazyAppendData(T),c.setSyncUIWhenModelChanged(S))};this.lazyAppendDataByTree=function(b,m){b?(S=c.isSyncUIWhenModelChanged(),c.setSyncUIWhenModelChanged(!1),C().showPromptForLazyAppendData(!0)):(C().showPromptForLazyAppendData(!1),m.setExpanded(!1),c.setSyncUIWhenModelChanged(!0),
m.setExpanded(!0),c.setSyncUIWhenModelChanged(S))};this.setLargeDataMode=function(b,m){C().setScrollDynamicRepaint(b,m)};this.isLargeDataMode=function(){return C().isScrollDynamicRepaint()};this.setHugeModelUpdateListener=function(b,m){C().setScrollDynamicUpdateModelListener(b,m)};this.setSyncUIWhenModelChanged=function(b){C().setSyncUIWhenModelChanged(b)};this.isSyncUIWhenModelChanged=function(){return C().isSyncUIWhenModelChanged()};this.setSyncMergeBlockWhenModelChanged=function(b){la=b};this.isSyncMergeBlockWhenModelChanged=
function(){return la};this.setCellRender=function(b){y=b};this.getCellRender=function(){y||(y=new KTDefaultCellRender(this));return y};this.setDiagonalRender=function(b){w=b};this.getDiagonalRender=function(){w||(w=new KTDiagonalRender);return w};this.setEmbedObjectRender=function(b){B=b};this.getEmbedObjectRender=function(){B||(B=new KTDefaultEmbedObjectRender);return B};this.setTreeHandlerRender=function(b){H=b};this.getTreeHandlerRender=function(){H||(H=new KTDefaultTreeHandlerRender(this));return H};
this.getStyleManager=function(){return t};this.addMergeBlock=function(b){k.append(b)&&q(b,KTableUI.ADD_MERGEBLOCK)};this.addMergeBlocks=function(b){k.appendArray(b)};this.removeMergeBlock=function(b){k.remove(b)&&q(b,KTableUI.REMOVE_MERGEBLOCK)};this.clearMergeBlocks=function(){k.clear();q(null,KTableUI.REMOVE_MERGEBLOCK)};this.bucketingMergeBlocks=function(b){b&&k.requestBucketing();k.bucketing(c.getRowsCount(),c.getColumnsCount(),I,P)};this.searchMergeBlock=function(b,m){return k.search(b,m,I,P)};
this.visitMergeBlocks=function(b,m,p,O,K){b=0>b?0:b;m=0>m?c.getRowsCount()-1:m;p=0>p?0:p;O=0>O?c.getColumnsCount()-1:O;k.visit(K,b,m,p,O,I,P)};this.visitAllMergeBlocks=function(b){k.visitAll(b)};this.setMergeBlockTextVisibleAlways=function(b){L=b};this.isMergeBlockTextVisibleAlways=function(){return L};this.setStyle=function(b){f=b};this.getStyle=function(){return f};this.setBorder=function(b){n=b};this.getBorder=function(){return n};this.getStyleValue=function(b,m,p,O,K,R){if(b&&(b=b[O]())&&((b=
b[K]())||0===b||!1===b))return b;if(b=m[O]())if((b=b[K]())||0===b||!1===b)return b;if(b=p[O]())if((b=b[K]())||0===b||!1===b)return b;if(b=c[O]())if((b=b[K]())||0===b||!1===b)return b;return R};this.addEmbedObject=function(b){if(0<=da(b))throw Error("EmbedObjcet ID already exist.");b.$innerBindChangeListener(ea);l.push(b)};this.removeEmbedObject=function(b){var m=da(b);0<=m&&(b=l[m],b.$innerBindChangeListener(null),l.splice(m,1))};this.getEmbedObject=function(b){b=da(new KTEmbedObject(b));return 0<=
b?l[b]:null};var da=function(b){for(var m=0;m<l.length;m++)if(b.getId()==l[m].getId())return m;return-1};this.getEmbedObjects=function(){return l};var ea=function(b,m,p,O){sa(b,m,p,O)};this.addCellClickListener=function(b){h.addListener("cell-click",b)};this.removeCellClickListener=function(b){h.removeListener("cell-click",b)};this.addTreeExpandListener=function(b){h.addListener("tree-expand",b)};this.removeTreeExpandListener=function(b){h.removeListener("tree-expand",b)};var ka=function(b,m){if(m.isCellPointed()){b=
m.getMouseTargetModel();var p=b.getCell();if(m.isPointTreeHandler()&&m.isLeftButton()){m=c.isSyncUIWhenModelChanged();c.setSyncUIWhenModelChanged(!0);var O=p.getTreeModel();O.setExpanded(!O.isExpanded());c.setSyncUIWhenModelChanged(m);b=new KTTreeExpandEvent(p,b.getRowIndex(),b.getColIndex());h.fireListener("tree-expand",b)}else{O=m.getOriginalEvent();a:{var K=b.getRowIndex();var R=b.getColIndex();if(K=c.searchMergeBlock(K,R))for(R=K.getRowIdxFrom();R<=K.getRowIdxTo();R++)for(var X=c.getRow(R),Y=
K.getColIdxFrom();Y<=K.getColIdxTo();Y++){var aa=X.getCell(Y,!0);if(aa){K=aa;break a}}K=null}b=new KTCellClickEvent(O,K?K:p,b,m);h.fireListener("cell-click",b)}}};this.addScrollToBottomListener=function(b){h.addListener("scroll-to-bottom",b)};this.removeScrollToBottomListener=function(b){h.removeListener("scroll-to-bottom",b)};var ra=function(b,m){m.isVerticalScroll()&&m.isScrollToBottom()&&h.fireListener("scroll-to-bottom",m)};this.addUIListener=function(b,m){C().addListener(b,m)};this.removeUIListener=
function(b,m){C().removeListener(b,m)};var sa=function(b,m,p,O){if(v&&v.isSyncUIWhenModelChanged()){if(b instanceof KTCell.Path){var K=c.getColumn(b.getColIndex()),R=c.getRowIndex(b.getRow());b.$innerSetInfo(R,K);if(m==KTCell.TREE_EXPANDING){m=new KTTreeStateChangedEvent(c,b);h.fireListener("tree-state-changed",m);if(!m.isPreventDefault()){if(v){var X=v.isSyncUIWhenModelChanged();v.setSyncUIWhenModelChanged(!1)}K=0;var Y=b.getCell().getTreeModel();m=Y.isHorizontal();p=Y.isExpanded();O=b.getRowIndex();
b=b.getColIndex();for(var aa=m?O:b,Z=R=m?N(O,b):F(O,b),qa=m?c.getColumnsCount():c.getRowsCount(),ja=[],fa=32767;Z<qa;){var ba=m?aa:Z,ma=m?Z:aa,na=Z;Z=m?N(aa,Z):F(Z,aa);var e=Z-1;ba=c.getRow(ba).getCell(ma,!0);if(!ba||!ba.getTreeModel())break;ma=ba.getTreeModel();var r=ma.getLevel();if(r<=Y.getLevel()||m!=ma.isHorizontal())break;if(p)for(ba=!1,r<=fa&&(fa=ma.isExpanded()?32767:r,ba=!0);na<=e;na++)ja.push(ba),ba&&K++;else for(;na<=e;na++)ba=m?c.getColumn(na):c.getRow(na),ba.isHide()||K++,ba.setHide(!0)}if(p){if(D)for(Y=
m?Math.min(D[0],c.getRowsCount()):Math.min(D[1],c.getColumnsCount()),na=aa+1;na<Y;na++)for(aa=ja,Z=R,qa=na,fa=m,e=Z,ba=Z+aa.length,ma=32767;e<ba;){var G=fa?qa:e,M=fa?e:qa,Q=e;e=fa?N(qa,e):F(e,qa);r=e-1;if((G=c.getRow(G).getCell(M,!0))&&G.getTreeModel()&&(G=G.getTreeModel(),fa==G.isHorizontal()))if(M=G.getLevel(),M<=ma)ma=G.isExpanded()?32767:M;else for(;Q<=r;Q++)aa[Q-Z]=!1}for(na=0;na<ja.length;na++)Z=na+R,(m?c.getColumn(Z):c.getRow(Z)).setHide(!ja[na])}R=K;if(!(0>=l.length))for(K=m?b:O,O=m?c.getColumn(b).getWidth():
c.getRow(O).getHeight(),O=(p?O:-O)*R,p=0;p<l.length;p++)b=l[p],m&&b.getColFrom()>K?b.setX(b.getX()+O):b.getRowFrom()>K&&b.setY(b.getY()+O);v&&(v.setSyncUIWhenModelChanged(X),v.updateUI(!0))}return}}v.propertyChangeHandler(b,m,p,O)}},q=function(b,m){v&&v.isSyncUIWhenModelChanged()&&v.modelChangeHandler(b,m)};this.getSelectionModel=function(){return E};this.setSelectionRender=function(b){V=b};this.getSelectionRender=function(){return V};this.setMouseDownSelectingMode=function(b){ha=b};this.isMouseDownSelectingMode=
function(){return ha};var A=function(b,m){if(!(ha&&"mousedown"!=b||!ha&&"mousedown"==b||m.isStopped())&&m.isCellPointed()&&(b=c.getSelectionModel(),b.getMode()!=KTSelectionModel.MODE_NONE)){var p=m.getMouseTargetModel();if(p instanceof KTCell.Path){if(b.isPolicySetting(KTSelectionModel.POLICY_ROW)){if(p.getRowIndex()<c.getFrozenRows())return;p=b.createRowTarget(p.getRowIndex())}else if(b.isPolicySetting(KTSelectionModel.POLICY_COLUMN)){if(p.getColIndex()<c.getFrozenColumns())return;p=b.createColumnTarget(p.getColIndex())}else p=
b.createCellTarget(p.getRowIndex(),p.getColIndex());m.isCtrlDown()&&b.getMode()==KTSelectionModel.MODE_MULTI?b.isContains(p)?b.removeSelected(p):b.addSelected(p):m.isShiftDown()&&b.getMode()==KTSelectionModel.MODE_MULTI?(b.isContains(p)&&b.removeSelected(p),b.appendSelected(p)):b.hasSelected()?b.isSingleSelected()&&b.isContains(p)||(b.removeAllSelecteds(),b.addSelected(p)):b.addSelected(p)}}};this.setFrozenRows=function(b){if(I!=b){var m=I;I=b;k.requestBucketing();sa(this,KTableUI.FROZEN_ROW,I,m)}};
this.getFrozenRows=function(){return I};this.setFrozenColumns=function(b){if(P!=b){var m=P;P=b;k.requestBucketing();sa(this,KTableUI.FROZEN_COL,P,m)}};this.getFrozenColumns=function(){return P};this.setCrossFrozenRenderMode=function(b){u=b};this.getCrossFrozenRenderMode=function(){return u};this.popupMenu=function(b,m,p,O,K){C().popupMenu(b,m,p,O,K)};this.setMultiTreeSupported=function(b,m,p){D=b?[m,p]:null};this.isMultiTreeSupported=function(){return D?!0:!1};var F=function(b,m){return(m=c.searchMergeBlock(b,
m))?m.getRowIdxTo()+1:b+1},N=function(b,m){return(b=c.searchMergeBlock(b,m))?b.getColIdxTo()+1:m+1};this.isColumnFitVisibleWidth=function(){return W};this.setColumnFitVisibleWidth=function(b){W=b};this.isAutoAdjustRowHeight=function(){return pa};this.setAutoAdjustRowHeight=function(b){pa=b};this.selectByPoint=function(b,m){return C().selectByPoint(b,m)};this.setScrollerVisible=function(b,m,p){C().setScrollerVisible(b,m,p)};this.keepScrollStatus=function(){return C().keepScrollStatus()};this.restoreScrollStatus=
function(b){C().restoreScrollStatus(b)};this.scrollCellVisible=function(b,m,p){C().scrollCellVisible(b,m,p)};this.setDraggableAdjusting=function(b,m,p,O){x=b?[m,p,O]:null};this.getDraggableAdjusting=function(){return x};this.relayoutViews=function(){C().relayoutViews()};this.addTreeStateChangedListener=function(b){h.addListener("tree-state-changed",b)};this.removeTreeStateChangedListener=function(b){h.removeListener("tree-state-changed",b)};this.setCellAcrossListener=function(b){z=b};this.getCellAcrossListener=
function(){return z}}KTable.iFlowId=0;var KTableViewTag=new function(){this.MAIN=0;this.LEFT=4096;this.TOP=256;this.EMBED=16},KTCrossFrozenRenderMode=new function(){this.STUPID_HEAVY=0;this.STUPID_LIGHT=1};function KTPopupMenuItem(c){var a=c,h;this.setText=function(d){a=d};this.getText=function(){return a};this.setUserObject=function(d){h=d};this.getUserObject=function(){return h}}
function KTAbstractMouseEvent(c,a,h,d,g){var k=!1;this.stop=function(){k=!0};this.isStopped=function(){return k};this.getX=function(){return d};this.getY=function(){return g};this.getXAtTable=function(){return a};this.getYAtTable=function(){return h};this.isCtrlDown=function(){return c.ctrlKey};this.isShiftDown=function(){return c.shiftKey};this.isLeftButton=function(){return 1==c.which};this.isRightButton=function(){return 3==c.which}}
function KTCellClickEvent(c,a,h,d){KTAbstractMouseEvent.call(this,c,d.getXAtTable(),d.getYAtTable(),d.getX(),d.getY());this.getCell=function(){return a};this.getCol=function(){return h.getCol()};this.getRow=function(){return h.getRow()};this.getColIdx=function(){return h.getColIndex()};this.getRowIdx=function(){return h.getRowIndex()};this.getXCellAtTable=function(){return d.getXYCellAtTable()[0]};this.getYCellAtTable=function(){return d.getXYCellAtTable()[1]}}
function KTTreeExpandEvent(c,a,h){this.isExpanded=function(){return c.getTreeModel().isExpanded()};this.getCell=function(){return c};this.getRowIdx=function(){return a};this.getColIdx=function(){return h}}
function KTTreeStateChangedEvent(c,a){var h=!1;this.preventDefault=function(){h=!0};this.isPreventDefault=function(){return h};this.getTable=function(){return c};this.getRowIndex=function(){return a.getRowIndex()};this.getColIndex=function(){return a.getColIndex()};this.getRow=function(){return a.getRow()};this.getCol=function(){return a.getCol()};this.getCell=function(){return a.getCell()};this.createCellId=function(d,g){d=d||a.getRow();g=g||a.getCol();return KTableUIAbstractView.createCellId(d,
g)}};
//qingVersionTag: 20250324