var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(w,g,y){w instanceof String&&(w=String(w));for(var I=w.length,D=0;D<I;D++){var L=w[D];if(g.call(y,L,D,w))return{i:D,v:L}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(w,g,y){if(w==Array.prototype||w==Object.prototype)return w;w[g]=y.value;return w};$jscomp.getGlobal=function(w){w=["object"==typeof globalThis&&globalThis,w,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<w.length;++g){var y=w[g];if(y&&y.Math==Math)return y}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(w,g){var y=$jscomp.propertyToPolyfillSymbol[g];if(null==y)return w[g];y=w[y];return void 0!==y?y:w[g]};
$jscomp.polyfill=function(w,g,y,I){g&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(w,g,y,I):$jscomp.polyfillUnisolated(w,g,y,I))};$jscomp.polyfillUnisolated=function(w,g,y,I){y=$jscomp.global;w=w.split(".");for(I=0;I<w.length-1;I++){var D=w[I];if(!(D in y))return;y=y[D]}w=w[w.length-1];I=y[w];g=g(I);g!=I&&null!=g&&$jscomp.defineProperty(y,w,{configurable:!0,writable:!0,value:g})};
$jscomp.polyfillIsolated=function(w,g,y,I){var D=w.split(".");w=1===D.length;I=D[0];I=!w&&I in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var L=0;L<D.length-1;L++){var Q=D[L];if(!(Q in I))return;I=I[Q]}D=D[D.length-1];y=$jscomp.IS_SYMBOL_NATIVE&&"es6"===y?I[D]:null;g=g(y);null!=g&&(w?$jscomp.defineProperty($jscomp.polyfills,D,{configurable:!0,writable:!0,value:g}):g!==y&&(void 0===$jscomp.propertyToPolyfillSymbol[D]&&(y=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[D]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(D):$jscomp.POLYFILL_PREFIX+y+"$"+D),$jscomp.defineProperty(I,$jscomp.propertyToPolyfillSymbol[D],{configurable:!0,writable:!0,value:g})))};$jscomp.polyfill("Array.prototype.find",function(w){return w?w:function(g,y){return $jscomp.findInternal(this,g,y).v}},"es6","es3");
(function(){function w(){var a,c;this.setExportType=function(l){a=l};this.setJsonModelWrapper=function(l){c=l};this.toJsonObject=function(){var l={};l.exportType=a;l.modelWrapper=JSON.stringify(c);return l}}function g(){var a=210,c=297,l=g.VERITICAL,e=18,A=18,u=25,K=25,F=g.SCALING,k=100,h=1,B=1,E=new y,H=new y,G=!0,q=!0,f=!1;this.getPaperWidth=function(){return a};this.setPaperWidth=function(b){a=b};this.getPaperHeight=function(){return c};this.setPaperHeight=function(b){c=b};this.getPageMarginLeft=
function(){return e};this.setPageMarginLeft=function(b){e=b};this.getPageMarginRight=function(){return A};this.setPageMarginRight=function(b){A=b};this.getPageMarginTop=function(){return u};this.setPageMarginTop=function(b){u=b};this.getPageMarginBottom=function(){return K};this.setPageMarginBottom=function(b){K=b};this.getDirection=function(){return l};this.setDirection=function(b){l=b};this.getZoomType=function(){return F};this.setZoomType=function(b){F=b};this.getScaling=function(){return k};this.setScaling=
function(b){k=b};this.getZoomOutPageWide=function(){return h};this.setZoomOutPageWide=function(b){h=b};this.getZoomOutPageTall=function(){return B};this.setZoomOutPageTall=function(b){B=b};this.getHeader=function(){return E};this.getFooter=function(){return H};this.isPagingRowFirst=function(){return G};this.setPagingRowFirst=function(b){G=b};this.isTopHeaderAll=function(){return q};this.setTopHeaderAll=function(b){q=b};this.isLeftHeaderAll=function(){return f};this.setLeftHeaderAll=function(b){f=
b};this.toJsonObject=function(){var b={};b.isAutoFit=F==g.SCALING?!1:!0;b.scale=k;b.autoFitWidth=h;b.autoFitHeight=B;var d={};d.paperWidth=a;d.paperHeight=c;d.isLandscape=l==g.HORIZONTAL?!0:!1;d.marginLeft=e;d.marginRight=A;d.marginTop=u;d.marginBottom=K;d.scaleModel=b;d.listHeaderRow=E.toJsonObject();d.listFooterRow=H.toJsonObject();d.isRowFirst=G;d.isTopHeaderAll=q;d.isLeftHeaderAll=f;return d};this.fromJsonObject=function(b){var d=b.scaleModel;F=d.isAutoFit?g.ADJUSTMENT:g.SCALING;k=d.scale;h=d.autoFitWidth;
B=d.autoFitHeight;a=b.paperWidth;c=b.paperHeight;l=b.isLandscape?g.HORIZONTAL:g.VERITICAL;e=b.marginLeft;A=b.marginRight;u=b.marginTop;K=b.marginBottom;E.fromJsonObject(b.listHeaderRow);H.fromJsonObject(b.listFooterRow);G=b.isRowFirst;q=b.isTopHeaderAll;f=b.isLeftHeaderAll}}function y(){var a=[],c=[],l=[];this.getLeftText=function(){return a.join("\n")};this.setLeftText=function(e){a=e.split("\n")};this.getCenterText=function(){return c.join("\n")};this.setCenterText=function(e){c=e.split("\n")};
this.getRightText=function(){return l.join("\n")};this.setRightText=function(e){l=e.split("\n")};this.toJsonObject=function(){return[a,c,l]};this.fromJsonObject=function(e){e[0]&&(a=e[0]);e[1]&&(c=e[1]);e[2]&&(l=e[2])};this.toString=function(){var e=a.join(" "),A=c.join(" ");A&&(0<e.length&&(e+=", "),e+=A);if(A=l.join(" "))0<e.length&&(e+=", "),e+=A;return e}}function I(){var a,c;this.checkInvalid=function(){if(a.getDirection()==g.VERITICAL){var f=a.getPaperWidth();var b=a.getPaperHeight()}else f=
a.getPaperHeight(),b=a.getPaperWidth();return a.getPageMarginLeft()+a.getPageMarginRight()>f/2||a.getPageMarginTop()+a.getPageMarginBottom()>b/2?r.get("invalidMarginPrompt","\u9875\u9762\u8fb9\u8ddd\u592a\u5927\uff0c \u4e0d\u9002\u5408\u5f53\u524d\u7eb8\u5f20\u5927\u5c0f"):null};this.setModel=function(f){a=f};this.getJqUi=function(){if(!c){var f=new L;f.setTitle(r.get("paperMedia","\u7eb8\u5f20\u5c3a\u5bf8"));var b=new M(r.get("paperType","\u7c7b\u578b")),d=new M(r.get("paperSize","\u5927\u5c0f(mm)")),
m=new M(r.get("paperWidth","\u5bbd")),p=new M(r.get("paperHeight","\u9ad8")),n=new R,v=new N,z=new N;e(n,v,z);var x=f.getJqContainer();x.append(b.getJqUi());x.append(n.getJqUi());x.append(d.getJqUi());x.append(v.getJqUi());x.append(m.getJqUi());x.append(z.getJqUi());x.append(p.getJqUi());t.layoutCtrl(b.getJqUi(),0,0,90,23);t.layoutCtrl(n.getJqUi(),90,0,200,23);t.layoutCtrl(d.getJqUi(),0,33,90,23);t.layoutCtrl(v.getJqUi(),90,33,60,23);t.layoutCtrl(m.getJqUi(),155,33,60,23);t.layoutCtrl(z.getJqUi(),
230,33,60,23);t.layoutCtrl(p.getJqUi(),295,33,60,23);f=f.getJqUi();b=new L;b.setTitle(r.get("direction","\u65b9\u5411"));d=new P;d.setText(r.get("directionVertical","\u7eb5\u5411"));m=new P;m.setText(r.get("directionHorizontal","\u6a2a\u5411"));p=new S;p.addElement(d);p.addElement(m);u(p,d,m);p=b.getJqContainer();p.append(d.getJqUi());p.append(m.getJqUi());t.layoutCtrl(d.getJqUi(),0,0,90,23);t.layoutCtrl(m.getJqUi(),90,0,90,23);b=b.getJqUi();d=new L;d.setTitle(r.get("margin","\u9875\u8fb9\u8ddd(mm)"));
m=d.getJqContainer();p=[[r.get("marginLeft","\u5de6"),a.getPageMarginLeft,a.setPageMarginLeft],[r.get("marginRight","\u53f3"),a.getPageMarginRight,a.setPageMarginRight],[r.get("marginTop","\u4e0a"),a.getPageMarginTop,a.setPageMarginTop],[r.get("marginBottom","\u4e0b"),a.getPageMarginBottom,a.setPageMarginBottom]];n=[];for(v=0;v<p.length;v++){x=p[v][0];var C=p[v][1],J=p[v][2];z=new N;K(z,C,J);x=new M(x);x.getJqUi().css("text-align","right");C=$("<div>");C.append(x.getJqUi());C.append(z.getJqUi());
t.layoutCtrl(x.getJqUi(),0,0,50,23);t.layoutCtrl(z.getJqUi(),60,0,60,23);n[v]=C;m.append(C)}t.layoutCtrl(n[0],0,30,120,23);t.layoutCtrl(n[1],200,30,120,23);t.layoutCtrl(n[2],100,0,120,23);t.layoutCtrl(n[3],100,60,120,23);d=d.getJqUi();m=new L;m.setTitle(r.get("headerfooter","\u9875\u7709/\u9875\u811a"));p=new M(r.get("hfHeader","\u9875\u7709"));n=new R;v=new T(r.get("hfSetting","\u81ea\u5b9a\u4e49"));z=new M(r.get("hfFooter","\u9875\u811a"));x=new R;C=new T(r.get("hfSetting","\u81ea\u5b9a\u4e49"));
F(n,x,v,C);J=m.getJqContainer();J.append(p.getJqUi());J.append(n.getJqUi());J.append(v.getJqUi());J.append(z.getJqUi());J.append(x.getJqUi());J.append(C.getJqUi());t.layoutCtrl(p.getJqUi(),0,0,50,23);t.layoutCtrl(n.getJqUi(),50,0,210,23);t.layoutCtrl(v.getJqUi(),260,0,60,23);t.layoutCtrl(z.getJqUi(),0,33,50,23);t.layoutCtrl(x.getJqUi(),50,33,210,23);t.layoutCtrl(C.getJqUi(),260,33,60,23);m=m.getJqUi();p=new L;p.setTitle(r.get("zoom","\u7f29\u653e"));n=new P;n.setText(r.get("zoomRatio","\u7f29\u653e\u6bd4\u4f8b"));
v=new P;v.setText(r.get("zoomFitTo","\u4e0d\u8d85\u51fa"));x=new S;x.addElement(n);x.addElement(v);z=new N;C=new N;J=new N;E(x,n,v,z,C,J);x=new M("%");var U=new M(r.get("zoomPagesWide","\u9875\u5bbd")),ea=new M(r.get("zoomPagesTall","\u9875\u9ad8"));C=l([[C,0,60],[U,5,null],[J,10,60],[ea,5,null]]);J=p.getJqContainer();J.append(n.getJqUi());J.append(v.getJqUi());J.append(z.getJqUi());J.append(x.getJqUi());J.append(C);t.layoutCtrl(n.getJqUi(),0,0,90,23);t.layoutCtrl(z.getJqUi(),90,0,60,23);t.layoutCtrl(x.getJqUi(),
155,0,40,23);t.layoutCtrl(v.getJqUi(),0,33,90,23);t.layoutCtrl(C,90,33,260,23);p=p.getJqUi();n=new L;n.setTitle(r.get("pagingOrder","\u5206\u9875\u987a\u5e8f"));v=new P;z=new P;x=new S;x.addElement(v);x.addElement(z);G(x,v,z);J=new M(r.get("pagingOrderRowFirst","\u5148\u884c\u540e\u5217"));x=new M(r.get("pagingOrderColFirst","\u5148\u5217\u540e\u884c"));U=$("<div>");U.css("background-image",V.getIconUrl("export","icon_export-rowfirst.png"));C=$("<div>");C.css("background-image",V.getIconUrl("export",
"icon_export-colfirst.png"));J=l([[J,0,null],[U,5,23]]);x=l([[x,0,null],[C,5,23]]);C=n.getJqContainer();C.append(v.getJqUi());C.append(J);C.append(z.getJqUi());C.append(x);t.layoutCtrl(v.getJqUi(),0,0,20,23);t.layoutCtrl(J,20,0,130,23);t.layoutCtrl(z.getJqUi(),155,0,20,23);t.layoutCtrl(x,175,0,130,23);n=n.getJqUi();v=new L;v.setTitle(r.get("repeatTableHead","\u8868\u5934"));z=new W;z.setText(r.get("repeatTableTop","\u6bcf\u9875\u91cd\u590d\u4e0a\u8868\u5934"));x=new W;x.setText(r.get("repeatTableLeft",
"\u6bcf\u9875\u91cd\u590d\u5de6\u8868\u5934"));q(z,x);C=v.getJqContainer();C.append(z.getJqUi());C.append(x.getJqUi());t.layoutCtrl(z.getJqUi(),0,0,260,23);t.layoutCtrl(x.getJqUi(),0,33,260,23);v=v.getJqUi();c=$("<div>");c.append(f);c.append(b);c.append(p);c.append(n);c.append(d);c.append(m);c.append(v);t.layoutCtrlWithLRTB(f,0,null,"45%",0,null,110);t.layoutCtrlWithLRTB(b,0,null,"45%",110,null,70);t.layoutCtrlWithLRTB(d,0,null,"45%",180,null,130);t.layoutCtrlWithLRTB(m,0,null,"45%",310,null,110);
t.layoutCtrlWithLRTB(p,null,0,"45%",0,null,110);t.layoutCtrlWithLRTB(n,null,0,"45%",110,null,70);t.layoutCtrlWithLRTB(v,null,0,"45%",180,null,110)}return c};var l=function(f){for(var b=$("<div>"),d=0;d<f.length;d++){var m=f[d][0],p=f[d][1],n=f[d][2];m=m instanceof $?m:m.getJqUi();b.append(m);m.css("position","relative");m.css("float","left");m.css("margin-left",p+"px");m.css("height","23px");n&&m.css("width",n+"px")}return b},e=function(f,b,d){var m=[new D(297,420,"A3"),new D(210,297,"A4"),new D(148,
210,"A5"),new D(353,500,"B3"),new D(250,353,"B4"),new D(176,250,"B5"),new D(0,0,r.get("paperMediaCustom","\u81ea\u5b9a\u4e49"))];f.setItemModels(m);A(m,f);f.addSelectedChangedListener(function(p,n,v){n=p.getSelected();p=n.getWidth();n=n.getHeight();0<p&&0<n&&(a.setPaperWidth(p),a.setPaperHeight(n),b.setValue(p),d.setValue(n))});b.setConstraint(100,1E3,1);b.setValue(a.getPaperWidth());b.addValueChangedListener(function(p,n,v,z){z!=N.CHANGED_BY_API&&(a.setPaperWidth(v),A(m,f))});d.setConstraint(100,
1E3,1);d.setValue(a.getPaperHeight());d.addValueChangedListener(function(p,n,v,z){z!=N.CHANGED_BY_API&&(a.setPaperHeight(v),A(m,f))})},A=function(f,b){for(var d=0;d<f.length;d++){var m=f[d];if(m.getWidth()==a.getPaperWidth()&&m.getHeight()==a.getPaperHeight()){b.setSelected(m);return}}b.setSelected(f[f.length-1])},u=function(f,b,d){b.setUserObject(g.VERITICAL);b.setChecked(a.getDirection()==g.VERITICAL);d.setUserObject(g.HORIZONTAL);d.setChecked(a.getDirection()==g.HORIZONTAL);f.addChangedListener(function(m,
p){p&&a.setDirection(m.getUserObject())})},K=function(f,b,d){f.setConstraint(0,1E3,1);f.setValue(b());f.addValueChangedListener(function(m,p,n,v){v!=N.CHANGED_BY_API&&d(n)})},F=function(f,b,d,m){f.setSelected(a.getHeader());b.setSelected(a.getFooter());var p=[new y,k([[],[r.get("hfSelectableItem1","\u7b2c&[Page]\u9875")],[]]),k([[],[r.get("hfSelectableItem2","\u7b2c&[Page]\u9875 \u5171&[PageCount]\u9875")],[]]),k([[],[r.get("hfSelectableItem3","\u6253\u5370\u65e5\u671f:&[Date]")],[]]),k([[],[r.get("hfSelectableItem4",
"\u6253\u5370\u65f6\u95f4:&[Time]")],[]]),k([[],[r.get("hfSelectableItem5","&[Date] &[Time]")],[]])];f.setItemModels(p,h);f.addSelectedChangedListener(function(n,v,z){a.getHeader().fromJsonObject(z.toJsonObject())});b.setItemModels(p,h);b.addSelectedChangedListener(function(n,v,z){a.getFooter().fromJsonObject(z.toJsonObject())});d.addActionListener(function(n){n=r.get("hfHeader","\u9875\u7709");B(n,!0,a.getHeader(),function(){f.setSelected(null);f.setSelected(a.getHeader())})});m.addActionListener(function(n){n=
r.get("hfFooter","\u9875\u811a");B(n,!1,a.getFooter(),function(){b.setSelected(null);b.setSelected(a.getFooter())})})},k=function(f){var b=new y;b.fromJsonObject(f);return b},h=function(f,b){return f.getLeftText()==b.getLeftText()&&f.getCenterText()==b.getCenterText()&&f.getRightText()==b.getRightText()},B=function(f,b,d,m){var p=new fa;p.setTitle(f);p.setHeaderOrFooter(b);p.setHeaderFooterModel(d);p.setConfirmedCallback(m);p.showDialog()},E=function(f,b,d,m,p,n){b.setUserObject(g.SCALING);b.setChecked(a.getZoomType()==
g.SCALING);d.setUserObject(g.ADJUSTMENT);d.setChecked(a.getZoomType()==g.ADJUSTMENT);f.addChangedListener(function(v,z){z&&a.setZoomType(v.getUserObject())});m.setConstraint(10,400,1);m.setValue(a.getScaling());m.addValueChangedListener(function(v,z,x,C){C!=N.CHANGED_BY_API&&(a.setScaling(x),a.setZoomType(g.SCALING),b.setChecked(!0))});p.setCustomPainter(H);p.setConstraint(0,32767,1);p.setValue(a.getZoomOutPageWide());p.addValueChangedListener(function(v,z,x,C){C!=N.CHANGED_BY_API&&(a.setZoomOutPageWide(x),
a.setZoomType(g.ADJUSTMENT),d.setChecked(!0))});n.setCustomPainter(H);n.setConstraint(0,32767,1);n.setValue(a.getZoomOutPageTall());n.addValueChangedListener(function(v,z,x,C){C!=N.CHANGED_BY_API&&(a.setZoomOutPageTall(x),a.setZoomType(g.ADJUSTMENT),d.setChecked(!0))})},H=function(f){return 0<f?f:""},G=function(f,b,d){b.setUserObject(!0);b.setChecked(a.isPagingRowFirst());d.setUserObject(!1);d.setChecked(!a.isPagingRowFirst());f.addChangedListener(function(m,p){p&&a.setPagingRowFirst(m.getUserObject())})},
q=function(f,b){f.setChecked(a.isTopHeaderAll());b.setChecked(a.isLeftHeaderAll());f.addCheckedListener(function(d,m){m&&a.setTopHeaderAll(d.isChecked())});b.addCheckedListener(function(d,m){m&&a.setLeftHeaderAll(d.isChecked())})}}function D(a,c,l){this.getWidth=function(){return a};this.getHeight=function(){return c};this.toString=function(){return l}}function L(){var a,c=$("<div>"),l=$("<div>");this.setTitle=function(e){c.text(e)};this.getJqUi=function(){a||(c.css("color","#333"),c.css("line-height",
"24px"),c.css("font-size","14px"),c.css("border-bottom","solid 1px #d7dadd"),l.css("font-size","12px"),a=$("<div>"),a.append(c),a.append(l),t.layoutCtrlWithLRTB(c,0,0,null,0,null,24),t.layoutCtrlWithLRTB(l,10,10,null,34,10,null));return a};this.getJqContainer=function(){return l}}function Q(){var a=this,c,l,e,A=0,u=0,K=function(){if(!c){c=new ba;var q=F();q.on("focus",B);q.on("blur",E);if(X.isIEBrowser())q.on("beforedeactivate",h)}return c},F=function(){return K().getJqUi().find("textarea")};this.getJqUi=
function(){return K().getJqUi()};this.requestFocus=function(){c.requestFocus()};this.setFocusListener=function(q){e=q};this.setAlign=function(q){F().css("text-align",q);l=r.get("left"==q?"hfSettingLeftPart":"right"==q?"hfSettingRightPart":"hfSettingCenterPart");H(!1)};this.setValue=function(q){K().setText(q);G(q)};this.getValue=function(){return K().getText()};this.insert=function(q){X.isIEBrowser()?u=A=k(q,A,u):k(q,F()[0].selectionStart,F()[0].selectionEnd);c.requestFocus()};var k=function(q,f,b){var d=
a.getValue();if("number"!=typeof f||"number"!=typeof b)b=f=d.length;a.setValue(d.substring(0,f)+q+d.substring(b,d.length));q=f+q.length;F()[0].setSelectionRange(q,q);return q},h=function(q){A=F()[0].selectionStart;u=F()[0].selectionEnd},B=function(q){H(!0);G(!0);e(a)},E=function(q){H(!1);G(a.getValue())},H=function(q){q?F().attr("placeholder",r.get("hfSettingInsertingTips","\u8bf7\u8f93\u5165\u5185\u5bb9")):F().attr("placeholder",l)},G=function(q){q?F().css("line-height",""):F().css("line-height",
"40px")}}function ha(){var a,c=new Q,l=new Q,e=new Q,A;this.setModelToModify=function(h){a=h;c.setValue(a.getLeftText());l.setValue(a.getCenterText());e.setValue(a.getRightText());A=a.getLeftText()?c:a.getCenterText()?l:a.getRightText()?e:c};this.acceptModified=function(){a.setLeftText(c.getValue());a.setCenterText(l.getValue());a.setRightText(e.getValue())};this.createJqUi=function(h){var B=K();h=u(h);var E=$("<div>");E.append(B);E.append(h);t.layoutCtrlWithLRTB(B,0,0,null,0,null,24);t.layoutCtrlWithLRTB(h,
0,0,null,32,null,112);setTimeout(function(){A.requestFocus()},0);return E};var u=function(h){c.setAlign("left");c.setFocusListener(F);l.setAlign("center");l.setFocusListener(F);e.setAlign("right");e.setFocusListener(F);var B=c.getJqUi(),E=l.getJqUi(),H=e.getJqUi(),G=V.getIconUrl("export",h?"icon_export-bgheader.png":"icon_export-bgfooter.png"),q=$("<div>");q.css("background-image",G);q.css("background-repeat","repeat-x");q.append(B);q.append(E);q.append(H);G=h?8:null;h=h?null:8;t.layoutCtrlWithLRTB(B,
8,null,"30%",G,h,44);t.layoutCtrlWithLRTB(E,"35%",null,"30%",G,h,44);t.layoutCtrlWithLRTB(H,null,8,"30%",G,h,44);return q},K=function(){var h=$("<div>"),B=0,E=new M(r.get("hfSettingButtonsCaption","\u63d2\u5165"));t.layoutCtrl(E.getJqUi(),B,0,60,23);h.append(E.getJqUi());B=60;E=[["&[Page]",r.get("hfSettingBtnPage","\u9875\u7801")],["&[PageCount]",r.get("hfSettingBtnPageCount","\u603b\u9875\u6570")],["&[Date]",r.get("hfSettingBtnDate","\u65e5\u671f")],["&[Time]",r.get("hfSettingBtnTime","\u65f6\u95f4")]];
for(var H=0;H<E.length;H++){var G=E[H][0],q=new T(E[H][1]);q.setUserObject(G);q.addActionListener(k);h.append(q.getJqUi());t.layoutCtrl(q.getJqUi(),B,0,72,23);B+=72}return h},F=function(h){A=h},k=function(h){h=h.getUserObject();A.insert(h)}}function fa(){Y.call(this);var a=this,c=this.protectedMethod,l,e,A;(function(){a.setSize(640,264);c.setSelectable(!0);c.setContentPaneCreator(function(){return e.createJqUi(l)});c.setClosingAction(function(u){u&&(e.acceptModified(),A())})})();this.setTitle=function(u){c.setTitle(u)};
this.setHeaderOrFooter=function(u){l=u};this.setHeaderFooterModel=function(u){e=new ha;e.setModelToModify(u)};this.setConfirmedCallback=function(u){A=u}}function ia(){Y.call(this);var a=this,c=this.protectedMethod,l,e,A;(function(){a.setSize(860,540);c.setContentPaneCreator(function(){e=new I;e.setModel(l);return e.getJqUi()});c.setClosingChecker(function(){var u=e.checkInvalid();return u?(c.getMessageCurtain().showPrompt(u),!1):!0});c.setClosingAction(function(u){u&&A(l)})})();this.setTitle=function(u){c.setTitle(u)};
this.setSettingModel=function(u){l=u};this.setConfirmer=function(u){A=u}}function ca(){var a=!0;this.setVerticalMerged=function(c){a=c};this.isVerticalMerged=function(){return a};this.toJsonObject=function(){var c={};c.verticalMerged=a;return c};this.fromJsonObject=function(c){a=c.verticalMerged}}function ja(){Y.call(this);var a=this,c=this.protectedMethod,l,e,A;(function(){a.setSize(360,180);c.setContentPaneCreator(function(){e=new ka;e.setModel(l);return e.getJqUi()});c.setClosingAction(function(u){u&&
A(l)})})();this.setTitle=function(u){c.setTitle(u)};this.setConfigModel=function(u){l=u};this.setConfirmer=function(u){A=u}}function ka(){var a,c;this.setModel=function(e){a=e};this.getJqUi=function(){c||l();return c};var l=function(){c=$("<div>");var e=new W;e.setText(r.get("keepVerticalMerged","\u4fdd\u7559\u5de6\u8868\u5934\u8de8\u884c\u5408\u5e76\u5355\u5143\u683c\uff08\u5982\u679c\u6709\uff09"));e.setChecked(a.isVerticalMerged());e.addCheckedListener(function(A,u){u&&a.setVerticalMerged(A.isChecked())});
e=e.getJqUi();e.appendTo(c);t.layoutCtrlWithLRTB(e,0,0,null,0,null,23)}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});"undefined"==typeof com.kingdee.bos.qing.exportmanage&&(com.kingdee.bos.qing.exportmanage={});var da=com.kingdee.bos.qing.exportmanage,X,t,r,V,Z,Y,P,S,R,M,T,W,N,ba,aa,O;(function(){var a=com.kingdee.bos.qing.common;X=a.Util;
t=a.DomUtil;a=com.kingdee.bos.qing.framework.common;r=a.MultilanguageManager.createPackageAccessor(da);V=a.Resource;Z=a.RemoteFramework;a=com.kingdee.bos.qing.ui.component;Y=a.AbstractModalDialog;P=a.RadioButton;S=a.RadioButtonGroup;R=a.ComboBox;M=a.Label;T=a.WorkButton;W=a.CheckBox;N=a.Spinner;ba=a.TextArea;a=com.kingdee.bos.qing.core.commonui;aa=a.ExportHelper;a=com.kingdee.bos.qing.behavior;O=a.BehaviorManager})();da.ExportManage=function(){var a,c;this.setDependentApi=function(k){a=k};this.setMenuStateUpdater=
function(k){c=k};this.exportExcel=function(){var k=A();!k&&(k=new ca);var h=new ja;h.setTitle(r.get("exportExcelDialogTitle","\u5bfc\u51fa\u4e3aExcel"));h.setConfigModel(k);h.setConfirmer(function(B){B=B.toJsonObject();B=JSON.stringify(B);a.setExportConfig(B);c(!0);F("EXCEL",".xlsx")});h.showDialog()};this.exportPng=function(){c(!0);F("PNG",".png")};this.exportPdf=function(){var k=l();k||(k=new g,e(k));c(!0);F("PDF",".pdf")};this.printSetting=function(){var k=l();!k&&(k=new g);var h=new ia;h.setTitle(r.get("printSettingDialogTitle",
"\u6253\u5370\u8bbe\u7f6e"));h.setSettingModel(k);h.setConfirmer(function(B){e(B)});h.showDialog()};this.printPreview=function(){c(!0);var k=l();k||(k=new g,e(k));K()};var l=function(){var k=a.getExportSetting();if(k){k=JSON.parse(k);var h=new g;h.fromJsonObject(k);return h}return null},e=function(k){k=k.toJsonObject();k=JSON.stringify(k);a.setExportSetting(k)},A=function(){var k=a.getExportConfig();if(k){k=JSON.parse(k);var h=new ca;h.fromJsonObject(k);return h}return null},u=function(k){return"Qing-"+
X.formatDate("yyyyMMdd_HHmmss")+k},K=function(){var k=(new Date).getTime(),h=u(".pdf"),B=new w;B.setExportType("PDF");B.setJsonModelWrapper(a.createJsonModelWrapper());var E=a.createFacade(function(H){c(!1);var G=r.get("printPreviewTabbedTitle","\u6253\u5370\u9884\u89c8");Z.previewFile(G,h,H);O.interestInBehavior(O.PRINT_PREVIEW,1,(new Date).getTime()-k);O.recordResourceOperation(O.OperationType.QING_PRINT)},function(H,G){c(!1);return aa.facadeErrorHandler(H,G)},void 0);E.setShowBlocking(!1);E.exportExhibition(h,
B,a.createJsonAdditionalFilters())},F=function(k,h){var B=(new Date).getTime(),E=u(h);h=new w;h.setExportType(k);h.setJsonModelWrapper(a.createJsonModelWrapper());var H=a.createFacade(function(G){c(!1);Z.downloadFile(E,G);O.interestInBehavior(O.EXPORT_TYPE,k,(new Date).getTime()-B);O.recordResourceOperation(O.OperationType.QING_EXPORT)},function(G,q){c(!1);return aa.facadeErrorHandler(G,q)},void 0);H.setShowBlocking(!1);H.exportExhibition(E,h,a.createJsonAdditionalFilters())}};g.SCALING="SCALING";
g.ADJUSTMENT="ADJUSTMENT";g.HORIZONTAL="HORIZONTAL";g.VERITICAL="VERITICAL"})();
//qingVersionTag: 20250324