var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var p=0;return function(){return p<c.length?{done:!1,value:c[p++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,p,t){if(c==Array.prototype||c==Object.prototype)return c;c[p]=t.value;return c};$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var p=0;p<c.length;++p){var t=c[p];if(t&&t.Math==Math)return t}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(c,p){var t=$jscomp.propertyToPolyfillSymbol[p];if(null==t)return c[p];t=c[t];return void 0!==t?t:c[p]};
$jscomp.polyfill=function(c,p,t,y){p&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(c,p,t,y):$jscomp.polyfillUnisolated(c,p,t,y))};$jscomp.polyfillUnisolated=function(c,p,t,y){t=$jscomp.global;c=c.split(".");for(y=0;y<c.length-1;y++){var A=c[y];if(!(A in t))return;t=t[A]}c=c[c.length-1];y=t[c];p=p(y);p!=y&&null!=p&&$jscomp.defineProperty(t,c,{configurable:!0,writable:!0,value:p})};
$jscomp.polyfillIsolated=function(c,p,t,y){var A=c.split(".");c=1===A.length;y=A[0];y=!c&&y in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var F=0;F<A.length-1;F++){var I=A[F];if(!(I in y))return;y=y[I]}A=A[A.length-1];t=$jscomp.IS_SYMBOL_NATIVE&&"es6"===t?y[A]:null;p=p(t);null!=p&&(c?$jscomp.defineProperty($jscomp.polyfills,A,{configurable:!0,writable:!0,value:p}):p!==t&&(void 0===$jscomp.propertyToPolyfillSymbol[A]&&(t=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[A]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(A):$jscomp.POLYFILL_PREFIX+t+"$"+A),$jscomp.defineProperty(y,$jscomp.propertyToPolyfillSymbol[A],{configurable:!0,writable:!0,value:p})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(c){if(c)return c;var p=function(F,I){this.$jscomp$symbol$id_=F;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:I})};p.prototype.toString=function(){return this.$jscomp$symbol$id_};var t="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",y=0,A=function(F){if(this instanceof A)throw new TypeError("Symbol is not a constructor");return new p(t+(F||"")+"_"+y++,F)};return A},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(c){if(c)return c;c=Symbol("Symbol.iterator");for(var p="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),t=0;t<p.length;t++){var y=$jscomp.global[p[t]];"function"===typeof y&&"function"!=typeof y.prototype[c]&&$jscomp.defineProperty(y.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return c},"es6",
"es3");$jscomp.iteratorPrototype=function(c){c={next:c};c[Symbol.iterator]=function(){return this};return c};$jscomp.iteratorFromArray=function(c,p){c instanceof String&&(c+="");var t=0,y=!1,A={next:function(){if(!y&&t<c.length){var F=t++;return{value:p(F,c[F]),done:!1}}y=!0;return{done:!0,value:void 0}}};A[Symbol.iterator]=function(){return A};return A};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(p){return p})}},"es6","es3");
(function(){function c(m,x,q,g){R.call(this,m,x,q,g);var h=this.protectedMethod;this.loadLinkageContext=function(a){h.remote("loadLinkageContext",{tag:a})};this.cancleJumpToLinkTarget=function(a,d){h.remote("cancleJumpToLinkTarget",{foreignKeyMembersCachedId:a,tag:d})};this.lookupBizMeta=function(a,d,f){a={arrBizUiId:JSON.stringify(a),tag:d,bEditUi:f};h.remote("lookupBizMeta",a)}}function p(){S.call(this);var m;this.getRemoteUrl=function(x){return m};this.setRemoteUrl=function(x){m=x}}function t(){var m,
x,q,g;this.setFunSetup=function(h){m=h};this.setFunLookupBizMeta=function(h){x=h};this.setFunJumpToBizListUi=function(h){q=h};this.setFunJumpToBizEditUi=function(h){g=h};this.setup=function(h,a,d){m&&m(h,a,d)};this.lookupBizMeta=function(h,a,d){x&&x(h,a,d)};this.jumpToBizListUi=function(h,a,d,f){q&&q(h,a,d,f)};this.jumpToBizEditUi=function(h,a,d,f){g&&g(h,a,d,f)}}function y(m,x,q,g,h){T.call(this);var a=this,d=this.protectedMethod,f;(function(){d.setTitle(K.get("navigationSetting","\u5355\u636e\u8054\u67e5\u8bbe\u7f6e"));
a.setSize(450,410);f=new A(m,x,q,g);d.setContentPaneCreator(function(){return f.getJqUi()});d.setClosingAction(function(b){var l=null;b&&(l=f.getModeFromUI());h(l)})})()}function A(m,x,q,g){var h,a,d,f,b,l,n=function(){var k=new c(m,function(r){l=new F;l.fromJson(r);B()},function(){});k.setBlockingJqUi(h);k.loadLinkageContext(x)},B=function(){h.empty();var k=l.getLinkageFormKeys();if(0==k.length){k=$("<div>");k.addClass("linkage-setting-panel-icon");N||(N=com.kingdee.bos.qing.linkage.common.MyIcons);
N.background(k,"icon-warning");var r=$("<div>");r.addClass("linkage-setting-panel-text");var w=K.get("noNavigationTarget","\u6570\u636e\u6a21\u578b\u4e2d\u6ca1\u6709\u5f15\u7528\u4efb\u4f55\u201c\u4e1a\u52a1\u5b9e\u4f53\u201d\uff0c\u6240\u4ee5\u60a8\u65e0\u6cd5\u8fdb\u884c\u5355\u636e\u8054\u67e5\u7684\u8bbe\u7f6e\u3002");r.text(w);k.appendTo(h);r.appendTo(h)}else{a=$("<div>");a.addClass("linkage-content-setting-panel");var e=[];for(r=0;r<k.length;r++)w=l.getLinkageFormInfo(k[r]),e.push(w);(w=u(e))?
z(e):D(e);h.append(a);k=$("<div>");k.addClass("linkage-check-setting-panel");d=new L;r=K.get("showMorePages","\u663e\u793a\u66f4\u591a\u9875\u9762");d.setText(r);d.setChecked(w);d.addCheckedListener(function(v,C){C&&(v.isChecked()?(null==f&&z(e),v=b?b.getCheckBoxList():null,f.show(v),b&&b.hide()):(null==b&&D(e),v=f?f.getCheckBoxList():null,b.show(v),f&&f.hide()))});w=d.getJqUi();w.attr("title",r);w.css({position:"absolute",top:0,height:23,left:5,width:100,"margin-top":5});k.append(w);r=new O;r.setIconType(O.ICON_TYPE_QUESTION);
r.setTipsText(K.get("whatsLayoutPage","\u663e\u793a\u57fa\u4e8e\u5b9e\u4f53\u7684\u201c\u5e03\u5c40\u9875\u9762\u201d"));r=r.getJqUi();U.layoutCtrl(r,103,8,null,null);k.append(r);h.append(k);a.css("height","260")}},u=function(k){if(!q||0==q.length)return!1;if(k&&0<k.length)for(var r=0;r<k.length;r++)for(var w=k[r],e=0;e<q.length;e++){var v=q[e];if(v.getForeignKey()==w.getFormPrimaryKey()){v=(v=v.getBizUiId())&&JSON.parse(v);var C=w.getFormKey();C=C&&JSON.parse(C);if(v.FormId!=C.FormId&&(!v.FormName||
v.FormName==C.FormName))return!0}}return!1},D=function(k){b=new W;b.addCheckedListener(function(r,w){if(f&&(w=f.getCheckBoxList())&&0<w.length){var e=r.getUserObject(),v;for(v in w){var C=w[v],E=C.getUserObject();E.isLayout()||e&&E.getFormKey()==e.getFormKey()&&E.getFormDisplayName()==e.getFormDisplayName()&&E.getFormPrimaryKey()==e.getFormPrimaryKey()&&C.setChecked(r.isChecked())}}});k=b.createJqUi(k,q,H);a.append(k);return k},z=function(k){k=X(k);f=new Y;f.addCheckedListener(function(r,w){w=r.getUserObject();
if(!w.isLayout()&&b){var e=b.getCheckBoxList();if(e&&0<e.length)for(var v in e){var C=e[v],E=C.getUserObject();E.getFormKey()==w.getFormKey()&&E.getFormDisplayName()==w.getFormDisplayName()&&E.getFormPrimaryKey()==w.getFormPrimaryKey()&&C.setChecked(r.isChecked())}}});k=f.createJqUi(k,q,H);a.append(k);return k};this.getJqUi=function(){h||(h=$("<div>"),n());return h};this.getModeFromUI=function(){var k=[];if(0==l.getLinkageFormKeys().length)return k;f&&G(k,f.getCheckBoxList());b&&G(k,b.getCheckBoxList());
return k};var G=function(k,r){for(var w=0;w<r.length;w++){var e=r[w],v=e.getUserObject();if(e=e.isChecked()){a:{e=k;for(var C=v,E=0;E<e.length;E++){var J=e[E];if(J.getBizUiId()==C.getFormKey()&&J.getBizUiDisplayName()==C.getFormDisplayName()&&J.getForeignKey()==C.getFormPrimaryKey()){e=!0;break a}}e=!1}e=!e}e&&(e=g(),e.setBizUiId(v.getFormKey()),e.setBizUiDisplayName(v.getFormDisplayName()),e.setForeignKey(v.getFormPrimaryKey()),k.push(e))}},H=function(k,r){if(k&&r&&0<r.length)for(var w=0;w<r.length;w++){var e=
r[w];if(e.getForeignKey()==k.getFormPrimaryKey()){e=(e=e.getBizUiId())&&JSON.parse(e);var v=k.getFormKey();v=v&&JSON.parse(v);if(e&&v&&e.FormId==v.FormId&&e.FormName==v.FormName)return!0}}return!1},X=function(k){var r=[];if(k&&0<k.length)for(var w=0;w<k.length;w++){var e=k[w],v=new P;v.setName(e.getFormDisplayName());v.setParentNode(null);v.setLinkageFormInfo(e);e=e.getLayouts();r.push(v);if(e&&0<e.length){for(var C=[],E=0;E<e.length;E++){var J=e[E],M=new P;M.setName(J.getFormDisplayName());M.setParentNode(v);
M.setLinkageFormInfo(J);C.push(M);r.push(M)}v.setChildren(C)}}return r}}function F(){var m=this,x=!1,q={};this.isEmbeded=function(){return x};this.getLinkageFormInfoMap=function(){return q};this.getLinkageFormInfo=function(g){return q[g]};this.getLinkageFormKeys=function(){return Object.keys(q)};this.isEmpty=function(){return 0<m.getLinkageFormKeys().length};this.toJson=function(){var g={};g.isEmbed=x;for(var h={},a=m.Object.keys(q),d=0;d<a.length;d++){var f=a[d];h[f]=q[f].toJson()}g.linkageFormInfos=
h;return g};this.fromJson=function(g){x=g.isEmbed;q={};g=g.linkageFormInfos;for(var h=Object.keys(g),a=0;a<h.length;a++){var d=h[a],f=g[d],b=new I;b.fromJson(f);q[d]=b}}}function I(){var m,x,q,g=[],h=!1;this.getFormKey=function(){return m};this.setFormKey=function(a){m=a};this.getFormDisplayName=function(){return x};this.setFormDisplayName=function(a){x=a};this.getFormPrimaryKey=function(){return q};this.setFormPrimaryKey=function(a){q=a};this.getLayouts=function(){return g};this.isLayout=function(){return h};
this.setLayout=function(a){h=a};this.toJson=function(){return{}};this.fromJson=function(a){m=a.formKey;x=a.formDisplayName;q=a.formPrimaryKey;if((a=a.layouts)&&0<a.length)for(var d=0;d<a.length;d++){var f=a[d],b=new I;b.setFormKey(f.formKey);b.setFormDisplayName(f.formDisplayName);b.setFormPrimaryKey(f.formPrimaryKey);b.setLayout(0==d?!1:!0);g.push(b)}}}function W(){var m=[],x,q,g,h;this.addCheckedListener=function(a){h=a};this.createJqUi=function(a,d,f){x=d;q=f;g=$("<div>");if(a&&0<a.length)for(f=
d=0;f<a.length;f++){var b=new L,l=a[f];b.setText(l.getFormDisplayName());b.addCheckedListener(h);b.setChecked(q(l,x));b.setUserObject(l);l=b.getJqUi();var n={position:"absolute"};n.top=d;n.height=23;n.left=0;n.right=0;d+=23;l.css(n);g.append(l);m.push(b)}return g};this.getJqUi=function(){return g};this.show=function(a){if(null!=a&&null!=m)for(var d=0;d<m.length;d++){var f=m[d],b=f,l=b.setChecked;a:{var n=a;if(null!=n&&0!=n.length){f=f.getUserObject();for(var B=0;B<n.length;B++){var u=n[B].getUserObject();
if(!u.isLayout()&&n[B].isChecked()&&u.getFormKey()==f.getFormKey()&&u.getFormDisplayName()==f.getFormDisplayName()&&u.getFormPrimaryKey()==f.getFormPrimaryKey()){n=!0;break a}}}n=!1}l.call(b,n)}g.show()};this.hide=function(){g.hide()};this.getCheckBoxList=function(){return m}}function Y(){function m(b){KTDefaultCellRender.call(this,b);var l=this;this.paintCellUI=function(n,B){a:{l.getCell().getValue();var u=l.getCell().getValue();var D=$("<div>");if("0"==u.getSubNodeLevel()){var z=$("<div>");z.text(u.getName())}else{if(null!=
g&&0<g.length)for(z=0;z<g.length;z++)if(g[z].getUserObject()==u.getLinkageFormInfo()){var G=g[z];u=u.getName();var H=new L;H.setText(u);H.setChecked(G.isChecked());H.setUserObject(G.getUserObject());u=H;u.addCheckedListener(f);g[z]=u;z=u.getJqUi();D.append(z);break a}z=new L;G=u.getLinkageFormInfo();z.setText(u.getName());z.setChecked(a(G,h));z.setUserObject(G);u=z;u.addCheckedListener(f);g.push(u);z=u.getJqUi()}D.append(z)}B?(n=$(B),D.appendTo(n)):(n=$(n),D.appendTo(n))}}var x=this,q,g=[],h,a,d,
f;this.addCheckedListener=function(b){f=b};this.createJqUi=function(b,l,n){a=n;h=l;l=new KTable;q=new m(l);l.setCellRender(q);l.setSyncUIWhenModelChanged(!1);l.addColumn().setWidth(400);for(n=0;n<b.length;n++){var B=b[n],u=l.addRow();u.setHeight(23);u=u.getCell(0);u.setValue(B);B=B.getSubNodeLevel();B=new KTCellTreeModel(B);u.setTreeModel(B)}l.updateUI();return d=$(l.getUI())};this.getJqUi=function(){return d};this.show=function(b){null!=b&&x.reBuildCheckBoxList(b);d.show()};this.reBuildCheckBoxList=
function(b){if(null!=g)for(var l=0;l<g.length;l++){var n=g[l];if(!n.getUserObject().isLayout()){var B=n,u=B.setChecked;a:{var D=b;if(null!=D&&0!=D.length)for(var z=0;z<D.length;z++)if(D[z].isChecked()){var G=D[z].getUserObject(),H=n.getUserObject();if(G.getFormKey()==H.getFormKey()&&G.getFormDisplayName()==H.getFormDisplayName()&&G.getFormPrimaryKey()==H.getFormPrimaryKey()){n=!0;break a}}n=!1}u.call(B,n)}}};this.hide=function(){d.hide()};this.getCheckBoxList=function(){return g}}function P(){var m=
this,x,q,g=[],h;this.setName=function(a){x=a};this.getName=function(){return x};this.setParentNode=function(a){q=a};this.setLinkageFormInfo=function(a){h=a};this.getLinkageFormInfo=function(){return h};this.getParentNode=function(){return q};this.setChildren=function(a){g=a};this.getChildren=function(){return g};this.getSubNodeLevel=function(){for(var a=0,d=q;d;)a++,d=d.getParentNode();return a};this.toJsonObject=function(){var a={};a.children=g;return a};this.fromJsonObject=function(a){m.setName(a.name);
if(a=a.children)for(var d=0;d<a.length;d++){var f=a[d];if(f){var b=new P;b.fromJsonObject(f);b.setParentNode(m);g.push(b)}}}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});"undefined"==typeof com.kingdee.bos.qing.linkage&&(com.kingdee.bos.qing.linkage={});var V=com.kingdee.bos.qing.linkage;V.LinkageManage=function(){var m,x,q,g=function(){m||
(m=new p,m.setRemoteUrl(x));return m};this.setCurrentLinkageTag=function(b){q=b};this.initDesigntime=function(b,l){var n=new t;x=b;h(n,l,!1)};this.initRuntime=function(b,l){var n=new t;x=b;h(n,l,!0)};var h=function(b,l,n){!n&&b.setFunSetup(d);b.setFunJumpToBizListUi(function(B,u,D,z){if(z)a(D);else{for(;Q.exit(););l(B,u,D)}});b.setFunJumpToBizEditUi(function(B,u,D,z){if(!z){for(;Q.exit(););l(B,u,D,!0)}});b.setFunLookupBizMeta(f);com.kingdee.bos.qing.core.LinkageRegister.register(b)},a=function(b){(new c(g(),
function(l){},function(){})).cancleJumpToLinkTarget(b,q)},d=function(b,l,n){(new y(g(),q,b,l,n)).showDialog()},f=function(b,l,n){var B=new c(g(),function(u){0<u.length&&l&&l(u)},function(){});B.setShowBlocking(!1);B.lookupBizMeta(b,q,n)}};var N,K,R,S,T,L,O,U,Q;(function(){var m=com.kingdee.bos.qing.framework.common;K=m.MultilanguageManager.createPackageAccessor(V);R=m.AbstractFacade;S=m.AbstractRemoteCall;m=com.kingdee.bos.qing.ui.component;T=m.AbstractModalDialog;L=m.CheckBox;O=m.HelpIcon;m=com.kingdee.bos.qing.common;
U=m.DomUtil;Q=m.FullScreenHelper})()})();
//qingVersionTag: 20250324