(function(){function F(l,t,p,u){A.call(this,l,t,p,u);var n=this.protectedMethod;this.getMetricReferenceMap=function(z,w){n.remote("getMetricReferenceMap",{refToId:w,workbenchId:z})}}function D(){y.call(this);var l;this.getRemoteUrl=function(){return l};this.setRemoteUrl=function(t){l=t}}var b,B,A,y,q;(function(){var l=com.kingdee.bos.qing.workbench.common;b=l.AbstractMetricHelper;B=l.MetricIntegration;l=com.kingdee.bos.qing.framework.common;y=l.AbstractRemoteCall;A=l.AbstractFacade;l=com.kingdee.bos.qing.common;
q=l.Util})();B.registerImpl(new function(){b.call(this);this.getMetricReferenceMap=function(l,t,p){(new F(x(),function(u){p(u)})).getMetricReferenceMap(l,t)};this.getMetricSquareEntrance=function(l){var t=q.decodeParamFromUrl(window.location.search,"path"),p=q.decodeParamFromUrl(window.location.search,"pageId");l=q.appendParamToUrl((t?t:"/ierp")+"/qing/metricSquareEntrance.do","metricLibId",l);return l=q.appendParamToUrl(l,"pageId",p)}});var x=function(){var l=com.kingdee.bos.qing.common.Util.decodeParamFromUrl(window.location.search,
"path");l=(l?l:"/ierp")+"/qing/workbench.do";var t=new D;t.setRemoteUrl(l);return t}})();(function(){function F(){com.kingdee.bos.qing.AbstractSquareDivScene.call(this);var n=this.protectedMethod,z,w,C;this.setSchemaContent=function(r){z=r};this.setSchemaLoadCallback=function(r){C=r};this.createChartInfoUi=function(r){return n.createChartInfoUi(r)};this.createInsightUi=function(r){return n.createInsightUi(r)};this.createInsightContentMaker=function(){return n.createInsightContentMaker()};this.redraw=function(){n.redraw()};this.changeChartType=function(r){return n.changeChartType(r)};
this.protectedLoadingImpl=function(r){r=r(z);C&&C(r)};this.protectedShowErrorImpl=function(r,v,G,H){w||(w=new com.kingdee.bos.qing.scene.common.square.exhibition.CardErrorUi(r),w.setShowDetail(!0));w.show(v,G,H);return!0};this.protectedInitMode=function(){}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});"undefined"==typeof com.kingdee.bos.qing.scene&&
(com.kingdee.bos.qing.scene={});var D=com.kingdee.bos.qing.scene;D.WorkbenchScene=function(){A.call(this);var n=this,z=[];this.protectedGetRemoteUrl=function(){return v()+"/qing/workbench.do"};this.protectedGetPublishEntranceUrl=function(d){var e=v()+"/qing/publishEntrance.do";e=b.appendParamToUrl(e,"publishId",d);d=n.getUrlParam("pageId");e=b.appendParamToUrl(e,"pageId",d);e=b.appendParamToUrl(e,"openFrom","qing_workbench");(d=p.getUrlParamValue())&&(e=b.appendParamToUrl(e,"skin",d));(d=u.getUrlParamValue("language"))&&
(e=b.appendParamToUrl(e,"language",d));return e=com.kingdee.bos.qing.integration.PageHelper.getIframeUrl(e)};this.protectedCustomInitEnv=function(){x.setFunMessageBoxPainter(H);x.setWorkbenchRemoteUrl(v()+"/qing/workbench.do");x.setCoreRemoteUrl(w());x.setFunGetDsbIFrameUrl(C);x.setFunGetReportIFrameUrl(r);x.setFunGetOpenAnalysisUrl(G);x.setLinkageRemoteURL(v()+"/qing/linkage.do");com.kingdee.bos.qing.integration.ImglibUrlParser.hookUrlParser();I();J();var d=com.kingdee.bos.qing.behavior.BehaviorManager;
d.interestInBehaviorEntrance(d.ENTRANCE_WORKBENCH)};var w=function(){return v()+"/qing/core.do"},C=function(d){var e=v()+"/qing/publishEntrance.do";e=b.appendParamToUrl(e,"publishId",d);d=n.getUrlParam("pageId");e=b.appendParamToUrl(e,"pageId",d);e=b.appendParamToUrl(e,"openFrom","qing_workbench");(d=p.getUrlParamValue())&&(e=b.appendParamToUrl(e,"skin",d));(d=u.getUrlParamValue("language"))&&(e=b.appendParamToUrl(e,"language",d));return e=com.kingdee.bos.qing.integration.PageHelper.getIframeUrl(e)},
r=function(d,e,k,f,c){var a=v()+"/qing/extreportEntrance.do";a=b.appendParamToUrl(a,"publishId",d);a=b.appendParamToUrl(a,"exhibitionScene",e);a=b.appendParamToUrl(a,"publishTargetType",k);a=b.appendParamToUrl(a,"extreportWidgetId",f);a=b.appendParamToUrl(a,"extReportName",c);a=b.appendParamToUrl(a,"isFullScreen",!1);a=b.appendParamToUrl(a,"schemaBiztagId",f);(d=b.decodeParamFromUrl(location.search,"pageId"))&&(a=b.appendParamToUrl(a,"pageId",d));(d=p.getUrlParamValue())&&(a=b.appendParamToUrl(a,
"skin",d));(d=u.getUrlParamValue("language"))&&(a=b.appendParamToUrl(a,"language",d));return a=com.kingdee.bos.qing.integration.PageHelper.getIframeUrl(a)},v=function(){var d=b.decodeParamFromUrl(location.search,"path");return d?d:"/ierp"},G=function(d,e,k,f,c){var a=v()+"/qing/workbenchWidgetAnalysisEntrance.do";a=b.appendParamToUrl(a,"widgetBizId",e);a=b.appendParamToUrl(a,"schemaAdditionalTag",c);a=b.appendParamToUrl(a,"workbenchId",k);a=b.appendParamToUrl(a,"tag",d);a=b.appendParamToUrl(a,"refType",
f);(d=b.decodeParamFromUrl(location.search,"pageId"))&&(a=b.appendParamToUrl(a,"pageId",d));(d=p.getUrlParamValue())&&(a=b.appendParamToUrl(a,"skin",d));(d=u.getUrlParamValue("language"))&&(a=b.appendParamToUrl(a,"language",d));a=b.appendParamToUrl(a,"openFrom","qing_workbench");return a=com.kingdee.bos.qing.integration.PageHelper.getIframeUrl(a)},H=function(d){y.setCallback(function(){var e=b.decodeParamFromUrl(window.location.search,"path");e=e?e:"/ierp";com.kingdee.bos.qing.message.common.Integration.setRemoteUrl(e+
"/qing/messageManage.do");K(e);var k=new com.kingdee.bos.qing.message.ui.Main;k.setFunOpenMessageDialog(function(){k.setViewSize(null,5,10,null)});k.setMessageWidth(80);e=k.getJqUi(25);B.layoutCtrlWithLRTB(e,null,-5,null,10,null,null);e.appendTo(d)});y.loadSkinCss("message","message");y.loadSkinJs("message","skin");y.loadJs("message/message-manage-ui.js");y.loadI18n("message","message")},K=function(d){com.kingdee.bos.qing.message.common.Integration.setImportJSCodeForManager(function(){var e=com.kingdee.bos.qing.CodeLoader;
e.setCallback(function(){var k=com.kingdee.bos.qing.theme.message.panel.common.Integration;k.setFunPublishRemoteImpl(function(){var f=new com.kingdee.bos.qing.theme.message.panel.common.RemoteImpl;f.setRemoteUrl(d+"/qing/publishTo.do");return f});k.setFunQingCenterAndMenuEntrance(function(f,c,a,h){c=p.getUrlParamValue();var g=d+"/qing/publishEntrance.do";g=b.appendParamToUrl(g,"publishId",f);"extreport"==h?(g=b.appendParamToUrl(g,"appID","qing_rpt"),c&&(g=b.appendParamToUrl(g,"skin",c)),q.openNewTabInAppId(a,
g,g,q.QING_RPT)):(c&&(g=b.appendParamToUrl(g,"skin",c)),q.openNewTabInAppId(a,g,g,q.QING_ANALYSIS))});k.setResourceRemoteUrl(d+"/qing/resource.do");k.setDataModelEntrance(function(f,c,a){var h=p.getUrlParamValue();c=l.get("dataModeling","\u6570\u636e\u51c6\u5907")+"-"+c;var g=d+"/qing/dataModelingEntrance.do";g=b.appendParamToUrl(g,"themeID",f);g=b.appendParamToUrl(g,"isPreset",a);h&&(g=b.appendParamToUrl(g,"skin",h));q.openNewTabInAppId(c,g,g,q.QING_ANALYSIS)});k.setFunPublishContext(function(){var f=
new com.kingdee.bos.qing.publish.common.PublishContext;f.setParamPathPrefix(d);f.setLappEntranceUrl(d+"/qing/lappEntrance.do");f.setSpaceID(u.getUrlParamValue("qingID"));return f});k.setFunPublishedEmailLoginViewUrl(function(){var f=p.getUrlParamValue(),c=u.getUrlParamValue("language"),a=d+"/qing/publishedEmailEntrance.do?publishId=(publishId)";f&&(a=b.appendParamToUrl(a,"skin",f));c&&(a=b.appendParamToUrl(a,"language",c));return a});k.setFunPublishedEmailAnonymousViewUrl(function(){var f=p.getUrlParamValue(),
c=u.getUrlParamValue("language"),a=d+"/index.html?userId=Guest&accountId=(accountId)&appNumber=qing&formId=qing_analysis_pub_email#/dform?appNumber=qing&formId=qing_analysis_pub_email&publishId=(publishId)";f&&(a=b.appendParamToUrl(a,"skin",f));c&&(a=b.appendParamToUrl(a,"language",c));return a});k.setFunPublishContentEditEntrance(function(){return function(f,c,a){var h=com.kingdee.bos.qing.publish.model.PublishTargetType;if(a&&h.MOBILE==a){h=f.getPublishId();var g=f.getId()}else h=f.getId();var m=
p.getUrlParamValue(),E=u.getUrlParamValue("language");a=d+"/qing/publishContentEditEntrance.do";a=b.appendParamToUrl(a,"skin",m);a=b.appendParamToUrl(a,"language",E);a=b.appendParamToUrl(a,"publishId",h);g&&(a=b.appendParamToUrl(a,"lappId",g));g=a;c&&(h="editPublishedContent-"+h,m=com.kingdee.bos.qing.publish.common.PublishSubscribeHelper,m.putSubscribe(h,c),a=b.appendParamToUrl(a,"subscribeKey",h),a=b.appendParamToUrl(a,"currentPageClientId",m.getCurrentPageClientId()));c=com.kingdee.bos.qing.framework.common.TabbedUiUtil;
c.openNewTabInAppId(l.get("editPublishedContent","\u7f16\u8f91\u53d1\u5e03\u65b9\u6848-")+f.getName(),a,g,c.QING_ANALYSIS)}});k.setFunTimedPushContentEditEntrance(function(){return function(f){var c=d+"/qing/timedPushContentEditEntrance.do",a=l.get("editTimedPushContent","\u7f16\u8f91\u63a8\u9001\u65b9\u6848");if(f instanceof com.kingdee.bos.qing.timedpush.model.EmailConfig){var h=f.getId(),g=f.getPublishSourceType();m=f.getSchemaSourceType();c=b.appendParamToUrl(c,"configId",h);c=b.appendParamToUrl(c,
"publishSourceType",g);c=b.appendParamToUrl(c,"schemaType",m);c=b.appendParamToUrl(c,"pushTarget","email");a=a+"-"+f.getNameRule().getName();f.isSourceNameNotFound()&&(c=b.appendParamToUrl(c,"errorCode","2301001"))}else{h=f.getId();g=f.getPushTargetType();var m=f.getSchemaType();c=b.appendParamToUrl(c,"configId",h);c=b.appendParamToUrl(c,"pushTargetType",g);c=b.appendParamToUrl(c,"schemaType",m);c=b.appendParamToUrl(c,"pushTarget","lapp");a=a+"-"+f.getName();f.getSourceName()||(c=b.appendParamToUrl(c,
"errorCode","2301001"))}f=p.getUrlParamValue();m=u.getUrlParamValue("language");f&&(c=b.appendParamToUrl(c,"skin",f));m&&(c=b.appendParamToUrl(c,"language",m));f=com.kingdee.bos.qing.framework.common.TabbedUiUtil;f.openNewTabInAppId(a,c,c,f.QING_ANALYSIS)}});k=com.kingdee.bos.qing.modeler.message.panel.common.Integration;k.setMessageRemoteUrl(d+"/qing_modeler/message.do");k.setFunOpenModelSetPage(function(f,c){var a=p.getUrlParamValue(),h=l.get("modelSet","\u6a21\u578b\u96c6-")+c,g=d+"/qing_modeler/modelSetMainPage.do";
g=b.appendParamToUrl(g,"modelSetId",f);g=b.appendParamToUrl(g,"modelSetName",c);g=b.appendParamToUrl(g,"currentPageClientId",com.kingdee.bos.qing.framework.common.RemoteFramework.getClientID());a&&(g=b.appendParamToUrl(g,"skin",a));q.openNewTabInAppId(h,g,g,q.QING_MODELER)});k.setFunOpenModelDesign(function(f,c,a,h,g){var m=com.kingdee.bos.qing.modeler.message.panel.common.ModelType,E=p.getUrlParamValue();g=(g=m.getModelTypeText(g))?g+"-"+a:a;m=d+"/qing_modeler/deployDesignerEntrance.do";m=b.appendParamToUrl(m,
"modelSetId",f);m=b.appendParamToUrl(m,"modelId",c);m=b.appendParamToUrl(m,"modelName",a);m=b.appendParamToUrl(m,"modelDeployId",h);E&&(m=b.appendParamToUrl(m,"skin",E));q.openNewTabInAppId(g,m,m,q.QING_MODELER)})});e.loadSkinCss("message","messagepanel");e.loadSkinJs("message","skin");e.loadJs("message/message-content-panel-management.js");e.loadI18n("message","messagepanel");e.loadSkinCss("qingmodeler/message","message-modeler-panel");e.loadSkinJs("qingmodeler/message","skin");e.loadJs("qingmodeler/message/message-content-panel-management.js");
e.loadI18n("qingmodeler/message","message-modeler-panel")})},I=function(){var d=new t;d.setDelay(100);d.setCallback(function(){for(var k=0;k<z.length;k++)(0,z[k])()});d.observe();com.kingdee.bos.qing.assistant.common.Integration.setSquareExhibitionLoader(L);com.kingdee.bos.qing.assistant.common.Integration.setOpenDesigner(M);com.kingdee.bos.qing.assistant.common.Integration.setRemoteUrl(v()+"/qing/gpt.do");d=com.kingdee.bos.qing.Seer.getUrlParamValue("showAssistantEntrance");var e=com.kingdee.bos.qing.Seer.getUrlParamValue("showAssistantPanel");
com.kingdee.bos.qing.assistant.common.Integration.setShowAssistantEntrance("true"==d);com.kingdee.bos.qing.assistant.common.Integration.setShowAssistantPanel("true"==e)},L=function(d,e,k,f,c){var a=w(),h=new F;h.setRemoteUrl(a);h.setRemoteTag(d);h.setSchemaContent(k);h.setSchemaLoadCallback(function(g){f(g)});h.setExecutedListener(function(g){c(g,h.createChartInfoUi,h.showChartInfo,h.createInsightUi,h.createInsightContentMaker,h.redraw,h.changeChartType)});z.push(h.redraw);h.show(e)},M=function(d,
e,k,f){var c=new com.kingdee.bos.qing.workbench.DesignerScene,a=function(h){c.hide();h&&f(h)};c.setIsSquare(!0);c.setRemoteUrl(w());c.setRemoteTag(d);c.setTag(d);c.setSquareOrLonger(!0);c.setClosable(!0);c.hideResetBtn();c.setSchemaLoader(function(h,g){h.setJsonModelBook(k);g(!0)});c.setSchemaSaver(function(h){h=h.getJsonModelBook();a(h)});c.setSchemaReseter(function(h){a(null)});c.show(e,function(){a(null)})},J=function(){var d=com.kingdee.bos.qing.map.common.Integration,e=v();d.setRemoteUrl(e+"/qing/mapManage.do");
var k=new com.kingdee.bos.qing.map.integration.MapSelectorDialog;com.kingdee.bos.qing.core.MapLibraryRegister.registerTemplateSelector(function(f,c){k.setParamPathPrefix(e);k.showDialog(f,c)})}};var b,B,A,y,q,x,l,t,p,u;(function(){var n=com.kingdee.bos.qing;y=n.CodeLoader;p=n.SkinUtil;u=n.Seer;n=com.kingdee.bos.qing.common;b=n.Util;B=n.DomUtil;n=com.kingdee.bos.qing.framework.common;q=n.TabbedUiUtil;l=n.MultilanguageManager.createPackageAccessor(D);t=n.WindowResizeObserver;n=com.kingdee.bos.qing.workbench;
A=n.WorkbenchEntrance;n=com.kingdee.bos.qing.workbench.common;x=n.Integration})()})();
//qingVersionTag: 20250324