var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,d){a instanceof String&&(a=String(a));for(var f=a.length,e=0;e<f;e++){var l=a[e];if(b.call(d,l,e,a))return{i:e,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,f):$jscomp.polyfillUnisolated(a,b,d,f))};$jscomp.polyfillUnisolated=function(a,b,d,f){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];if(!(e in d))return;d=d[e]}a=a[a.length-1];f=d[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,f){var e=a.split(".");a=1===e.length;f=e[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<e.length-1;l++){var p=e[l];if(!(p in f))return;f=f[p]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?f[e]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(d=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+d+"$"+e),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,d){return $jscomp.findInternal(this,b,d).v}},"es6","es3");
(function(){"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});"undefined"==typeof com.kingdee.bos.qing.management&&(com.kingdee.bos.qing.management={});"undefined"==typeof com.kingdee.bos.qing.management.handover&&(com.kingdee.bos.qing.management.handover={});var a=com.kingdee.bos.qing.management.handover;a.MainUI=function(){p.call(this);var g=
this,w=!0,x=!1;this.initJqUiCallback=function(){var c=b.get("handOverRecordDesc","\u7ba1\u7406\u5458 #1 \u5c06\u6570\u636e\u5185\u5bb9\u4ece #2 \u79fb\u4ea4\u7ed9 #3").replace("#1","<b style='color: rgb(51, 51, 51)'>#1</b>").replace("#2","<b style='color: rgb(51, 51, 51)'>#2</b>").replace("#3","<b style='color: rgb(51, 51, 51)'>#3</b>");g.setHandOverReCordDescTemplate(c)};this.handOverCallback=function(c,h,k){c&&0<c.length&&com.kingdee.bos.qing.timedpush.LappIntegration.handover(l.getPublishRemoteImpl(),
c,h,k,function(m){console.log("\u79fb\u52a8\u7aef\u79fb\u4ea4\u6210\u529f: "+m)},function(m,n){console.error("\u79fb\u52a8\u7aef\u79fb\u4ea4\u5931\u8d25: "+n);return!1})};this.setSearchBoxProps=function(c){c.setPlaceholder(b.get("searchBoxPlaceholder","\u641c\u7d22\u6765\u6e90\u540d\u79f0/\u6765\u6e90\u8def\u5f84/\u53d1\u5e03\u540d\u79f0/\u63a8\u9001\u540d\u79f0/\u53d1\u5e03\u8def\u5f84"));var h=c.getJqUi();c=h.find(":input");c.focus(function(){h.css({width:"520px"})});c.blur(function(){h.css({width:"180px"})})};
this.createTableHead=function(c){c.addColumns(8);c.getColumn(0).setWidth(15);c.getColumn(1).setWidth(80);c.getColumn(2).setWidth(50);c.getColumn(3).setWidth(50);c.getColumn(4).setWidth(50);c.getColumn(5).setWidth(80);c.getColumn(6).setWidth(50);c.getColumn(7).setWidth(120);c=d.createHeadRow(c);c.getCell(0).setValue("");c.getCell(1).setValue(b.get("sourceName","\u6765\u6e90\u540d\u79f0"));c.getCell(2).setValue(b.get("sourceType","\u6765\u6e90\u7c7b\u578b"));c.getCell(3).setValue(b.get("sourcePathName",
"\u6765\u6e90\u8def\u5f84"));c.getCell(4).setValue(b.get("sourceCreator","\u62e5\u6709\u8005"));c.getCell(5).setValue(b.get("publishName","\u53d1\u5e03/\u63a8\u9001\u540d\u79f0"));c.getCell(6).setValue(b.get("publishType","\u7c7b\u578b"));c.getCell(7).setValue(b.get("publishPath","\u53d1\u5e03\u8def\u5f84"));g.setTableColumnIndex(0,1,2,3,4,5,6,7)};this.loadHandOverInfo=function(c){var h=!1,k=0;a:for(;k<c.length;k++){var m=c[k],n=0;for(;n<m.length;n++)if(2==m[n].getPublishToType()){h=!0;break a}}return h&&
!w?(g.getMessageCurtain().showPrompt(b.get("currentUserLackOpenId","\u83b7\u53d6\u5f53\u524d\u7528\u6237\u8f7b\u5e94\u7528\u4fe1\u606f\u5931\u8d25\uff0c\u8bf7\u5148\u540c\u6b65\u5f53\u524d\u7528\u6237\u8f7b\u5e94\u7528\u4fe1\u606f\u3002"),2E3),!1):h&&x?(g.getMessageCurtain().showPrompt(b.get("loadLappFailed","\u83b7\u53d6\u79fb\u52a8\u7aef\u53d1\u5e03\u4fe1\u606f\u5931\u8d25\uff0c\u65e0\u6cd5\u79fb\u4ea4\u79fb\u52a8\u7aef\u53d1\u5e03\u4fe1\u606f\u3002"),2E3),!1):!0};this.loadPublishAppTypeMap=function(c,
h,k){for(var m=[],n=0;n<h.length;n++){var y=h[n];z(y)&&m.push(y.getPubId())}var r={};0<m.length?f.loadHandoverDirName(l.getPublishRemoteImpl(),m,c,function(v){for(var t=0;t<h.length;t++){var q=h[t];if(z(q)){var u=v[q.getPubId()];u&&(q.setPubPathName(b.get("lightapp","\u79fb\u52a8\u8f7b\u5e94\u7528\uff1a")+u.directoryName),q.setPubName(u.analysisName),r[q.getPubId()]=u.appType)}}k&&k(r)},function(v,t){0==v&&(w=!1);k&&k(r);x=!0;return!1}):k&&k(r)};var z=function(c){return c.getPubId()&&c.getPublishToType()==
e.MOBILE&&"lightapp"==c.getPubPath()}};var b,d,f,e,l,p;(function(){var g=com.kingdee.bos.qing.framework.common;b=g.MultilanguageManager.createPackageAccessor(a);g=com.kingdee.bos.qing.common.ui;d=g.TableUtil;g=com.kingdee.bos.qing.timedpush;f=g.LappIntegration;g=com.kingdee.bos.qing.publish.model;e=g.PublishTargetType;g=com.kingdee.bos.qing.handover.common;l=g.HandOverIntegration;p=g.AbstractHandOverPanel})()})();
//qingVersionTag: 20250324