(function(){function H(d){var h=d.getRootPath();this.setRootPath=function(f){h=f};var a=[],m=[];this.pushJs=function(f){w(m,f);a.push([h,f])};var l=[],q=[];this.pushCss=function(f){w(q,f);l.push([h,f])};var r=[],u=[];this.pushSkinJs=function(f,e){w(u,f+"//"+e);r.push([h,f,e])};var k=[],z=[];this.pushSkinCss=function(f,e){w(z,f+"//"+e);k.push([h,f,e])};var y=[],A=[];this.pushI18n=function(f,e){w(A,f+"//"+e);y.push([h,f,e])};var w=function(f,e){e=h+"|"+e;if(f[e])throw Error("Duplicated: "+e);f[e]=!0};
this.load=function(f){f&&d.setCallback(f);for(f=0;f<a.length;f++){var e=a[f],v=e[0],t=e[1];d.setRootPath(v);d.loadJs(t)}for(f=0;f<l.length;f++)e=l[f],v=e[0],t=e[1],d.setRootPath(v),d.loadCss(t);for(f=0;f<r.length;f++)e=r[f],v=e[0],t=e[1],e=e[2],d.setRootPath(v),d.loadSkinJs(t,e);for(f=0;f<k.length;f++)e=k[f],v=e[0],t=e[1],e=e[2],d.setRootPath(v),d.loadSkinCss(t,e);for(f=0;f<y.length;f++)e=y[f],v=e[0],t=e[1],e=e[2],d.setRootPath(v),d.loadI18n(t,e)}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&
(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});var n=com.kingdee.bos.qing;n.CodeLoader=new function(){var d=this,h=null,a=[],m=!1,l,q="/",r=".",u="pioneer",k="zh_CN",z={},y=[],A=!1,w;this.createSafety=function(){return new H(d)};var f=function(){m=!0;var b=new XMLHttpRequest;b.open("GET",r+"/resources.json?version="+(new Date).getTime(),!0);b.setRequestHeader("Content-type","application/json");b.onreadystatechange=
function(){if(4==b.readyState){if(200==b.status)try{h=JSON.parse(b.responseText)}catch(p){window.console&&console.log(p)}!h&&(h={});for(var c=0;c<a.length;c++){var g=a[c];F(g[0],g[1],g[2])}a=null;m=!1}};b.send()};this.getIconUrl=function(b,c){c&&(b=b+"/skin/"+u+"/res/"+c);return v(r,b)};this.setRootPath=function(b){r=b};this.getRootPath=function(){return r};this.setSkinName=function(b){u=b};this.getSkinName=function(){return u};this.setI18nLocal=function(b){k=b};this.setCdnUrls=function(b){l=b};this.setUrlBase=
function(b){var c=window.location.protocol+"//"+window.location.host+window.location.pathname,g=c.lastIndexOf("/");c=c.substring(0,g);g=c.indexOf(b);if(0<=g)c=c.substring(g+b.length);else throw Error("It must be part of current URL.");q=c};this.setCallback=function(b){e(b)};this.loadJsBatch=function(b,c){e(c);c=!1;for(var g=0;g<b.length;g++){var p=b[g],x=v(r,p);z[x]||(c=!0,t(p,"js"))}c||setTimeout(B,0)};this.loadJs=function(b,c){e(c);t(b,"js")};this.loadCss=function(b,c){e(c);t(b,"css")};this.loadSkinJs=
function(b,c,g){e(g);t((b?b+"/":"")+"skin/"+u+"/"+c+".js","js")};this.loadSkinCss=function(b,c,g){e(g);t((b?b+"/":"")+"skin/"+u+"/"+c+".css","css")};this.loadI18n=function(b,c,g){e(g);t((b?b+"/":"")+"i18n/"+c+"-"+k+".js","js")};var e=function(b){b&&(!w&&(w=[]),w.push(b))},v=function(b,c){if("."==b){var g=l?l.length:0;if(0==g)g="";else if(1==g)g=l[0];else{for(var p=0,x=0;x<c.length;x++)p+=c.charCodeAt(x);g=l[p%g]}g&&(b=q)}else if("/"==b.charAt(0))g="";else throw Error("Unsupported");p="";h&&(x=h[c])&&
(p="?version="+x);return g+(b?b+"/":"")+c+p},t=function(b,c){h?F(r,b,c):(a.push([r,b,c]),m||f())},F=function(b,c,g){b=v(b,c);y.push([b,g]);A||(A=!0,B())},B=function(){if(0<y.length){var b=y.shift(),c=b[0];b=b[1];if(z[c])setTimeout(B,0);else switch(b){case "js":I(c);break;case "css":J(c);break;default:throw Error("I don't know: "+b);}}else if(A=!1,w)for(c=w,w=null,b=0;b<c.length;b++)(0,c[b])()},I=function(b){var c=document.createElement("script");c.src=b;c.onerror=function(){E(b)};c.onload=function(){C(b)};
document.head.appendChild(c)},J=function(b){var c=document.createElement("link");c.rel="stylesheet";c.href=b;var g=536>navigator.userAgent.replace(/.*(?:AppleWebKit|AndroidWebKit)\/?(\d+).*/i,"$1"),p="onload"in c;g||!p?(document.head.appendChild(c),setTimeout(function(){G(b,c,g,0)},1)):(p?(c.onerror=function(){E(b)},c.onload=function(){C(b)}):c.onreadystatechange=function(){/loaded|complete/.test(c.readyState)?C(b):E(b)},document.head.appendChild(c))},C=function(b){z[b]=!0;B()},E=function(b){window.console&&
console.error("Loading error: "+b);z[b]=!1;B()},G=function(b,c,g,p){var x=c.sheet;p+=1;if(3E5<p){var D=!0;c=null;C(b)}else{if(g)x&&(D=!0);else if(x)try{x.cssRules&&(D=!0)}catch(K){"NS_ERROR_DOM_SECURITY_ERR"===K.name&&(D=!0)}setTimeout(function(){D?C(b):G(b,c,g,p)},20)}}};n.CommonCodeImporter=new function(){var d=this;this.importRemoteProxy=function(a){a.loadJsBatch(["jquery/jquery.js","common/qing-table.js","common/qing-common.js","common/qing-remote-proxy.js"]);a.loadSkinJs("common","skin");a.loadI18n("common",
"qing-common");a.loadSkinCss("common","qing-ui-component")};this.importCode=function(a){a.loadJsBatch("jquery/jquery.js common/qing-table.js common/qing-common.js common/qing-framework-remote.js core/qing-charts.js core/qing-main.js core/qing-scene.js".split(" "))};this.importSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinJs("core","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinCss("core","qing")};this.importI18n=function(a){a.loadI18n("common","qing-common");a.loadI18n("core",
"qing-core")};this.importDashboardDesignerCode=function(a){d.importCode(a);a.loadJsBatch(["dashboard/dsb-main.js","dashboard/dsb-scene.js"])};this.importDashboardDesignerSkin=function(a){d.importSkin(a);a.loadSkinJs("dashboard","skin");a.loadSkinCss("dashboard","dsb")};this.importDashboardDesignerI18n=function(a){d.importI18n(a);a.loadI18n("dashboard","dsb")};this.importMapDesignerCode=function(a){a.loadJsBatch("jquery/jquery.js common/qing-table.js common/qing-common.js common/qing-framework-remote.js core/qing-charts.js map-designer/map-designer.js".split(" "))};
this.importMapDesignerSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinJs("map-designer","skin");a.loadSkinCss("map-designer","map-designer")};this.importMapDesignerI18n=function(a){a.loadI18n("common","qing-common");a.loadI18n("map-designer","map-designer")};this.importDataModelingCode=function(a){a.loadJs("jquery/jquery.js");a.loadJs("common/qing-table.js");a.loadJs("common/qing-common.js");a.loadJs("common/qing-framework-remote.js");a.loadJs("common/qing-schedule.js");
a.loadJs("biz-common/qing-biz-common.js");a.loadJs("data-modeling/qing-data-modeling.js")};this.importDataModelingSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinJs("biz-common","skin");a.loadSkinJs("data-modeling","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinCss("biz-common","biz-common");a.loadSkinCss("data-modeling","dm-relationview");a.loadSkinCss("data-modeling","dm")};this.importDataModelingI18n=function(a){a.loadI18n("common","qing-common");a.loadJs("common/qing-framework-remote.js");
a.loadI18n("common","qing-schedule");a.loadI18n("biz-common","biz-common");a.loadI18n("data-modeling","qing-dm")};this.importLongerMobileCode=function(a,m){h(a,m);a.loadJs("lightapp/core/qing-lapp-longer-ui.js");a.loadJs("lightapp/scene/qing-lapp-longer-scene.js")};this.importSquareMobileCode=function(a,m){h(a,m);a.loadJs("lightapp/core/qing-lapp-square-ui.js");a.loadJs("lightapp/scene/qing-lapp-square-scene.js")};this.importDsbMobileCode=function(a,m){h(a,m);a.loadJs("dashboard/dsb-main-mobile.js");
a.loadJs("lightapp/dashboard/dsb-widget-ctrl-mobile.js");a.loadJs("dashboard/dsb-scene.js");a.loadJs("lightapp/core/qing-lapp-dsb-ui.js");a.loadJs("lightapp/scene/qing-lapp-dsb-scene.js")};var h=function(a,m){a.loadJs("common/qing-table.js");a.loadJs("common/qing-common.js");a.loadJs("common/qing-framework-remote.js");m?(a.loadJs("core/qing-charts.js"),a.loadJs("core/qing-main.js")):(a.loadJs("core/qing-mobile-charts.js"),a.loadJs("core/qing-mobile-main.js"));a.loadJs("core/qing-scene.js");a.loadJs("lightapp/common/qing-lapp-common.js")};
this.importLappSkin=function(a){a.loadSkinJs("common","skin");a.loadSkinJs("core","skin");a.loadSkinCss("common","qing-ui-component");a.loadSkinCss("core","qing");a.loadCss("lightapp/common/qing-lapp.css")};this.importLappI18n=function(a){a.loadI18n("common","qing-common");a.loadI18n("core","qing-core");a.loadI18n("lightapp/core","qing-lapp-core")};this.lazyImportFunctionProvider=function(a){n.CodeLoader.setCallback(a);n.CodeLoader.loadJs("common/qing-functions.js");n.CodeLoader.loadI18n("common",
"qing-formula")}};n.Seer=new function(){this.getUrlParamValue=function(d){var h=window.location.search,a=d+"=";for(d=-1;!(d=h.indexOf(a,d+1),0>=d);){var m=h.charAt(d-1);if("&"==m||"?"==m)break}return-1!=d?(d+=a.length,a=h.indexOf("&",d),a=-1==a?h.length:a,window.decodeURIComponent(h.substring(d,a))):null}};n.SkinUtil=new function(){var d,h,a;this.setUrlParamValue=function(l){(l=l?l.split("_"):null)?(d=l[0],a=1<l.length?l[1]:null):a=d=null;h="curio"==d?"ierp":d};this.getUrlParamValue=function(){return d?
a?d+"_"+a:d:null};this.isModernStyle=function(){return"ierp"==d};this.getCssFolder=function(){return h};this.makeColorEffective=function(){a&&m(a)};this.changeColorTheme=function(l){a=l;m(a)};var m=function(l){var q=com.kingdee.bos.qing.common.ColorUtil,r=q.decodeStringToRgbArray(l),u=q.rgbToHsv(r[0],r[1],r[2]),k=u[0],z=u[1]/100,y=u[2]/100;u=q.hsvToRgb(60<=k&&240>=k?0>k-2?k-2+360:k-2:360<k+2?k+2-360:k+2,Math.round(100*Math.max(.05,z-.18)),Math.round(100*Math.min(1,y+.08)));k=q.hsvToRgb(60<=k&&240>=
k?0>k-10?k-10+360:k-10:360<k+10?k+10-360:k+10,Math.round(100*Math.max(.05,z-.9)),Math.round(100*Math.min(1,y+.4)));q={};q["--color-main"]=l;q["--color-lightish"]="rgb("+u.join(",")+")";q["--color-tint"]="rgba("+r.join(",")+",0.5)";q["--color-pale"]="rgb("+k.join(",")+")";l=document.body.style;for(var A in q)l.setProperty(A,q[A])}};(function(){var d=n.Seer.getUrlParamValue("skin");n.SkinUtil.setUrlParamValue(d);(d=n.SkinUtil.getCssFolder())&&n.CodeLoader.setSkinName(d);(d=n.Seer.getUrlParamValue("language"))&&
n.CodeLoader.setI18nLocal(d);(d=n.Seer.getUrlParamValue("cdnUrl"))&&n.CodeLoader.setCdnUrls(d.split(";"));(d=n.Seer.getUrlParamValue("path"))&&n.CodeLoader.setUrlBase(d)})()})();
//qingVersionTag: 20250324