(function(){function O(){com.kingdee.bos.qing.framework.common.AbstractRemoteCall.call(this);var a,b;this.getRemoteUrl=function(d){b&&(d.dashboardUniqueId=b);return a};this.setRemoteUrl=function(d){a=d};this.setDashboardUniqueId=function(d){b=d}}function P(){var a=this;this.getParamLanguage=function(){return a.getUrlParam("language")};this.getParamPathPrefix=function(){return a.getUrlParam("path")};this.getUrlParam=function(b){return com.kingdee.bos.qing.common.Util.decodeParamFromUrl(window.location.search,
b)}}function G(){var a,b,d,t,w;(function(){var g=com.kingdee.bos.qing;a=g.CodeLoader;g=com.kingdee.bos.qing.framework.common;b=g.WebPageInitializer;d=g.WindowResizeObserver;t=g.FontLibSupporter;g=com.kingdee.bos.qing.core;w=g.UserOperationReporter})();var h=this,e=new P,q,n;this.getRemoteImpl=function(){q||(q=new O,q.setRemoteUrl(h.protectedGetRemoteUrl()),q.setDashboardUniqueId(h.protectedGetDashboardUniqueId()));return q};this.preload=function(g){a.setCallback(function(){t.setupWebPage(g)});x.CommonCodeImporter.importDashboardDesignerSkin(a);
x.CommonCodeImporter.importDashboardDesignerI18n(a);var r=a.createSafety();h.protectedImportMoreCode(r);r.load()};this.start=function(){C();h.protectedCustomInitEnv();h.protectedRegisterImplements(com.kingdee.bos.qing.dsb.IntegrationRegister);var g=$(document.body);g.css("overflow","hidden");n=h.protectedCreateMain();var r=n.createJqUi();r.css("z-index",1);r.appendTo(g);n.resize();h.protectedLoading(h.getRemoteImpl(),n,function(z){h.protectedAfterLoaded(z,n)})};this.protectedCreateMain=function(){throw Error("Override");
};var C=function(){b.init();w.hookCollector(function(r,z){com.kingdee.bos.qing.behavior.BehaviorManager.interestInBehavior(r,z)});v();var g=new d;g.setCallbackImmediately(function(){v()});g.setDelay(250);g.setCallback(function(){n.resize()});g.observe()},v=function(){document.body.style.height=document.documentElement.clientHeight+"px"};this.protectedGetRemoteUrl=function(){throw Error("Override");};this.protectedGetDashboardUniqueId=function(){throw Error("Override");};this.protectedImportMoreCode=
function(g){};this.protectedCustomInitEnv=function(){};this.protectedRegisterImplements=function(g){throw Error("Override");};this.protectedLoading=function(g,r,z){throw Error("Override");};this.protectedAfterLoaded=function(g,r){};this.protectedMethod={getUrlParamUtil:function(){return e},reload:function(){h.protectedLoading(h.getRemoteImpl(),n,function(g){})}}}function D(){this.setSkinName=function(a){throw Error("Override");};this.setRemoteTag=function(a){throw Error("Override");};this.setExecutedListener=
function(a){throw Error("Override");};this.show=function(a,b){throw Error("Override");};this.setJsonModelBook=function(a,b,d){throw Error("Override");};this.executeWithoutRendering=function(a,b){throw Error("Override");};this.reExecute=function(){throw Error("Override");};this.redraw=function(){throw Error("Override");};this.displayError=function(a,b){throw Error("Override");};this.setBlocking=function(a){throw Error("Override");};this.destroy=function(){throw Error("Override");};this.executeOutputParamValue=
function(a,b,d,t){throw Error("Override");};this.setFilteringListener=function(a){throw Error("Override");};this.displayActionPrompt=function(a,b){throw Error("Override");}}function H(){var a;this.setLongerDesignerOperationJudgerGetter=function(b){a=b};this.protectedLoadDesignerOperationJudger=function(b){var d=a();b(d)}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&
(com.kingdee.bos.qing={});var x=com.kingdee.bos.qing;x.AbstractDashboardDesignerScene=function(){G.call(this);var a=this;this.protectedCreateMain=function(){var b=new com.kingdee.bos.qing.dsb.ui.Designer;b.setRemoteImpl(a.getRemoteImpl());a.protectedInitDesigner(b);return b};this.protectedInitDesigner=function(b){};this.protectedAfterLoaded=function(b,d){!b&&d.born()}};x.AbstractDashboardExhibitionScene=function(){var a=com.kingdee.bos.qing.common.FullScreenHelper,b=com.kingdee.bos.qing.common.DomUtil,
d=com.kingdee.bos.qing.framework.common.MultilanguageManager.createPackageAccessor(com.kingdee.bos.qing.dsb.ui),t=com.kingdee.bos.qing.ui.component.Label,w=com.kingdee.bos.qing.ui.component.WorkButton,h=com.kingdee.bos.qing.dsb.Facade,e=com.kingdee.bos.qing.dsb.widget.ExhibitionModePanel,q=com.kingdee.bos.qing.dsb.commonui.CornerMenu;G.call(this);var n=this,C=this.protectedMethod,v,g=!1,r=!1,z,B,I=18E5;this.protectedCreateMain=function(){var c=new com.kingdee.bos.qing.dsb.ui.Executor;c.setCachedExhibitionMode(J());
c.setRemoteImpl(n.getRemoteImpl());c.setUiCreatedAnnouncer(function(){setTimeout(function(){v.setup($(document.body),128)},0)});c.setLayerCoverOthers(129);return c};this.protectedAfterLoaded=function(c,k){v||(v=new q,v.setMenuItem(0,"","",Q),v.setMenuItem(1,"refresh",d.get("refresh","\u5237\u65b0"),function(){k.hasSlideshow()&&(r=!1,E());C.reload()}),k.hasSlideshow()&&(v.setMenuItem(2,"","",function(){r=!r;k.slideshowPause(r);E()},!0),E()),v.setMenuItem(3,"info",d.get("about","\u5173\u4e8e")+"...",
function(){R(k)}),K(),a.addChangedListener(function(f){null==f?g=!1:f==document.body&&(g=!0);K();g?(L(),k.reparseRelativeDate()&&F(k)):(clearTimeout(z),B&&clearTimeout(B))}))};var Q=function(){g?a.exit():a.request(document.body)},L=function(){S();z=setTimeout(L,6E5)},S=function(){(new h(n.getRemoteImpl(),function(c){},function(c,k,f){console.error("keepAlive() error. ErrorCode:"+c+". "+k);return!0})).runtimeKeepAlive()},F=function(c){B&&clearTimeout(B);B=setTimeout(function(){c.reparseRelativeDate()&&
F(c)},I)},K=function(){var c=g?"quitFullscreen":"fullscreen",k=g?d.get("exitFullScreen","\u9000\u51fa\u5168\u5c4f"):d.get("requestFullScreen","\u5168\u5c4f");v.setMenuItem(0,c,k,null)},E=function(){var c=r?"play":"pause",k=r?d.get("play","\u7ee7\u7eed\u8f6e\u64ad"):d.get("pause","\u6682\u505c\u8f6e\u64ad");v.setMenuItem(2,c,k,null)},R=function(c){var k=new q.ConfigDialog;k.setContextCreator(function(f){n.protectedLoadDashboardInfo(f)});k.setEnvCreator(function(f){f.text(c.getEnvironmentDescription());
T(f,c)});k.setPersonalizationCreator(function(f){U(f,c)});k.show(d.get("about","\u5176\u5b83"),v)};this.protectedLoadDashboardInfo=function(c){c.text("...");setTimeout(function(){c.text("TODO")},1E3)};var T=function(c,k){c.on("dblclick",function(f){if(3>f.offsetX&&3>f.offsetY){var m=$("<textarea style='width:420px;height:80px'>");f=$("<button>Run</button>");c.append(m);c.append(f);f.on("click",function(p){p=m.val();(new Function("var oTester = arguments[0];"+p))({changeRelativeDateTestableCurrentTime:function(l){var u=
new h(n.getRemoteImpl(),function(y){console.log(JSON.stringify(y))});l=l?(new Date(l)).getTime():null;u.changeTestableCurrentTimeForRelativePeriod(l)},changeRelativeDateReparseInterval:function(l){I=1E3*l;F(k)}})})}})},J=function(){var c=(new Date).getTime(),k=c-864E7,f=null,m=window.localStorage.getItem("kd.qing.dsb.ExhibitionScene.layout");if(m){var p=!1,l=n.protectedGetDashboardUniqueId();m=JSON.parse(m);for(var u=m.length-1;0<=u;u--){var y=m[u],A=y.lastTime;y.id==l?(f=y.layout,y.lastTime=c,p=
!0):A<k&&(m.splice(u,1),p=!0)}p&&(0==m.length?window.localStorage.removeItem("kd.qing.dsb.ExhibitionScene.layout"):window.localStorage.setItem("kd.qing.dsb.ExhibitionScene.layout",JSON.stringify(m)))}return f},M=function(c){var k=c?!1:!0,f=null,m=n.protectedGetDashboardUniqueId(),p=window.localStorage.getItem("kd.qing.dsb.ExhibitionScene.layout");if(p){var l=JSON.parse(p);for(p=l.length-1;0<=p;p--){var u=l[p];if(u.id==m){f=u;k&&l.splice(p,1);break}}}k?l&&(0==l.length?window.localStorage.removeItem("kd.qing.dsb.ExhibitionScene.layout"):
window.localStorage.setItem("kd.qing.dsb.ExhibitionScene.layout",JSON.stringify(l))):(f||(f={},f.id=m,!l&&(l=[]),l.push(f)),f.layout=c,f.lastTime=(new Date).getTime(),window.localStorage.setItem("kd.qing.dsb.ExhibitionScene.layout",JSON.stringify(l)))},U=function(c,k){var f=k.getFreshExhibitionMode(),m=J();!m&&(m=f);var p=new t(d.get("layout","\u6309\u53ef\u89c6\u753b\u9762\u8c03\u6574")),l=new w;l.setText(d.get("reset","\u91cd\u7f6e"));l.addActionListener(function(A){l.setEnabled(!1);M(null);u.setSelection(f);
k.updateLayoutAdapter(f)});l.setEnabled(m!=f);var u=new e;u.addSelectionChangedListener(function(A){var N=A==f;l.setEnabled(!N);M(N?null:A);k.updateLayoutAdapter(A)});var y=u.createJqUi();u.setSelection(m);b.layoutCtrl(p.getJqUi(),20,10,100,23);b.layoutCtrl(l.getJqUi(),320,10,80,23);b.layoutCtrl(y,20,50,400,100);c.append(p.getJqUi());c.append(l.getJqUi());c.append(y)}};x.DashboardSquareScene=function(){D.call(this);x.AbstractSquareDivScene.call(this);var a,b,d=!0,t,w,h=this.show;this.show=function(e,
q){a=q;h(e)};this.protectedLoadingImpl=function(e){b=e;a()};this.setJsonModelBook=function(e,q,n){return b(e,q,n)};this.setBlocking=function(e){d=e};this.protectedBlockingAllFrame=function(){return d?!1:null};this.protectedGetSkinName=function(){return t};this.setSkinName=function(e){t=e};this.protectedDisplayConsumingStatistics=function(e){w(e)};this.setConsumingStatisticsDisplayer=function(e){w=e}};x.DashboardLongerScene=function(){D.call(this);x.AbstractLongerDivScene.call(this);H.call(this);var a,
b,d=!0,t,w,h=this.show;this.show=function(e,q){a=q;h(e)};this.protectedLoadingImpl=function(e){b=e;a()};this.setJsonModelBook=function(e,q,n){return b(e,q)};this.setBlocking=function(e){d=e};this.protectedIsBlockingRemoteCall=function(){return d};this.protectedGetSkinName=function(){return t};this.setSkinName=function(e){t=e};this.protectedDisplayConsumingStatistics=function(e){w(e)};this.setConsumingStatisticsDisplayer=function(e){w=e}};x.AbstractMobileDashboardLongerScene=function(){D.call(this);
x.AbstractMobileLongerScene.call(this);H.call(this);var a,b,d,t=!0;this.setRemoteUrl=function(h){a=h};this.protectedGetRemoteUrl=function(){return a};this.setRemoteTag=function(h){b=h};this.protectedGetRemoteTag=function(){return b};this.protectedIsWidthFitting=function(){return!1};this.protectedIsHeightFitting=function(){return!1};this.setSkinName=function(h){d=h};this.protectedGetSkinName=function(){return d};this.setBlocking=function(h){t=h};this.protectedIsBlockingRemoteCall=function(){return t};
var w=this.show;this.show=function(h,e){w(h);e()}}})();
//qingVersionTag: 20250324