var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(C,G,J){C instanceof String&&(C=String(C));for(var S=C.length,O=0;O<S;O++){var V=C[O];if(G.call(J,V,O,C))return{i:O,v:V}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(C,G,J){if(C==Array.prototype||C==Object.prototype)return C;C[G]=J.value;return C};$jscomp.getGlobal=function(C){C=["object"==typeof globalThis&&globalThis,C,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var G=0;G<C.length;++G){var J=C[G];if(J&&J.Math==Math)return J}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(C,G){var J=$jscomp.propertyToPolyfillSymbol[G];if(null==J)return C[G];J=C[J];return void 0!==J?J:C[G]};
$jscomp.polyfill=function(C,G,J,S){G&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(C,G,J,S):$jscomp.polyfillUnisolated(C,G,J,S))};$jscomp.polyfillUnisolated=function(C,G,J,S){J=$jscomp.global;C=C.split(".");for(S=0;S<C.length-1;S++){var O=C[S];if(!(O in J))return;J=J[O]}C=C[C.length-1];S=J[C];G=G(S);G!=S&&null!=G&&$jscomp.defineProperty(J,C,{configurable:!0,writable:!0,value:G})};
$jscomp.polyfillIsolated=function(C,G,J,S){var O=C.split(".");C=1===O.length;S=O[0];S=!C&&S in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var V=0;V<O.length-1;V++){var sa=O[V];if(!(sa in S))return;S=S[sa]}O=O[O.length-1];J=$jscomp.IS_SYMBOL_NATIVE&&"es6"===J?S[O]:null;G=G(J);null!=G&&(C?$jscomp.defineProperty($jscomp.polyfills,O,{configurable:!0,writable:!0,value:G}):G!==J&&(void 0===$jscomp.propertyToPolyfillSymbol[O]&&(J=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[O]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(O):$jscomp.POLYFILL_PREFIX+J+"$"+O),$jscomp.defineProperty(S,$jscomp.propertyToPolyfillSymbol[O],{configurable:!0,writable:!0,value:G})))};$jscomp.polyfill("Array.prototype.find",function(C){return C?C:function(G,J){return $jscomp.findInternal(this,G,J).v}},"es6","es3");
(function(){function C(){com.kingdee.bos.qing.framework.common.AbstractRemoteCall.call(this);var g,p,u;this.getRemoteUrl=function(q){q.skin=u;q.tag=p;return g};this.setRemoteUrl=function(q){g=q};this.setTag=function(q){p=q};this.setSkinName=function(q){u=q}}function G(){var g=this;this.getParamLanguage=function(){return g.getUrlParam("language")};this.getParamPathPrefix=function(){return g.getUrlParam("path")};this.getParamTag=function(){return g.getUrlParam("tag")};this.getUrlParam=function(p){return com.kingdee.bos.qing.common.Util.decodeParamFromUrl(window.location.search,
p)}}function J(){var g,p,u,q,m,f,e,v,B,H;(function(){var d=com.kingdee.bos.qing;g=d.CodeLoader;d=com.kingdee.bos.qing.common;p=d.DomUtil;d=com.kingdee.bos.qing.core;u=d.Facade;q=d.QingModelAssistant;d=com.kingdee.bos.qing.core.model;m=d.ModelBook;f=d.AbstractAnalyticalField;d=com.kingdee.bos.qing.core.controller;e=d.CommandManager;d=com.kingdee.bos.qing.longer.model;v=d.AnalyticalModel;B=d.FilterFieldSet;d=com.kingdee.bos.qing.longer.ui;H=d.ExecutedArea})();var x=this,y,D,K,r,N,E,I,M,w=[],h,b,n,z;
this.show=function(d){d=$(d?d:document.body);D=$("<div>");D.appendTo(d);D[0].addEventListener("contextmenu",function(F){F.ctrlKey&&(F.preventDefault(),x.protectedDisplayConsumingStatistics(x.protectedGetRemoteTag()))},!0);p.layoutCtrl(D,0,0,"100%","100%");K=$("<div>");K.appendTo(d);p.layoutCtrl(K,0,0,"100%","100%");b=new O;b.bindParentJqUi(K);g.setCallback(function(){N=new e;r=new H;r.setContextGetter(la());r.getJqUi().appendTo(D);p.layoutCtrl(r.getJqUi(),0,0,"100%","100%");ea();x.protectedInitMode();
x.protectedCustomInitEnv();x.protectedLoadingImpl(W)});X.CommonCodeImporter.importSkin(g);X.CommonCodeImporter.importI18n(g);x.protectedImportMoreCode(g)};this.displayError=function(d,F,L){aa(!1);ha([d,F,L])};this.displayActionPrompt=function(d,F){var L=new ta;L.setPromptText(F);L.show(d)};this.destroy=function(){r.destroy();z=n=null};this.setExecutedListener=function(d){n=d};this.setFilteringListener=function(d){z=d};this.redraw=function(){ea()};this.protectedGetRemoteUrl=function(){throw Error("Override");
};this.protectedGetRemoteTag=function(){throw Error("Override");};this.protectedImportMoreCode=function(d){};this.protectedInitMode=function(){};this.protectedCustomInitEnv=function(){};this.protectedLoadingImpl=function(d){throw Error("Override");};this.protectedGetSkinName=function(){return"white"};this.protectedIsBlockingRemoteCall=function(){return!0};this.protectedShowErrorImpl=function(d,F,L,ca){return!1};this.protectedDisplayConsumingStatistics=function(d){throw Error("Override");};var Q=function(){y||
(y=new C,y.setRemoteUrl(x.protectedGetRemoteUrl()));y.setTag(x.protectedGetRemoteTag());y.setSkinName(x.protectedGetSkinName());return y},W=function(d,F){var L=new m;L.fromJsonObject(d,new V);d=L.getModelPages()[0];E=L.getMeta();I=d.getModel();M=d.getPreferences();h=F;F=M.getExhibitionStatus();r.getExhibition().applyStatus(F);q.verifyLinkageBizMeta(I);I.addModelChangedListener(Y);ia();return L},Y=function(d){d.isContainKeys([v.KEY_SORTING_LANE,f.KEY_SORT])&&r.getExhibition().keepScrollStatus(!0);
d.isContainKey(B.KEY_FILTER_VALUE,I.getFilterFieldSet())&&(d=d.getTargetField(I.getFilterFieldSet(),B.KEY_FILTER_VALUE),w.push(d));N.untilWakeup(Z)},Z=function(){0<=ma()?ja():na()};this.reExecute=function(){return I?(ia(),!0):!1};this.executeWithoutRendering=function(d,F){var L;r.getExhibition().setRenderingInterceptor(function(ka){L=ka;F(null,null)});var ca=I?!0:!1;ca&&ia();d(ca,function(ka,ba){L()})};var na=function(){r.execute(function(d,F,L){d?(aa(!0),b.setErrorOccurred(!1)):(aa(!1),b.bindRetry(this,
na,[]),ha(F));n&&n(d)})},ja=function(){r.filteringExecute(ma(),function(d,F,L){d?(aa(!0),b.setErrorOccurred(!1),w=[]):(aa(!1),b.bindRetry(this,ja,[]),ha(F));n&&n(d)});z&&z()},ia=function(){r.christmasExecute(!0,function(d,F,L){d?(aa(!0),b.setErrorOccurred(!1),w=[]):(aa(!1),b.bindRetry(this,ia,[]),ha(F));n&&n(d)})},ma=function(){for(var d=w.length-1;0<=d;d--){var F=w[d];F=I.getFilterFieldSet().getIndex(F);if(0<=F)return F}return-1},qa=function(d,F,L){d=new u(Q(),d,F,L);x.protectedIsBlockingRemoteCall()?
(d.setShowBlocking(!0),d.setBlockingJqUi(D.parent())):d.setShowBlocking(!1);return d},ea=function(){r&&(r.resize(),I&&r.refreshRightLanes())},aa=function(d){d?(D.css("display",""),K.css("display","none")):(D.css("display","none"),K.css("display",""))},ha=function(d){K.empty();var F=d[0],L=d[1];d=d[2];b.setErrorOccurred(!0);b.highPriorityHandler(F,L)||x.protectedShowErrorImpl(K,F,L,d)||b.lowPriorityHandler(F,L,d)},oa=function(){var d=h?h():null;return d?d.toExecutableJsonObject():null},pa=function(){var d=
h?h():null;return d?d.toMetaFieldNames():null},ra=function(){return I},fa=function(d){x.protectedLoadDesignerOperationJudger(function(F){d(F)})};this.protectedLoadDesignerOperationJudger=function(d){throw Error("Override");};var la=function(){return{createFacade:qa,getTopJqUi:function(){return D},getCommandManager:function(){return N},getMeta:function(){return E},getAnalyticalModel:ra,getPreferences:function(){return M},getJsonAdditionalFilters:oa,getJsonAdditionalFieldNames:pa,loadDesignerOperationJudger:fa,
getBlockingJqUi:function(){return D.parent()}}};this.executeOutputParamValue=function(d,F,L,ca){var ka=d==I?oa():null,ba=new u(Q(),function(a){ca(a)},function(a,k,A){console&&console.warn("executeOutputParamValue error. "+a+", "+k);ca(null)});ba.setShowBlocking(!1);ba.setCancelable(!0);ba.executeBriefOutput(E,d,F,ka,L)};this.protectedMethod={createFacade:qa,resize:ea}}function S(){var g,p,u,q,m,f,e,v,B,H,x;(function(){var a=com.kingdee.bos.qing;g=a.CodeLoader;a=com.kingdee.bos.qing.common.shared;
p=a.LongtimeWaitingMask;a=com.kingdee.bos.qing.core;u=a.Facade;q=a.QingModelAssistant;m=a.UserOperationReporter;a=com.kingdee.bos.qing.core.commonui;f=a.ExecutingProgressParser;a=com.kingdee.bos.qing.core.model;e=a.ModelBook;v=a.ModelPage;B=a.AbstractFilterPreparedModel;a=com.kingdee.bos.qing.square.ui;H=a.ExhibitionContent;x=a.ChartTypeFactory})();var y=this,D,K,r,N,E,I,M,w=new H,h,b,n=!1,z,Q,W,Y=!1,Z,na,ja=function(){D||(D=new C,D.setRemoteUrl(y.protectedGetRemoteUrl()));D.setTag(y.protectedGetRemoteTag());
D.setSkinName(y.protectedGetSkinName());return D};this.show=function(a){a=$(a?a:document.body);a.css("overflow","hidden");M=$("<div style='position:absolute; top:0; left:0; width:100%; height:100%'; overflow:hidden>");M.appendTo(a);M.on("contextmenu",function(k){k.ctrlKey&&(k.preventDefault(),y.protectedDisplayConsumingStatistics(y.protectedGetRemoteTag()))});b=new O;b.bindParentJqUi(M);g.setCallback(function(){y.protectedInitMode();y.protectedCustomInitEnv();ia();y.protectedLoadingImpl(qa)});X.CommonCodeImporter.importSkin(g);
X.CommonCodeImporter.importI18n(g);y.protectedImportMoreCode(g)};this.displayError=function(a,k,A){ba(a,k,A)};this.displayActionPrompt=function(a,k){var A=new ta;A.setPromptText(k);A.show(a)};this.protectedGetRemoteTag=function(){throw Error("Override");};this.protectedInitMode=function(){};this.protectedBlockingAllFrame=function(){};this.protectedGetRemoteUrl=function(){throw Error("Override");};this.protectedImportMoreCode=function(a){};this.protectedCustomInitEnv=function(){};this.protectedLoadingImpl=
function(a){throw Error("Override");};this.protectedDrawCustomLegend=function(a,k){};this.protectedGetSkinName=function(){return"white"};this.protectedDisplayConsumingStatistics=function(a){throw Error("Override");};this.setPredrawListener=function(a){w.setPredrawListener(a)};this.setExecutedListener=function(a){z=a};this.setFilteringListener=function(a){Q=a};this.getTooltipsWidget=function(){return w.getTooltipsWidget()};this.setSelectionListener=function(a){w.setSelectionListener(a)};this.setCosmeticHandler=
function(a){w.setCosmeticHandler(a)};this.hookExecutingWaitingImpl=function(a){W=a};var ia=function(){w.setContextApi({getMeta:function(){return K},getDependentMeta:pa,getSquareModel:ra,getJsonAdditionalFieldNames:ha,getJsonAdditionalFilters:aa,createFacade:function(a,k){k=k?k:ba;a=new u(ja(),a,k);ma(a);return a}})},ma=function(a){var k=y.protectedBlockingAllFrame();if(null===k)return a.setShowBlocking(!1),!1;a.setShowBlocking(!0);a.setBlockingJqUi(k?$(document.body):M.parent());return!0},qa=function(a,
k,A){E=k;I=A;k=new e;k.fromJsonObject(a,new V);r=k.getModelPages()[0].getModel();K=k.getMeta();N=null;q.verifyLinkageBizMeta(r);r.addModelChangedListener(function(R){w.getCommandManager().untilWakeup(function(){fa()})});fa(Z);Z=null;return k},ea=function(){var a=E?E():null;return a?a.toDisplayJsonObject():null},aa=function(){var a=E?E():null;return a?a.toExecutableJsonObject():null},ha=function(){var a=E?E():null;return a?a.toMetaFieldNames():null},oa=function(){var a=r.getChart();a=a.getChartProperty().getPalette()?
null:a.getChartTypeName();return I?I(a):null},pa=function(a){var k=ha(),A=[];a&&(A=A.concat(a));k&&(A=A.concat(k));return r.createDependentMeta(K,A)},ra=function(){return r};this.reExecute=function(){return r?(fa(),!0):!1};this.executeWithoutRendering=function(a,k){var A=r?!0:!1;A?fa(k):Z=k;a(A,function(R,c){R?(R=c[0],b.setErrorOccurred(!1),M.empty(),d(R),z&&z(!0)):(ba(c[0],c[1],c[2]),z&&z(!1))})};var fa=function(a){var k=(new Date).getTime();na=k;var A=new u(ja(),function(c){k<na||(a?a(!0,[c]):(b.setErrorOccurred(!1),
M.empty(),d(c),z&&z(!0)))},function(c,l,t){if(!(k<na)){if(a)a(!1,[c,l,t]);else{if(-1==c&&n)return!0;b.bindRetry(this,fa,[]);ba(c,l,t);z&&z(!1)}return!0}},function(){R&&la().hideWaiting()}),R=ma(A);R&&(A.setCancelable(!0),A.setShowBlocking(!1),A.setProgressListener(function(c){la().hookWaitingProgressDisplayer(f.makeUiCreator(c))}));A=A.squareExecute(pa(),r,N,aa(),oa());R&&la().showWaiting(A)},la=function(){if(!W){var a;W={showWaiting:function(k){if(!a){var A=y.protectedBlockingAllFrame()?$(document.body):
M.parent();a=new p;a.hookOwner(A,null)}a.showWaiting(f.getWaitingText(),k)},hookWaitingProgressDisplayer:function(k){a&&a.hookProgressDisplayer(k)},hideWaiting:function(){a&&(a.hideWaiting(),a=null)}}}return W},d=function(a){Y||(n=!0,a=w.setModel(a.squareView,r.getChart()),y.protectedDrawCustomLegend(a.getChartTypeName(),a.getLegendModel()),ka())},F=function(){for(var a=r.getFilterSet().copyFiltersForSetting(),k=0;k<a.length;k++)a[k].addValueChangedListener(function(A){for(var R=0;R<a.length;R++){var c=
a[R];c!=A&&c.isJustShowAffected()&&c.innerCarryPreparedModel(null)}});return a},L=function(a,k,A,R){a=r.getFilterSet().toInsteadJson(a);var c=k.getAssociatedField(),l=new u(ja(),function(t){t=B.create(t);k.setPreparedModel(t);A(!0)},function(t,P){A(!1)});ma(l);R&&l.setBlockingJqUi(R);l.getSquareFilterPreparedValue(pa(),r,a,c,aa())},ca=function(a){r.getFilterSet().applyFiltersFromSetting(a);fa();Q&&Q();m.occur(m.SQUARE_EXTRA_FILTER,1)};this.showExtraFilter=function(a){h||(h=new com.kingdee.bos.qing.core.ui.ExtraFilter,
h.setContextApi(F,L,ca));h.show(a)};this.showChartInfo=function(a){var k=new ua,A=k.askMaxSize(a);A=w.createChartInfoUi(ea(),function(){k.hide()},function(R,c){k.suggestSize(R,c)},A[0],A[1]);k.setContent(A.createJqUi());k.show(a)};this.showInsight=function(a){var k=new ua,A=k.askMaxSize(a);A=w.createInsightUi(function(){k.hide()},function(R,c){k.suggestSize(R,c)},A[0],A[1]);k.setContent(A.createJqUi());k.show(a)};this.getDescription=function(){return r.getChart().getChartProperty().getDescription()};
var ka=function(){!b.isErrorOccurred()&&n&&(h&&h.hide(),w.drawChart(M))},ba=function(a,k,A){Y||(M.empty(),n=!1,b.setErrorOccurred(!0),b.highPriorityHandler(a,k)||y.protectedShowErrorImpl(M,a,k,A)||b.lowPriorityHandler(a,k,A))};this.protectedShowErrorImpl=function(a,k,A,R){return!1};this.executeOutputParamValue=function(a,k,A,R){k=a==r?aa():null;var c=new u(ja(),function(l){R(l)},function(l,t,P){console&&console.warn("executeOutputParamValue error. "+l+", "+t);R(null)});c.setShowBlocking(!1);c.setCancelable(!0);
c.executeBriefOutput(K,a,null,k,A)};this.protectedMethod={createChartInfoUi:function(a){return w.createChartInfoUi(ea(),a)},createInsightUi:function(a){return w.createInsightUi(a)},createInsightContentMaker:function(){return w.createInsightContentMaker()},changeChartType:function(a){var k=x.getInstance(a),A=x.getInstance(r.getChartTypeName());a=r.getChart().getGarbageProperties();A=A.willTransform(r.getChart());k=k.transform(A);k.setGarbageProperties(a);r.setChart(k);a=new v;a.setModel(r);a.setPreferences(N);
k=new e;k.setMeta(K);k.setModelPages([a]);return k.toJsonObject(new V)},copyFilters:F,updateFilterPreparedValue:L,filtering:ca,setTooltipsWidget:function(a){w.setTooltipsWidget(a)},setRollOutHandler:function(a){w.setRollOutHandler(a)},redraw:ka,destroy:function(){Y=!0;w.destroy();Q=z=null}}}function O(){var g,p;(function(){var w=com.kingdee.bos.qing.framework.common;g=w.MultilanguageManager.createPackageAccessor(com.kingdee.bos.qing.core.ui);w=com.kingdee.bos.qing.core.commonui;p=w.ErrorCodeParser})();
var u=this,q,m,f=!1,e,v,B,H=10,x;this.bindParentJqUi=function(w){q=w};this.setErrorOccurred=function(w){f=w;m&&m.remove();m=null;f||(H=10,u.bindRetry(null,null,null),clearTimeout(x))};this.isErrorOccurred=function(){return f};this.bindRetry=function(w,h,b){e=w;v=h;B=b};this.highPriorityHandler=function(w,h){clearTimeout(x);if(-1==w)return N(),!0;if(205401==w||205402==w)return E(),!0;var b=p.toDisplayText(w,h);return b?(r(b,[w,h]),!0):!1};this.lowPriorityHandler=function(w,h,b){b=g.get("cardPromptErrorOccurred",
"\u51fa\u9519\u4e86");r(b,[w,h])};var y=function(){m||(m=$("<div>"),m.addClass("sa-scene-card-errorprompt"),m.appendTo(q));return m},D=function(w){var h=$("<div>");h.addClass("sa-scene-card-errorprompt-text");h.text(w);h.appendTo(y());return h},K=function(w,h){var b=$("<span>");b.addClass("sa-scene-card-errorprompt-button");b.text(w);b.appendTo(y());b.on("click",function(n){h(b)})},r=function(w,h){D(w);K(g.get("cardPromptShowErrorDetail","\u67e5\u770b\u66f4\u591a..."),function(b){b.remove();D(" ");
for(b=0;b<h.length;b++)D(h[b])})},N=function(){K(g.get("cardPromptReExecute","\u91cd\u65b0\u6267\u884c"),function(w){clearTimeout(x);M()})},E=function(){D(g.get("cardPromptNotEnoughMemory","\u670d\u52a1\u5668\u5fd9\uff0c\u7a0d\u540e\u91cd\u8bd5..."));I(D(""));K(g.get("cardPromptTryAgainRightNow","\u7acb\u5373\u5237\u65b0"),function(w){clearTimeout(x);M()})},I=function(w){var h=H,b=function(){w.text(h);h--;0>h?(H=Math.max(1,Math.min(300,3*H)),M()):x=setTimeout(b,1E3)};b()},M=function(){y().empty();
D(g.get("cardPromptTrying","\u5c1d\u8bd5\u4e2d..."));setTimeout(function(){v.apply(e,B)},1E3)}}function V(){var g=com.kingdee.bos.qing.longer.model.AnalyticalModel,p=com.kingdee.bos.qing.longer.model.AnalyticalPreferences,u=com.kingdee.bos.qing.square.model.SquareModel,q=com.kingdee.bos.qing.square.model.SquarePreferences;this.encodeModelPageType=function(m){if(m instanceof g)m="L";else if(m instanceof u)m="S";else throw Error("Modify here.");return m};this.decodeModelPageType=function(m,f){if("L"==
m)f.setModel(new g),f.setPreferences(new p);else if("S"==m)f.setModel(new u),f.setPreferences(new q);else throw Error("Modify here.");};this.createView=function(m){var f=com.kingdee.bos.qing.core.ui.ViewConfig;if(m==f.TYPE_LongPainting)return new com.kingdee.bos.qing.longer.ui.LongPaintingDesk;if(m==f.TYPE_Square){m=com.kingdee.bos.qing.framework.common.MultilanguageManager.createPackageAccessor(com.kingdee.bos.qing.square.ui);f=com.kingdee.bos.qing.square.model.PreviewSetupItem;var e=com.kingdee.bos.qing.square.ui.SquareDesk;
e.setPreviewSetupItems([new f(m.get("cardFullArea","\u5168\u753b\u9762"),-1,-1,20,20,20),new f(m.get("cardCommonName","\u5361\u7247")+"1",314,210,40,10,20),new f(m.get("cardCommonName","\u5361\u7247")+"2",628,210,40,10,20),new f(m.get("cardCommonName","\u5361\u7247")+"3",314,420,40,10,20),new f(m.get("cardCommonName","\u5361\u7247")+"4",628,420,40,10,20)]);return new e}throw Error("Modify here.");}}function sa(){var g=com.kingdee.bos.qing.common.DomUtil,p=$("<div>"),u,q,m;this.addTabPanel=function(e){var v=
$("<div>");v.addClass("sa-scene-tab-head");v.appendTo(p);v.on("click",function(x){q=e;f(v)});g.makeSelectable(v,!1);var B=e.getTitle(),H=$("<div>");H.addClass("sa-scene-tab-head-text-"+(128>B.charCodeAt(0)?"en":"cn"));H.text(B);H.appendTo(v)};this.setCurrentTabPanel=function(e){q=e};this.initUi=function(e){u=$("<div>");u.addClass("sa-scene-tab-container");u.appendTo(p);var v=$("<div>");v.addClass("sa-scene-tab-hulk");v.appendTo(p);p.css({position:"absolute",left:0,right:0,top:0,bottom:0});p.addClass("sa-scene-tab");
p.appendTo(e);e=p.children(".sa-scene-tab-head");for(v=0;v<e.length;v++){var B=$(e[v]);if(B.text()==q.getTitle()){f(B);break}}};this.setChangedListener=function(e){m=e};var f=function(e){p.children(".sa-scene-tab-head").removeClass("sa-scene-tab-head_selected");e.addClass("sa-scene-tab-head_selected");e=q.getJqUi();for(var v=u.children(),B=!1,H=0;H<v.length;H++){var x=v[H],y=$(x);x==e[0]?(B=!0,y.css("display","block"),x=q,y=x.into(),m&&m(x,y)):y.css("display","none")}B||(e.css({position:"absolute",
left:0,right:0,top:0,bottom:0}),e.appendTo(u),e=q,v=e.into(),m&&m(e,v))}}function wa(g,p,u){var q,m=!0;this.getType=function(){return g};this.getTitle=function(){return p};this.getDesigner=function(){return u};this.getJqUi=function(){q||(q=u.createJqUi(),q.find(".sa-toolbar").addClass("sa-scene-tab-toolbar"));return q};this.into=function(){var f=m;m=!1;u.resize();return f}}function xa(){var g,p,u,q;(function(){var f=com.kingdee.bos.qing.longer.model;g=f.AnalyticalModel;p=f.AnalyticalPreferences;u=
f.MarkFieldSet;q=f.AnalyticalField})();this.transform=function(f){var e=new g,v=f.getModel();v.getChart().lookupAllItemModelSet(function(B){B=B.getSquareField();B=m(B);B.isMeasure()?(e.getMarkFieldSet().add(B),e.getMarkFieldSet().setFieldMatchingMarkType(B,u.TYPE_LABEL)):e.getRowAnalyticalFieldSet().add(B)});v.getFilterSet().traversalItems(function(B){var H=B.getFilter();B=B.getSquareField();B=m(B);e.getFilterFieldSet().add(B);e.getFilterFieldSet().setFilter(B,H)});v=new p;v.getDesignerStatus().setHide(!1);
f.setModel(e);f.setPreferences(v)};var m=function(f){var e=new q;e.setMetaField(f.getMetaField());e.setDisplayName(f.getDisplayName());e.setRole(f.getRole(),f.getAggregation());e.setContinuous(f.isContinuous());e.setNumberFormat(f.getNumberFormat());e.setDateFormat(f.getDateFormat());e.setPartValue(f.getPartValue());e.setQuickSetup(f.getQuickSetup());return e}}function ta(){var g=com.kingdee.bos.qing.common.DomUtil;com.kingdee.bos.qing.core.commonui.AbstractCoveredSlideDownUi.call(this);var p=this.protectedMethod,
u;this.setPromptText=function(q){u=q};this.protectedInitJqUi=function(q,m,f){p.createPromptLabel(u).appendTo(f);q=Math.min(240,parseInt(.9*q));m=Math.min(80,parseInt(.9*m));g.layoutCtrlWithLRTB(f,null,4,q,4,null,m);p.initManualClosable(f)}}function ua(){var g=com.kingdee.bos.qing.common.DomUtil;com.kingdee.bos.qing.core.commonui.AbstractCoveredSlideDownUi.call(this);var p=this.protectedMethod,u,q,m;this.setContent=function(f){u=f};this.askMaxSize=function(f){var e=f.prop("clientWidth");f=f.prop("clientHeight");
return p.getComfortableSize(e,f)};this.suggestSize=function(f,e){q?q(!0,f,e):m=[f,e]};this.protectedInitJqUi=function(f,e,v){u.appendTo(v);g.layoutCtrlWithLRTB(u,0,0,null,0,0,null);var B=p.getComfortableSize(f,e);q=function(H,x,y){x=Math.min(B[0],Math.max(180,x+40));y=Math.min(B[1],Math.max(120,y+24));H?v.animate({width:x,height:y},200):g.layoutCtrlWithLRTB(v,null,4,x,4,null,y)};q(!1,m[0],m[1])}}"undefined"==typeof com&&(com={});"undefined"==typeof com.kingdee&&(com.kingdee={});"undefined"==typeof com.kingdee.bos&&
(com.kingdee.bos={});"undefined"==typeof com.kingdee.bos.qing&&(com.kingdee.bos.qing={});var X=com.kingdee.bos.qing;X.RemoteImpl=C;X.SceneCommonUtil=G;X.AbstractDesignerScene=function(){var g,p,u,q,m,f,e;(function(){var b=com.kingdee.bos.qing;g=b.CodeLoader;b=com.kingdee.bos.qing.framework.common;p=b.WebPageInitializer;u=b.MultilanguageManager;q=b.WindowResizeObserver;b=com.kingdee.bos.qing.core;m=b.UserOperationReporter;b=com.kingdee.bos.qing.core.ui;f=b.Main;e=b.ViewConfig})();var v=this,B=new G,
H,x=0,y,D;this.preload=function(b){g.setCallback(b);X.CommonCodeImporter.importSkin(g);X.CommonCodeImporter.importI18n(g);b=g.createSafety();v.protectedImportMoreCode(b);b.load()};this.start=function(b){K();v.protectedCustomInitEnv(function(){I($(b?b:document.body))})};this.protectedGetRemoteUrl=function(){throw Error("Override me.");};this.protectedImportMoreCode=function(b){};this.protectedCustomInitEnv=function(b){throw Error("Override me.");};this.protectedInitDesignerForLonger=function(b){throw Error("Override me.");
};this.protectedInitDesignerForSquare=function(b){throw Error("Override me.");};this.protectedLoadingLonger=function(b,n,z){throw Error("Override me.");};this.protectedIntoTab=function(b,n){};this.protectedLoadingSquare=function(b,n,z){throw Error("Override me.");};this.getRemoteImpl=function(){H||(H=new C,H.setRemoteUrl(v.protectedGetRemoteUrl()),H.setTag(B.getParamTag()));return H};var K=function(){p.init();m.hookCollector(function(n,z){com.kingdee.bos.qing.behavior.BehaviorManager.interestInBehavior(n,
z)});r();var b=new q;b.setCallbackImmediately(function(){r()});b.setDelay(250);b.setCallback(function(){D&&D.resize()});b.observe()},r=function(){document.body.style.height=document.documentElement.clientHeight+"px"},N=function(b){v.protectedLoadingLonger(v.getRemoteImpl(),b,function(n){n||b.born()})},E=function(b){v.protectedLoadingSquare(v.getRemoteImpl(),b,function(n){n||b.born()})},I=function(b){if(0==x)throw Error("Please setModule() first.");if(1==x||16==x)1==(x&1)?D=h(1):16==(x&16)&&(D=h(16)),
D.createJqUi().appendTo(b),D.resize(),1==(x&1)?N(D):16==(x&16)&&E(D);else{var n=M();n.setChangedListener(function(z,Q){D=z.getDesigner();if(Q)if(1==z.getType())N(D);else if(16==z.getType())E(D);else throw Error("Modify here.");v.protectedIntoTab(D,Q)});n.initUi(b)}},M=function(){var b=u.createPackageAccessor(com.kingdee.bos.qing.core.ui),n=new sa;if(1==(x&1)){var z=b.get("moduleLonger","\u6570\u636e\u5206\u6790");w(n,1,z)}16==(x&16)&&(z=b.get("moduleSquare","\u6570\u636e\u6597\u65b9"),w(n,16,z));
if(!D)throw Error("Current panel hasn't be appointed.");return n},w=function(b,n,z){var Q=h(n);z=new wa(n,z,Q);b.addTabPanel(z);y==n&&(b.setCurrentTabPanel(z),D=Q)},h=function(b){var n=new f;n.setRemoteImpl(v.getRemoteImpl());n.getConductor().setConsumingStatisticsDisplayer(function(){v.protectedDisplayConsumingStatistics(B.getParamTag())});if(16==b)b=e.TYPE_Square,v.protectedInitDesignerForSquare(n);else if(1==b)b=e.TYPE_LongPainting,v.protectedInitDesignerForLonger(n);else throw Error("Illegal arguments iModule: "+
b);var z=new e;z.setSupportedType(b);n.setViewConfig(z);n.setViewIntegration(new V);return n};this.protectedDisplayConsumingStatistics=function(b){throw Error("Override");};this.protectedMethod={getUrlParamUtil:function(){return B},setModuleWithLonger:function(b,n){b?(x|=1,n&&(y=1)):x&=-2},setModuleWithSquare:function(b,n){b?(x|=16,n&&(y=16)):x&=-17},getCurrentVisibleDesigner:function(){return D},createSquare2LongerModelTransformer:function(){return new xa}}};X.AbstractModalDesignerScene=function(){var g,
p,u,q,m,f,e,v,B,H;(function(){var h=com.kingdee.bos.qing.common;g=h.DomUtil;h=com.kingdee.bos.qing.framework.common;p=h.MultilanguageManager.createPackageAccessor(com.kingdee.bos.qing.core.ui);u=h.WindowResizeObserver;h=com.kingdee.bos.qing.ui.component;q=h.SimpleConfirmer;h=com.kingdee.bos.qing.common.shared;m=h.LongtimeWaitingMask;f=h.DataPreparingProgressParser;h=com.kingdee.bos.qing.core;e=h.Facade;h=com.kingdee.bos.qing.core.commonui;v=h.RuntimePopupSupporter;h=com.kingdee.bos.qing.core.ui;B=
h.Main;H=h.ViewConfig})();var x=this,y,D,K,r,N,E,I;this.setRemoteUrl=function(h){y=h};this.setRemoteTag=function(h){D=h};this.setClosable=function(h,b){E=h?b?b:function(){}:null};this.show=function(h,b){var n=new H;n.setSupportedType(x.protectedIsSquare()?H.TYPE_Square:H.TYPE_LongPainting);r=new B;r.setRemoteImpl(w());r.setViewConfig(n);r.setViewIntegration(new V);r.getConductor().setConsumingStatisticsDisplayer(function(){x.protectedDisplayConsumingStatistics(D)});x.protectedInitDesigner(r);N=$("<div>");
N.css("z-index",256);N.css("background-color","rgba(0,0,0,0.4");N.appendTo($(document.body));g.layoutCtrlWithLRTB(N,0,0,null,0,0,null);var z=$("<div>");z.css("border-radius","4px");z.css("overflow","hidden");z.appendTo(N);g.layoutCtrlWithLRTB(z,20,20,null,20,20,null);n=$("<div>");n.text(h);n.addClass("sa-ctrl-dialog-title");n.css("z-index",1);n.appendTo(z);h=$("<div>");h.css("z-index",1);h.appendTo(z);g.layoutCtrlWithLRTB(h,0,0,null,n.outerHeight(),0,null);if(E){var Q=$("<div>");Q.css("z-index",2);
Q.addClass("sa-ctrl-dialog-close");Q.text("\u00d7");Q.appendTo(z);Q.on("click",function(Y){r.getConductor().isDirty()?(Y=new q,Y.setText(p.get("confirmQuittingModalDesigner","\u662f\u5426\u653e\u5f03\u4fee\u6539\u5e76\u9000\u51fa\uff1f")),Y.setConfirmedListener(function(Z){Z&&(E(),x.hide(),W.destroyWhenClosed())}),Y.show(Q)):(E(),x.hide(),W.destroyWhenClosed())});n=$("<div>");n.css("z-index",2);n.appendTo(z);g.layoutCtrlWithLRTB(n,null,36,30,6,null,30);var W=new v;W.setup(n);W.hookAction(function(){g.layoutCtrlWithLRTB(z,
4,4,null,4,4,null)},function(){g.layoutCtrlWithLRTB(z,20,20,null,20,20,null)})}r.createJqUi().appendTo(h);r.resize();I=new u;I.setDelay(250);I.setCallback(function(){r.resize()});I.observe();M(b)};this.hide=function(){I.unobserve();r.destroy();N.remove()};var M=function(h){h=new e(w(),function(n){r.prepareMeta(n);x.protectedLoading(r,function(z){z||r.born()})},h,function(){b.hideWaiting()});h.setShowBlocking(!1);h.setProgressListener(function(n){b.hookProgressDisplayer(f.makeUiCreator(n))});h.getMeta();
var b=new m;b.setIconVisible(!0);b.hookOwner($(document.body),null);b.showWaiting(f.getWaitingText(),null)};this.protectedIsSquare=function(){throw Error("Override me");};this.protectedInitDesigner=function(h){throw Error("Override me");};this.protectedDisplayConsumingStatistics=function(h){throw Error("Override");};this.protectedLoading=function(h,b){throw Error("Override me");};var w=function(){K||(K=new C,K.setRemoteUrl(y),K.setTag(D));return K}};X.AbstractSquareIframeScene=function(){var g,p,
u;(function(){var e=com.kingdee.bos.qing.framework.common;g=e.WebPageInitializer;p=e.WindowResizeObserver;e=com.kingdee.bos.qing.core;u=e.UserOperationReporter})();S.call(this);var q=this.protectedMethod,m=new G;this.protectedGetRemoteTag=function(){return m.getParamTag()};this.getUrlParam=function(e){return m.getUrlParam(e)};this.protectedInitMode=function(){g.init();u.hookCollector(function(v,B){com.kingdee.bos.qing.behavior.BehaviorManager.interestInBehavior(v,B)});f();var e=new p;e.setCallbackImmediately(function(){f()});
e.setDelay(10);e.setCallback(function(){q.redraw()});e.observe()};this.protectedBlockingAllFrame=function(){return!0};var f=function(){document.body.style.height=document.documentElement.clientHeight+"px"}};X.AbstractSquareDivScene=function(){S.call(this);var g=this.protectedMethod,p,u;this.setRemoteTag=function(q){p=q};this.protectedGetRemoteTag=function(){return p};this.setRemoteUrl=function(q){u=q};this.protectedGetRemoteUrl=function(){return u};this.protectedBlockingAllFrame=function(){return!1};
this.redraw=function(){g.redraw()};this.destroy=function(){g.destroy()}};X.AbstractLongerIframeScene=function(){var g,p,u;(function(){var e=com.kingdee.bos.qing.framework.common;g=e.WebPageInitializer;p=e.WindowResizeObserver;e=com.kingdee.bos.qing.core;u=e.UserOperationReporter})();J.call(this);var q=this.protectedMethod,m=new G;this.protectedGetRemoteTag=function(){return m.getParamTag()};this.protectedInitMode=function(){g.init();u.hookCollector(function(v,B){com.kingdee.bos.qing.behavior.BehaviorManager.interestInBehavior(v,
B)});f();var e=new p;e.setCallbackImmediately(function(){f()});e.setDelay(10);e.setCallback(function(){q.resize()});e.observe()};var f=function(){document.body.style.height=document.documentElement.clientHeight+"px"};this.protectedMethod.getUrlParamUtil=function(){return m}};X.AbstractLongerDivScene=function(){J.call(this);var g,p;this.setRemoteUrl=function(u){g=u};this.protectedGetRemoteUrl=function(){return g};this.setRemoteTag=function(u){p=u};this.protectedGetRemoteTag=function(){return p}};X.AbstractMobileLongerScene=
function(){var g,p,u,q,m,f,e,v,B,H,x;(function(){var c=com.kingdee.bos.qing.common;g=c.DomUtil;c=com.kingdee.bos.qing.core;p=c.Facade;q=c.QingModelAssistant;c=com.kingdee.bos.qing.core.model;u=c.ModelBook;m=c.ModelPage;f=c.AbstractAnalyticalField;e=c.DiscreteFilter;v=c.AbstractFilterPreparedModel;c=com.kingdee.bos.qing.longer.model;B=c.AnalyticalModel;c=com.kingdee.bos.qing.core.controller;H=c.CommandManager;c=com.kingdee.bos.qing.longer.ui;x=c.ExecutableExhibition})();var y=this,D,K,r,N,E,I,M,w,
h,b,n,z,Q,W,Y,Z;this.protectedLoadDesignerOperationJudger=function(c){throw Error("Override");};var na=function(c){y.protectedLoadDesignerOperationJudger(function(l){c(l.isDataDetailReadable())})},ja=function(c){y.protectedLoadDesignerOperationJudger(function(l){c(l.isExportable())})};this.show=function(c){b=new x;b.setRowColumnDraggable(!1);b.setFakeClipboardSupported(!1);b.initCacheLoader();b.setLegendsNeededListener(F);b.setContextGetter(R());b.setTooltipsWidgetInstance(y.protectedCreateTooltipsWidgetInstance());
b.initTooltipsWidget(na,ja,L,ca,a,ba);b.setExecutedListener(ha);b.setPreUpdateListener(fa);b.setExcutedModelChangedListener(ra);c=$(c);var l=b.getJqUi();g.layoutCtrl(l,0,0,"100%","100%");l.appendTo(c);Y=$("<div>");Y.appendTo(c);g.layoutCtrl(Y,0,0,"100%","100%");Z=$("<div>");Z.appendTo(c);g.layoutCtrl(Z,0,0,"100%","100%");z=new O;z.bindParentJqUi(Z)};this.protectedCreateTooltipsWidgetInstance=function(){return null};this.displayError=function(c,l,t){oa(!1);pa([c,l,t])};this.displayActionPrompt=function(c,
l){throw Error("Unsupported.");};this.destroy=function(){b&&b.destroy();W=Q=null};this.setExecutedListener=function(c){Q=c};this.setFilteringListener=function(c){W=c};this.redraw=function(){b&&b.repaint(n)};var ia=function(){K||(K=new C,K.setRemoteUrl(y.protectedGetRemoteUrl()),K.setTag(y.protectedGetRemoteTag()));K.setSkinName(y.protectedGetSkinName());return K};this.protectedGetRemoteUrl=function(){throw Error("Override");};this.protectedGetRemoteTag=function(){throw Error("Override");};this.protectedGetSkinName=
function(){return"white"};this.setJsonModelBook=function(c,l,t){t=new u;t.fromJsonObject(c,new V);c=t.getModelPages()[0];N=t.getMeta();E=c.getModel();I=c.getPreferences();M=l;w=I.getExhibitionStatus().getWidths();h=I.getExhibitionStatus().getHeights();q.verifyLinkageBizMeta(E);E.addModelChangedListener(ma);ea();return t};this.getJsonModelBook=function(){var c=I.getExhibitionStatus();b.collectStatus(c);c=new m;c.setModel(E);c.setPreferences(I);var l=new u;l.setMeta(N);l.setModelPages([c]);return l.toJsonObject(new V)};
var ma=function(c){c.isContainKeys([B.KEY_SORTING_LANE,f.KEY_SORT])&&b.keepScrollStatus(!0);k().untilWakeup(aa)},qa=function(c){for(var l=0;l<c.getCount();l++){var t=c.getFilter(l);t instanceof e&&t.abandonExclude()}};this.reExecute=function(){return E?(ea(),!0):!1};this.executeWithoutRendering=function(c,l){var t;b.setRenderingInterceptor(function(U){t=U;l(null,null)});var P=E?!0:!1;P&&ea();c(P,function(U,T){t()})};var ea=function(){var c=ba(),l=a();l=E.createDependentMeta(N,l);var t=I.createExecutingCopy(E.getChartType());
b.christmasExecute(l,E,t,c,!0,qa)},aa=function(){var c=ba(),l=a();l=E.createDependentMeta(N,l);var t=I.createExecutingCopy(E.getChartType());b.execute(l,E,t,c)},ha=function(c,l,t){c?(oa(!0),z.setErrorOccurred(!1)):(oa(!1),pa(l));Q&&Q(c)},oa=function(c){c?(Y.css("display",""),Z.css("display","none")):(Y.css("display","none"),Z.css("display",""))},pa=function(c){Z.empty();z.setErrorOccurred(!0);var l=c[0],t=c[1];c=c[2];z.highPriorityHandler(l,t)||y.protectedShowErrorImpl(Z,l,t,c)||z.lowPriorityHandler(l,
t,c)};this.protectedShowErrorImpl=function(c,l,t,P){return!1};var ra=function(c){n=c},fa=function(c,l,t){d(t,y.protectedPreUpdateLegend)||y.protectedPreUpdateLegend(null);var P="auto";t=I.getExhibitionStatus();if(y.protectedIsWidthFitting()){var U=b.getJqUi().innerWidth(),T=t.getPaintableWidths();0<T.length&&(P=la(U,T,l),t.setWidths(P),P="hidden")}else t.setWidths(w);y.protectedIsHeightFitting()?(l=b.getJqUi().innerHeight(),U=t.getPaintableHeights(),0<U.length&&(c=la(l,U,c,15),t.setHeights(c))):t.setHeights(h);
b.applyStatus(t);b.setScrollerVisible(P,"auto")};this.protectedIsWidthFitting=function(){throw Error("Override");};this.protectedIsHeightFitting=function(){throw Error("Override");};var la=function(c,l,t,P){for(var U=0,T=0;T<l.length-1;T++)U+=l[T];U+=l[l.length-1]*t;t=[];for(T=0;T<l.length;T++)t[T]=l[T]/U;U=[];for(T=0;T<l.length;T++){var da=Math.round(c*t[T]);P&&(da=Math.max(da,P));U[T]=da}return U},d=function(c,l){for(var t=0;t<c.length;t++){var P=c[t];if(P&&"discreteColor"==P.getType())return l(P.getModel()),
!0}return!1};this.protectedPreUpdateLegend=function(c){throw Error("Override");};var F=function(c){d(c,y.protectedUpdateLegend)||y.protectedUpdateLegend(null)};this.protectedUpdateLegend=function(c){throw Error("Override");};var L=function(){return N},ca=function(){return E},ka=function(){return I},ba=function(){var c=M?M():null;return c?c.toExecutableJsonObject():null},a=function(){var c=M?M():null;return c?c.toMetaFieldNames():null},k=function(){!r&&(r=new H);return r},A=function(c,l,t){c=new p(ia(),
c,l,t);y.protectedIsBlockingRemoteCall()?(c.setShowBlocking(!0),c.setBlockingJqUi(b.getJqUi())):c.setShowBlocking(!1);return c};this.protectedIsBlockingRemoteCall=function(){return!0};var R=function(){return{getMeta:L,getAnalyticalModel:ca,getPreferences:ka,getCommandManager:k,createFacade:A,getBlockingJqUi:function(){return b.getJqUi()}}};this.executeOutputParamValue=function(c,l,t,P){var U=c==E?ba():null,T=new p(ia(),function(da){P(da)},function(da,va,ya){console&&console.warn("executeOutputParamValue error. "+
da+", "+va);P(null)});T.setShowBlocking(!1);T.setCancelable(!0);T.executeBriefOutput(N,c,l,U,t)};this.protectedMethod={getUrlParamUtil:function(){!D&&(D=new G);return D},createFacade:A,copyFilters:function(){for(var c=E.getFilterFieldSet().copyFiltersForSetting(),l=0;l<c.length;l++)c[l].addValueChangedListener(function(t){for(var P=0;P<c.length;P++){var U=c[P];U!=t&&U.isJustShowAffected()&&U.innerCarryPreparedModel(null)}});return c},updateFilterPreparedValue:function(c,l,t){var P=ba(),U=I.createExecutingCopy(E.getChartType());
c=E.getFilterFieldSet().toInsteadJson(c);var T=l.getAssociatedField();A(function(da){da=v.create(da);l.setPreparedModel(da);t(!0)},function(da,va){t(!1)}).getFilterPreparedValue(N,E,U,c,T,P)},filtering:function(c){E.getFilterFieldSet().applyFiltersFromSetting(c);aa();W&&W()}}};X.ModelHelper=new function(){this.fromJson=function(g){var p=new com.kingdee.bos.qing.core.model.ModelBook;p.fromJsonObject(g,new V);return p};this.toJson=function(g){return g.toJsonObject(new V)};this.mergeFilterState=function(g,
p){g.pages[0].model.filters=p;return g}}})();
//qingVersionTag: 20250324